### ISSUE TITLE
Number error by Russian

### ISSUE THREAD

**Issue by nepster-web** [giggsey/libphonenumber-for-php#102]
+79255077200 - is success
89255077200 - is fail

+7 - international
8 - Only in Russia

**Comment by giggsey** [comment]
Hi,

Both numbers appear as valid on both Google's demo for libphonenumber, and the libphonenumber-for-php demo.

| Number | libphonenumber | libphonenumber-for-php |
|-----------|----------------------|---------------------------------|
| +79255077200 | [Valid RU Mobile](http://libphonenumber.appspot.com/phonenumberparser?number=%2B79255077200&country=RU) | [Valid RU Mobile](http://libphonenumber-for-php.giggsey.net/index.php?phonenumber=%2B79255077200&country=RU&language=&region=) |
| 89255077200 | [Valid RU Mobile](http://libphonenumber.appspot.com/phonenumberparser?number=89255077200&country=RU) | [Valid RU Mobile](http://libphonenumber-for-php.giggsey.net/index.php?phonenumber=89255077200&country=RU&language=&region=) |


Can you provide a link to the demo that shows a problem?

**Comment by nepster-web** [comment]
Excuse me. I started to learn English.

My code example:

```php
        $tel = '89255077200';

        $phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
        try {
            $swissNumberProto = $phoneUtil->parse($tel, "CH");
            $isValid = $phoneUtil->isValidNumber($swissNumberProto);
        } catch (\libphonenumber\NumberParseException $e) {
            $isValid = false;
        }
        var_dump($isValid);
```

result:
```
bool(false) 
```

**Comment by giggsey** [comment]
You are trying to parse `89255077200` using `CH` (Switzerland) as the country code. It doesn't work because `89255077200` is not a valid number in Switzerland. When dialing internationally from Switzerland, the user would dial `00 7 925 507-72-00`.

If you used `RU` (Russia) as the country code when using calling the `parse()` function, it will return a valid number.

**Comment by nepster-web** [comment]
Thank you. I didn't notice it. It works.

**Comment by Sscorpion9991** [comment]
@giggsey Hi! Have the same issue:

+79255077200 - [is success on web](https://giggsey.com/libphonenumber/index.php?phonenumber=%2B79255077200&country=&language=&region=)
89255077200 -[ is fail on web](https://giggsey.com/libphonenumber/index.php?phonenumber=89255077200&country=&language=&region=) with exception `Missing or invalid default region.`

Could you have a look on this problem? Thanks.

**Comment by giggsey** [comment]
Did you pass a default region into the parse() function?

**Comment by Sscorpion9991** [comment]
@giggsey With default country works fine (https://giggsey.com/libphonenumber/index.php?phonenumber=89255077200&country=RU&language=&region=)

Thanks.
