### ISSUE TITLE
Is ISO 3166-1 mandatory?

### ISSUE THREAD

**Issue by samus-aran** [giggsey/libphonenumber-for-php#103]
As the Google's Demo doesn't require you to entry the ISO 3166-1 just wondering if that is a possibility in this project too?

**Comment by giggsey** [comment]
As per https://github.com/giggsey/libphonenumber-for-php/issues/85#issuecomment-147643646, you can leave it empty or null, providing that it can work out the phone number from what is provided (e.g. supplying the number in E164).

**Comment by samus-aran** [comment]
Thanks for that!
