### ISSUE TITLE
Formatting doesnt seem to work properly

### ISSUE THREAD

**Issue by rgpublic** [giggsey/libphonenumber-for-php#105]
I'm using this code:

    $phoneUtil = PhoneNumberUtil::getInstance();
    $number=$phoneUtil->parse("+492302580150", PhoneNumberFormat::E164);_EOL;
    echo $phoneUtil->format($number, PhoneNumberFormat::NATIONAL) . PHP_EOL;

I would expect the area code to be separate by a space from the rest of the number. This doesnt seem to happen. Strangely, when I'm using the online demo (http://giggsey.com/libphonenumber/) it works. Why?

**Comment by giggsey** [comment]
You are calling `parse()` with the country code being PhoneNumberFormat::E164.

Try changing that, and see if that helps?

**Comment by rgpublic** [comment]
Sorry, I don't think I understand. Why is PhoneNumberFormat::E164 wrong? I've got an international phone number (+CCXXXXXXXXX) without any spaces and separators. I want to format it properly with spaces between International Access Code, Area Access Code and Local Number. Isnt that possible. How must I change the code exactly? If I'm using this:

    $number=$phoneUtil->parse("+492302580150", "DE");_EOL;

it doesn't work either. Is any special PHP version required? Or any version of PCRE? I tried different PHP versions and servers to no avail...

**Comment by giggsey** [comment]
The [`parse()`](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberUtil.md#parse) function accepts a phone number, and a region code. This region code can be null if the number is already in an international format (like your example is).


However, I have tried your example, and it is working fine for me.

```php
<?php

require 'vendor/autoload.php';

use libphonenumber\PhoneNumberUtil;
use libphonenumber\PhoneNumberFormat;

$phoneUtil = PhoneNumberUtil::getInstance();
$number=$phoneUtil->parse("+492302580150", 'DE');
echo $phoneUtil->format($number, PhoneNumberFormat::NATIONAL) . PHP_EOL;
```

Output:

> 02302 580150

This is using PHP `7.0.5-2+deb.sury.org~trusty+1`, but I would expect the same result with 5.x. The pcre version in use by my PHP 7 install is `PCRE Library Version => 8.31 2012-07-06`.

There were some issues with the PCRE version included with PHP7, but the regex was patched to solve it.

**Comment by rgpublic** [comment]
Arrrgh. Facepalm. Found my mistake. When entering "libphonenumber php" the first Google result varies and sometimes the first result is this: https://github.com/davideme/libphonenumber-for-PHP. Which looks eerily similar, but is of course a fork. And one that's 4 years old. Sigh. And I was so dumb and just clicked "Download ZIP". It was very confusing because the method names and arguments didnt change over the years. And the demo worked - just with that little problem. Sigh... *Walks silently away in shame*. Thank you so much, giggsey, for investigating this.

**Comment by giggsey** [comment]
Ahh, that would explain it.

This project actually was the fork from the @davideme project, made because it wasn't getting updated.

Anyway. Glad your problem has been sorted.
