### ISSUE TITLE
Questions: Is it possible to Map mobile number MCC & MNC

### ISSUE THREAD

**Issue by momostafa** [giggsey/libphonenumber-for-php#110]
Hi Joshua,

Thank you very much for the awesome work, my coding skills is limited so please give clear example

1- is it Is it possible to Map mobile number MCC & MNC to the mobile operator something like here https://www.numberingplans.com/?page=plans&sub=imsinr 

2- is it possible to display information such as: 
  -Mobile Operator (this is i know how)
 -Mobile Prefix for matched operator
- All Mobile Prefixes for matched country

3- Is there a function that can get all mobile prefixes listed here https://github.com/giggsey/libphonenumber-for-php/tree/master/src/libphonenumber/carrier/data/en so i can save them in my database for further processing 

Thank you very much for your help

**Comment by giggsey** [comment]
1) As far as I can tell, MCC/MNC info is not stored at all within the libphonenumber project.

2) As you have already found, you can get the operator of a mobile number (the original range holder, due to number portability). However, there isn't a defined method of get this back to the Prefix.

3) If you look at PrefixFileReader, there is a function called getPhonePrefixDescriptions. You might be able to use that to get the prefix array.

**Comment by momostafa** [comment]
Hi Joshua,

thanks a lot for your directions i was able to pull the prefix list by replicating on of the functions in PrefixFileReader that solved my questions 2 & 3 

regarding MCC & MNC it would be of a great help to think about its implementation in future releases as all Messaging and Voice providers and agregators routing depends on it

Thanks again and have a nice day

**Comment by giggsey** [comment]
I'm glad you were able to extract the prefix list.

As for MCC & MNC, the feature would have to be added to Google's [libphonenumber](https://github.com/googlei18n/libphonenumber) before I add it to this PHP Port.

**Comment by momostafa** [comment]
Took me a very long night to figure it out )) thanks again for your help
I will add a note on Google's project

**Comment by giggsey** [comment]
I'm going to close this, as it's not directly related to libphonenumber-for-php.

If Google add this functionality, it'll get added here shortly after.

**Comment by danielsteiner** [comment]
It seems as if Google still has not added it - I think this is a feature that could be implemented in the PHP lib as well - there's a nice Wikipedia Article on MNC / MCC https://en.wikipedia.org/wiki/Mobile_country_code#Test_networks and the database wouldn't be that big.
