### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by lichunqiang** [giggsey/libphonenumber-for-php#111]
There is one correct phone number for KR: `+8201094313431`

But after parsed, The nationalNumber is `1094313431`

It should be `01094313431`

**Comment by lichunqiang** [comment]
Sorry

**Comment by giggsey** [comment]
The PHP version is returning the same result as Google's [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B8201094313431&country=KR).

As for the reason, leading zeros count as a national prefix for KR (and other countries). https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/data/PhoneNumberMetadata_KR.php#L136

If you want the number with the leading zero, you'll need to format it into the National Format.

**Comment by lichunqiang** [comment]
Thank you
