### ISSUE TITLE
Fatal error: Call to a member function hasLeadingDigits() 

### ISSUE THREAD

**Issue by wonderer007** [giggsey/libphonenumber-for-php#112]
**Fatal error: Call to a member function hasLeadingDigits() on a non-object in PhoneNumberUtil.php on line 1919** on input phone **+12023519852**

**Comment by giggsey** [comment]
Hi @wonderer007,

Can you provide a code example of what you are running to produce this error.

I've just tried on the demo, and it works fine.

**Comment by wonderer007** [comment]
I have huge database of phone numbers before porcessing any number i want to make sure is it valid or not. I just encountered this phone number 

```
use com\google\i18n\phonenumbers\PhoneNumberUtil;
use com\google\i18n\phonenumbers\PhoneNumberFormat;
use com\google\i18n\phonenumbers\NumberParseException;

require_once 'PhoneNumberUtil.php';

$phone_number = "+12023519852";
$phoneUtil = PhoneNumberUtil::getInstance();
try {
      $swissNumberProto = $phoneUtil->parseAndKeepRawInput($phone_number, "IN");
        var_dump($swissNumberProto);

} catch (NumberParseException $e) {
  echo $e;

}
$isValid = $phoneUtil->isValidNumber($swissNumberProto);//return true
var_dump($isValid);
```
I just updated the if check inside PhoneNumberUtil.php on line #1919 with 
`if ($metadata != null && $metadata->hasLeadingDigits()) {`

and on line # 1924 like

`} else if ($metadata != null && $this->getNumberTypeHelper($nationalNumber, $metadata) != PhoneNumberType::UNKNOWN) {`

its working fine for me now. I**s it the correct way ?**

**Comment by giggsey** [comment]
You're not using this library.

The namespace here is `\libphonenumber`, not `com\google\i18n\phonenumbers`.
