### ISSUE TITLE
Number of files in repo may cause inode issues

### ISSUE THREAD

**Issue by srcspider** [giggsey/libphonenumber-for-php#121]
Currently the library sits at around 2127 files. This by itself is not an issue, however in the context of the library sitting in a application that uses docker images and subsequently in a kubernetes node this can lead to inode issues as images get pushed and in use. Not by itself but in combination with other libraries with many many files. Many images can be instantiated on the same node and the way containers work (such as docker) means the inodes in use are taken from the host.

Looking at the data structure it seems like all the files in `carrier/data`, `data` and `geocoding` could easily sit in a single larger multi-dimensional map, since at least as far as I can tell most of them are just arrays of 4-6 key value mappings. This should remove at least 1989 files, ensuring the library isn't part of a "inode leak".

http://blog.scoutapp.com/articles/2014/10/08/understanding-disk-inodes

**Comment by fmp777** [comment]
Yea i was quite shocked at the size of this meat puppet too - looking for other alternatives

**Comment by giggsey** [comment]
Happy for suggestions to improve file count, need to be careful with memory usage too. #44 was an issue with memory usage and large arrays.

**Comment by giggsey** [comment]
I've pushed a branch (#138) which reduces the file count of src to 1000 files.

It should be possible to combine metadata files further, but it would require a fair amount more work. I'll have more of a review tomorrow, then hopefully merge it in ready for the next release.

**Comment by giggsey** [comment]
The new release has just been tagged which contains the prefix mapper changes. As my previous comment says, this has cut down the file count to approx 1000 files.

There was also another change that uses .gitattributes to exclude the Tests directory when exporting (so installing from dist on composer). This should further cut down the file count.

I'm going to close this issue now, as I believe it's in a much better position than before. If you feel it needs to be reduced further, please reopen.

**Comment by srcspider** [comment]
Thanks a lot giggsey. :+1:
