### ISSUE TITLE
getDescriptionForNumber() issue

### ISSUE THREAD

**Issue by git-webmaster** [giggsey/libphonenumber-for-php#122]
Hi!

Recreated an issue.
Seems like this is not a bug, but another function behaviour maybe.

In the previous release, i used this code below to get localized name of the phone's locality (when possible of course, but at least it worked for big cities like New York, Rome etc.):

`$number = $phoneUtil->parse("+1 646-282-3400", "US");
$geocoder = \libphonenumber\geocoding\PhoneNumberOfflineGeocoder::getInstance();
$phone_region = $geocoder->getDescriptionForNumber($number , "pt_BR");`

This way i was getting "Nova Iorque" for this number.

Now this code returns "New York" as $phone_region value if i specify only $locale (in getDescriptionForNumber params), and "Estados Unidos" if i also specify $userRegion as well.
This is not a behaviour that was before, if i am not mistaken.

Is there a way to get localized name of the phone's locality now (or at least something more than country name), using your great library?

Thanks!

**Comment by giggsey** [comment]
Hi,

I'm unable to do any testing on this for a few days, but are you able to tell me whether this worked as expected in 7.4.3 (The previous version)?

There were only metadata changes made in the latest release, so I want to try to find where the regression was introduced.

**Comment by git-webmaster** [comment]
Sorry, information that i provided is incorrect.
Closing this issue.
