### ISSUE TITLE
getRegionCodeForNumberFromRegionList returns null by default *ouch*

### ISSUE THREAD

**Issue by tschallacka** [giggsey/libphonenumber-for-php#123]
https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/PhoneNumberUtil.php#L689

That function returns null by default whilst there are valid items in the regionCodes array. The code just wasn't able to match it.

I came across it by some sample test data, and I couldn't figure out why it just wouldn't return the country code.

I changed that line into 

       return count($regionCodes) > 0 ? $regionCodes[0] : null;

that way it will return a default code(if available) if it wasn't able to match with it's known data.

That way an invalidly typed number, can still return a valid country code.

Or, let it throw an exception, which can be caught and handled.

**Comment by giggsey** [comment]
Do you have an example where this function fails?

**Comment by tschallacka** [comment]
+440645494440

it's an "invalid" english number, but there are voip services that will supply some really weird numbers when the price is right. It cannot be matched to any of the british countries, and then it defaults to null, whilst it should return something as a default from the array(I chose in my example the first index of the supplied array)

**Comment by giggsey** [comment]
How are you getting to that function though, as it's protected?

**Comment by tschallacka** [comment]
i'm not using it directly... I'm calling getRegionCodeForNumber($phonenumber)

https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/PhoneNumberUtil.php#L649

which calls

https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/PhoneNumberUtil.php#L659

which goes through a loop https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/PhoneNumberUtil.php#L668

where it finds no matches to predifined rules,
so it returns null.

In my opinion there should be at least a warning be raised, or anything better than null.
Null is evil. null tells us absolute zilch.

You have in the comments or null when when no region matches, but that was not the case. A region matched, the +44 does match a region. it just didn't fit in the ruleset as defined. If a customer had made a typing error, a 6 instead of a 7, he gets an non descript error message back, because nothign can be gathered from the API whats wrong.

A toggle to allow exceptions instead of nulls would be great.

**Comment by giggsey** [comment]
Okay, thanks.

Firstly, I'm unable to write an actual test to confirm, but the source of the Java version that this is a port from has the same behaviour (https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2168-2200).

Secondly, with your example (+440), how do you know what +44 region it belongs to? How can you be absolutely sure it's GB instead of JE, IM etc. when it's invalid? isPossibleNumber() would return false for the number you provided.

**Comment by giggsey** [comment]
As a side note:

> it's an "invalid" english number, but there are voip services that will supply some really weird numbers when the price is right

I feel your pain here. I've encountered this on a personal level. Although I've not encountered one that passes a leading zero in E164 for a UK number. I use libphonenumber for dealing with different number formats from different SIP providers, but only on a best effort level. If libphonenumber is unable to make sense of the number, I keep the original number.

**Comment by tschallacka** [comment]
I see, but I'd still prefer then that something other than null is returned, or exception thrown, pointing people to use isValidNumber() before attempting to retrieve data from something that cannot supply it.

Nulls are hard to check for, because you don't know where it comes from, why it came there, because it doesn't have any meaning. it could well be some bug in the code happened and returned null, whilst valid output also returns null. 

If the code comes to a "Null" return it should return a region code of "UNKNOWN" or "##", something that will clearly convey the message, we couldn't retrieve valid data from this method, this means you get a generic response, plural zz alpha. Then when you get a null you know something is wrong.

**Comment by giggsey** [comment]
I understand your view here, but it's not something I'm going to change.

Feel free to create an issue for libphonenumber. If they make a change to the API here, this port will get updated to match.

For now, closing.
