### ISSUE TITLE
Composer update issues

### ISSUE THREAD

**Issue by taiidani** [giggsey/libphonenumber-for-php#124]
When updating this library using Composer it has consistently failed to update properly.

The string we use in our JSON:
```
"giggsey/libphonenumber-for-php": "~7.0",
```

When performing a `composer install` the library appears to update, but instead of adding new code to `src/libphonenumber` it actually removes most of the code and places all the new code under `src/src/libphonenumber`. The presence of this redundant `src` folder in the directory tree makes the autoloader miss, and thus causes "Class 'libphonenumber\PhoneNumberUtil' not found" errors throughout our codebase after each deploy.

We have a number of other packages in our project, but this package seems to be the only one that breaks during each update. Completely deleting the package from `vendor` and reinstalling clean will solve the problem once, but the problem crops up again during the next `vacasa install`.

Have you seen this issue? Do you know if it's a problem with libphonenumber, Composer or perhaps a configuration miss on our side?

**Comment by giggsey** [comment]
I've never encountered that, both with this project, and many other projects I use.

I would suggest ensuring that your composer version is up to date, and if it still occurs, report it as a composer issue.

**Comment by giggsey** [comment]
Closing this, as it is likely a composer issue.

If it does turn out to be something with this project, we'll reopen this issue.

**Comment by taiidani** [comment]
Not a problem, we're still troubleshooting. It definitely looks like a problem with our Composer installation.
