### ISSUE TITLE
Too long French mobile number

### ISSUE THREAD

**Issue by sylfabre** [giggsey/libphonenumber-for-php#126]
I try with +336234567890 on https://libphonenumber.appspot.com/phonenumberparser?number=%2B336234567890 and I get invalid for International format output.

But using the following PHP code

```
$phone = '+336234567890';
$phoneObject = $phoneUtil->parse($phone, null);
echo $phoneUtil->format($phoneObject, \libphonenumber\PhoneNumberFormat::INTERNATIONAL);
// +33 6234567890
```
=> There is a space after international prefix

**Comment by sylfabre** [comment]
Sorry I misused `INTERNATIONAL` vs `E164`

**Comment by giggsey** [comment]
I'm glad you worked it out, but just a further note:

The `format()` function does not actually check whether the number is valid. Google's demo (and the [libphonenumber for php demo](https://giggsey.com/libphonenumber/)) check whether the number is valid before trying to format it.
