### ISSUE TITLE
Taking too much time on execution.

### ISSUE THREAD

**Issue by dheerajtiwari** [giggsey/libphonenumber-for-php#127]
When I am using this library to get number type in my code it is taking too much time.
I am using it in loop of 20k. To execute this much of loop it is taking upto 50 to 100 sec.

Is there any way so that i can pass more than one number to find it's type.

Here is my code.

```
$phoneUtil = PhoneNumberUtil::getInstance();
$numberPrototype = $phoneUtil->parse($number, $iso);
return $phoneUtil->getNumberType($numberPrototype);
```

Input field $number and $iso are coming in loop.

Thanks

**Comment by giggsey** [comment]
Hi,

It's still going to have to do the same amount of work if you pass one
number in at a time, or many different numbers.

It does do some things to improve performance a bit. It uses a singleton so
there is only one instance in memory. Once it loads each countries metadata
once.

The slow part here is the getNumberType, as it has to compare the number
against many different complex regular expressions to work out what number
type it is.

I'll run some bench marks a bit later, and see if I get a similar result.

**Comment by giggsey** [comment]
At 20,000 rows in 50 seconds, that gives 0.0025s per row.

On my local Windows setup (PHP 7), I've done ~30 example numbers, and my average is 0.0024s, so a similar result to you.

I'm not sure what to suggest, apart from the usual caching where possible or offload the work to workers.

**Comment by dheerajtiwari** [comment]
It was not taking this much of time before.
We are using this code since 2 years and suddenly since past 1 month it is taking to much of time.
Please suggest something.

**Comment by giggsey** [comment]
On a digitalocean droplet running the latest Ubuntu LTS with PHP7 (where the demo code runs):

(This parses a number, then gets the number type). It only does it on a small sample size, and I've only run it once)

| libphonenumber-for-php Version | Average |
|--------|----------|
| 7.6.0 | 0.0006 |
| 7.5.0 | 0.0008 |
| 7.4.1 | 0.0007 |
| 7.3.0 | 0.0006 |
| 7.2.1 | 0.0007 |
| 7.0    | 0.0007 |
| 6.0    | 0.0006 |

As you can see, the results here are pretty much the same.


What operating system/PHP version are you using? Do you have xdebug installed?

**Comment by giggsey** [comment]
@dheerajtiwari Any improvements on the latest release? Also, can you answer the questions from the end of my last comment.

**Comment by giggsey** [comment]
Closing due inactivity.

If you are still having issues, can you answer the questions in the previous comments and reopen.
