### ISSUE TITLE
"Missing or invalid default region" on correct number and region

### ISSUE THREAD

**Issue by uniaq** [giggsey/libphonenumber-for-php#128]
Demo works fine.

Region: PN
Number: +64286300988

**Comment by giggsey** [comment]
Hi,

It seems to work for me.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$phoneNumberUtil = \libphonenumber\PhoneNumberUtil::getInstance();

$phoneNumberObj = $phoneNumberUtil->parse('+64286300988', 'PN');

var_dump($phoneNumberUtil->isValidNumber($phoneNumberObj));

```

Output:

> bool(true)


Are you using the latest version?

**Comment by uniaq** [comment]
It was a "plus" sign, I didn't use it as prefix. Looks like some regions works well without it, and some regions are not.

Issue resolved, thanks for help.
