### ISSUE TITLE
Nigerian Phone Number Isn't a Valid Phone Number

### ISSUE THREAD

**Issue by tubiz** [giggsey/libphonenumber-for-php#129]
I tried to validate a new Nigerian phone number series but it wasn't validated as a valid phone.

Here is the phone number format 0907XXXXXXX.

It belongs to the Airtel network.

**Comment by giggsey** [comment]
Hi,

Please take a look at the section in the README about [Invalid Numbers](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers).

In this case, it appears that Google's libphonenumber is returning the same issue: [09071230000 in NG](https://libphonenumber.appspot.com/phonenumberparser?number=09071230000&country=NG).

**Comment by giggsey** [comment]
I'm closing this issue as Google's libphonenumber is returning the same result.

If you do believe this is an issue with this project, feel free to reopen.
