### ISSUE TITLE
PhoneNumberUtil::isViablePhoneNumber fails when called without first calling getInstance()

### ISSUE THREAD

**Issue by johnquintal** [giggsey/libphonenumber-for-php#135]
Hi Joshua,

Thanks so much for making this library available. 

I have found an issue though, pretty much as the title says, the following works:
```
$value = '+1245236347'; // some string that can be either a valid or invalid number
$phoneUtil = PhoneNumberUtil::getInstance();
return $phoneUtil::isViablePhoneNumber($value);
```
but this does not:
```
$value = '+1245236347'; // some string that can be either a valid or invalid number
return PhoneNumberUtil::isViablePhoneNumber($value);
```

The error returned is:

```
local.ERROR: exception 'ErrorException' with message 'preg_match(): Empty regular expression' in <path to project>/vendor/giggsey/libphonenumber-for-php/src/libphonenumber/PhoneNumberUtil.php:1218
```

It seems like the `isViablePhoneNumber()` static method should either be a class method or call `getInstance()` internally (of course, the former is preferred).

**Comment by giggsey** [comment]
Thanks for the report.

I can't change it from static to a class method as that would be a Backwards Incompatible change. Also, it would no longer mirror Google's libphonenumber.

However, this method errors because it's trying to load a regular expression which is loaded at startup of getInstance. This is because PHP can't set static class properties based on an expression. It can be worked around for in this function, but I want to go through and check all the other static methods.

I'll try to look at it over the next few days.

**Comment by johnquintal** [comment]
No problems. I understand the reasoning for not changing it. It should probably be documented though or have the method invoke the `getInstance()` method. 

I thought that might have been the case with the static properties. I have come up against the issue of static properties as expressions before as well. [Check out this SO answer to a similar question](http://stackoverflow.com/questions/10771502/php-define-static-array-of-objects#10771559). So, rather than creating a whole instance, you could just initialise the bits that you need. It depends on whether performance would suffer when calling `getInstance()` compared with using a single static accessor when using a static method as in the second example I gave. In fact, creating accessors for the static properties and calling all of them in `getInstance()` would be useful as well.

Anyhow, I hope that is helpful.

**Comment by giggsey** [comment]
Thanks again for reporting.

Once Google release a new version of libphonenumber (based on previous release history, should be within a few weeks), a new version will be released here.
