### ISSUE TITLE
Add a .gitattributes file

### ISSUE THREAD

**Issue by Indigo744** [giggsey/libphonenumber-for-php#139]
Hello,

Could you add a .gitattributes file in order to exclude Tests, build and doc folder?
So when using composer with --prefer-dist option, I only get the relevant source code?

Some reference:
 * http://stackoverflow.com/a/17069547
 * https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production

An example: https://github.com/PHP-DI/PHP-DI/blob/master/.gitattributes

Thanks a lot.

**Comment by giggsey** [comment]
I was going to mention that it already has a section in the composer.json to handle it for satis installs, but then found my reddit comment saying exactly that.

**Comment by Indigo744** [comment]
Also, if I may add another example...
https://github.com/giggsey/Locale/blob/master/.gitattributes

:yum:

**Comment by giggsey** [comment]
And that'll be where I remember doing it for :)

I'm just preparing it now.

**Comment by giggsey** [comment]
Thanks for reporting :+1:
