### ISSUE TITLE
Leading "00" for international number not recognized

### ISSUE THREAD

**Issue by tbindewald** [giggsey/libphonenumber-for-php#141]
An international number like +4916098765432 could also be written as 004916098765432. In the second case the library throws a NumberParseException because of "missing default region", but the region is defined by "0049" (=Germany).
Thank you for your nice work.

**Comment by giggsey** [comment]
00 is the International Dialling Prefix (IDD) for most countries, but not all.

Therefore, if you try parsing 0049... without specifying the region, it cannot be sure that you are looking at it from the point of view of a region that does have 00 as it's IDD.

Related issue on Google's parent project: https://github.com/googlei18n/libphonenumber/issues/382#issuecomment-65484198

**Comment by tbindewald** [comment]
I wasn't aware of that. Thank you.
