### ISSUE TITLE
Not validating New Numbers for India 

### ISSUE THREAD

**Issue by Jayad** [giggsey/libphonenumber-for-php#143]
https://giggsey.com/libphonenumber/index.php?phonenumber=8660447360&country=IN&language=&region=

https://giggsey.com/libphonenumber/index.php?phonenumber=7980122638&country=IN&language=&region=

These are new Numbers in India.
Even with the latest 7.7.3 version of the PHP API, we are Seeing these numbers as isValidNumber() 	false.
Kindly look into.

**Comment by giggsey** [comment]
I just tried the first number in [Google's demo](http://libphonenumber.appspot.com/phonenumberparser?number=8660447360&country=IN) and it gives the same result.

Please check the FAQ for reporting metadata issues: https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers


Closing.
