### ISSUE TITLE
Missing or invalid default region.

### ISSUE THREAD

**Issue by JamesTheHacker** [giggsey/libphonenumber-for-php#148]
How do you check if a number is a possible number without specifying a country code? For example, the following will not work and throws an exception:

```
$number = "077403392283";
$phoneNumberObject = $phoneNumberUtil->parse($input, null);
 if($phoneNumberUtil->isPossibleNumber($phoneNumberObject))
 {
     // Number is valid
 }
```

The error I get is: `Missing or invalid default region.`. All I need to do is check if a number is a possible number irrespective of its geo location.

Is that possible?

**Comment by giggsey** [comment]
The region code (if supplied) allows libphonenumber to narrow down which region a phone number belongs to. If it's not provided, then the only way it can tell the region is by being passed a full international number (in E164).

Have a look at https://github.com/giggsey/libphonenumber-for-php/issues/141 or https://github.com/googlei18n/libphonenumber/issues/382#issuecomment-65484198.

**Comment by JamesTheHacker** [comment]
I see. Thanks.
