### ISSUE TITLE
guess country when phone start with + and passed country=ZZ

### ISSUE THREAD

**Issue by muayyad-alsadi** [giggsey/libphonenumber-for-php#151]
> If Google's Online Demo gives a different result to the libphonenumber-for-php demo, then please raise an Issue here.

I'm trying to guess country from full international number stating with `+` as suggested [here](https://groups.google.com/forum/#!topic/libphonenumber-discuss/IqP4cC8udn0)

> If the number starts with a +, there are no problems - you can just parse it (with any region code, including "ZZ" which is the unknown region), and afterwards you can ask what the region code is.

the link I used is https://libphonenumber.appspot.com/phonenumberparser?number=%2B962775321073&country=ZZ&geocodingLocale=en-GB

the result is Jordan as expected

on the other hand your library does not handle this case

https://giggsey.com/libphonenumber/index.php?phonenumber=+962775321073&country=ZZ&language=en&region=GB

**Comment by muayyad-alsadi** [comment]
![screenshot from 2016-12-20 10-28-22](https://cloud.githubusercontent.com/assets/1312683/21343405/38af5fa6-c69f-11e6-97ec-7e3acb0b7992.png)

**Comment by giggsey** [comment]
You're not URL encoding the + on the link to the libphonenumber-for-php demo: https://giggsey.com/libphonenumber/index.php?phonenumber=%2B962775321073&country=ZZ&language=en&region=GB

**Comment by muayyad-alsadi** [comment]
thank you
