### ISSUE TITLE
Enhancement:  List phone carriers by region

### ISSUE THREAD

**Issue by NoMan2000** [giggsey/libphonenumber-for-php#155]
I'd like to be able to get a list of carriers all the carriers, and also get a filtered list of all carriers by region, without having to put in a phone number.  This is because even some numbers that are valid return null results when using PhoneNumberToCarrierMapper.

This is my code that mimics the functionality, but you can see some of the problems.  

- I have to go through the directory path, but you might change it in the future.  This is unstable.
- I can't order by continent or any other meaningful data.  There are 749 available carriers if you include everything and even with a search feature, that's too much slog.

Ideally there'd be two new methods.

- `getAllCarriers`, to expose all of the carriers for a location.
- `getCarrierByRegionCode`, to expose a list of carriers for a specific region. 

```php
    /**
     * @throws \Exception
     * @return array
     */
    public function getAllCarriers()
    {
        if (!empty(static::$carriers)) {
            return static::$carriers;
        }
        $directory = dirname(dirname(__DIR__)) . '/vendor/giggsey/libphonenumber-for-php/src/carrier/data';
        $directoryInfo = new SplFileInfo($directory);
        if (!$directoryInfo->isDir()) {
            throw new FileException("Unable to find the directory $directory");
        }
        $defaultList = ['AT&T', 'Verizon', 'Sprint', 'T-Mobile', 'Boost', 'Virgin', 'Cricket', 'Other'];
        $language = $this->getSessionManager()->getGlobal('language', 'en_US');
        $prefix = Locale::getPrimaryLanguage($language);
        $isValidDir = is_dir($directory . '/' . $prefix);
        if (!$isValidDir) {
            $prefix = 'en';
        }
        $directoryRecursiveIterator = new RecursiveDirectoryIterator($directory . '/' . $prefix);
        $iterator = new RecursiveIteratorIterator($directoryRecursiveIterator);
        $codeList = $defaultList;
        /**
         * @var $value SplFileInfo
         */
        foreach ($iterator as $key => $value) {

            $isFile = $value->isFile() && !$value->isDir();
            if ($isFile) {
                $codeList[] = include $value->getRealPath();
            }
        }
        $codeList = array_flatten($codeList);
        asort($codeList);
        $carriers = array_values(array_unique($codeList));
        static::$carriers = $carriers;
        return $carriers;
    }
```

**Comment by giggsey** [comment]
This port aims to keep API compatibility with Google's Java release. As a result, I'm not willing to add additional API methods that do not exist in their version.

However, I have knocked up some sample code that will get a full list of carriers:

```php
<?php

use libphonenumber\PhoneNumberToCarrierMapper;
use libphonenumber\prefixmapper\PhonePrefixMap;
use libphonenumber\prefixmapper\PrefixFileReader;

require __DIR__ . '/vendor/autoload.php';

$directory = PhoneNumberToCarrierMapper::MAPPING_DATA_DIRECTORY;
$baseLocation = dirname((new ReflectionClass(PhoneNumberToCarrierMapper::class))->getFileName());

$prefixFileReader = new PrefixFileReader($baseLocation . DIRECTORY_SEPARATOR . $directory);


$regions = \libphonenumber\PhoneNumberUtil::getInstance()->getSupportedRegions();

$carriers = [];

foreach ($regions as $region) {
    $code = \libphonenumber\PhoneNumberUtil::getInstance()->getCountryCodeForRegion($region);
    $result = $prefixFileReader->getPhonePrefixDescriptions($code, 'en', null, 'US');

    if ($result === null) {
        continue;
    }

    $property = new ReflectionProperty(PhonePrefixMap::class, 'phonePrefixMapStorage');
    $property->setAccessible(true);

    $carriers = array_unique(array_merge($carriers, array_values($property->getValue($result))));
}

sort($carriers);

var_dump($carriers);
```

The only real risk to BC is the usage of Reflection to access `PhonePrefixMap->phonePrefixMapStorage`.

However, you could continue using your method, and convert the hardcoded file path to use the `$directory` and `$baseLocation`.


A few things to watch out for:
 - libphonenumber only stores carriers for mobile numbers
 - It'll only display the range owner, so any number portability means you won't have the correct carrier
 - It only displays owners of number ranges, so there is a good change [MVNO's](https://en.wikipedia.org/wiki/Mobile_virtual_network_operator) won't be included (the data for the UK does not contain MVNO's as they don't own the numbers)

If you want to use this information without the risk of BC changes being introduced in the PHP, I would recommend parsing the data yourself, and storing it for future use. The base data is stored in simple text files, in a similar fashion to the PHP array: https://github.com/googlei18n/libphonenumber/blob/master/resources/carrier/en/1.txt

I'm going to close this issue, as it's not something that is going to be implemented natively into this port. However, I'm happy to continue discussing any alternatives.

**Comment by NoMan2000** [comment]
Thanks, that's pretty much what I was looking for.

**Comment by mohammeddawod** [comment]
It's wrong when you select one region like [CA] Canada
