### ISSUE TITLE
findNumbers implementation

### ISSUE THREAD

**Issue by jamesgraham** [giggsey/libphonenumber-for-php#161]
Are there any plans to implement this?

My use case is scanning some text for numbers.

**Comment by giggsey** [comment]
Hi, this isn't something that has been considered before. However, I can see that this could be useful for some.

I might be able to look at it something in the near future, but I'll happily accept pull requests for it.

**Comment by giggsey** [comment]
I made a start on this over the weekend, and I hope to have something pushed this week.

**Comment by giggsey** [comment]
Took a bit longer than planned, but it's now pushed to a branch (PR #164).

I'll probably leave it there until Google release 8.4 (currently on 8.3.3).

If you could give it a try (You can use `dev-phoneNumberMatcher` in your composer.json), that would be great.

**Comment by jamesgraham** [comment]
Thanks will update and report back any issues!
