### ISSUE TITLE
Spanish mobile numbers and NDC length

### ISSUE THREAD

**Issue by shuttertorture** [giggsey/libphonenumber-for-php#162]
Hi,

maybe we're just using the library the wrong way, anyway, there's a behaviour with Spanish mobile numbers that I don't understand.

Given the number +34 666999666 (which should be a valid Spanish mobile phone number), I'd expect getLengthOfNationalDestinationCode() to return zero, as there's no destination codes at all in Spanish telephone numbers as far as I know. Adding just one digit to  the number (+34 6669996669) does exactly that, length of the NDC is 0 now.

What am I doing wrong? Causes a bug in our phonenumber handling that is "hacky" to fix.

Thanks a lot!

**Comment by giggsey** [comment]
Do you have any sample code?

Or is it just something like:

```
<?php

require 'vendor/autoload.php';

$phoneNumberUtil = \libphonenumber\PhoneNumberUtil::getInstance();

$spanishNumber = $phoneNumberUtil->parse("+34 666999666", null);

$ndc = $phoneNumberUtil->getLengthOfNationalDestinationCode($spanishNumber);

var_dump($ndc);
```

Within the next hour, I'll give that try using Google's libphonenumber in Java.

**Comment by giggsey** [comment]
Looking at the documentation for the function, it seems that this is the desired behaviour?

     * Gets the length of the national destination code (NDC) from the PhoneNumber object passed in,
     * so that clients could use it to split a national significant number into NDC and subscriber
     * number. The NDC of a phone number is normally the first group of digit(s) right after the
     * country calling code when the number is formatted in the international format, if there is a
     * subscriber number part that follows. An example of how this could be used:

+34 666999666 in the international format is 	+34 666 99 96 66. The first group of digits after the country calling code is 666.

**Comment by shuttertorture** [comment]
Hi, thanks for the quick reply, it seems like it is our fault, we're mixing up area code and NDC. We need to split the phone number coming in as a pure string into country code, area code and number.

Our code looks like so:
`
$nationalSignificantNumber = $phoneUtil->getNationalSignificantNumber($phoneNumberObject);
                $nationalDestinationCodeLength = $phoneUtil->getLengthOfNationalDestinationCode($phoneNumberObject);
                if ($nationalDestinationCodeLength > 0) {
                    $areaCode = substr($nationalSignificantNumber, 0, $nationalDestinationCodeLength);
                    $nationalNumber = substr($nationalSignificantNumber, $nationalDestinationCodeLength);
                } else {
                    $areaCode = "";
                    $nationalNumber = $nationalSignificantNumber;
                }`

This leads to an area code being set and the number is cut by the first three digits.
But it seems like this is wrong, we probably need to use `getLengthOfGeographicalAreaCode()` then?

Thx!

**Comment by giggsey** [comment]
`getLengthOfGeographicalAreaCode()` won't help, as you're trying to lookup a mobile number. Mobile numbers in Spain don't have a geographical area.

This might be a better question for the [libphonenumber Mailing List](https://groups.google.com/forum/#!forum/libphonenumber-discuss). The fact you are using a PHP port shouldn't make a difference, as it should be the same API as the Java version.

**Comment by shuttertorture** [comment]
Alright, thanks for the link and your time, I guess this issue can be closed then. I have to read deeper into telephone number handling in general, I guess ;)

**Comment by giggsey** [comment]
Sorry I wasn't able to help further. This uses part of the library that I don't use, so I don't have a great deal of knowledge about it.

I'll close this issue for now. If you have any other issues, feel free to open a new issue.

Thanks
