### ISSUE TITLE
Missing Carrier Map for 8.8.3

### ISSUE THREAD

**Issue by ninjahza** [giggsey/libphonenumber-for-php#163]
Hi,

264 was added to Map.php but the en/264.php file is missing.

https://github.com/googlei18n/libphonenumber/blob/master/resources/carrier/en/264.txt

**Comment by giggsey** [comment]
Whoops, forgot to add that file into git on the last commit.

I'll release 8.8.3.1 once the tests pass.

Thanks for reporting.

**Comment by ninjahza** [comment]
All good, thanks for the lib!
