### ISSUE TITLE
Update Phone number from Vietnam

### ISSUE THREAD

**Issue by nguyenanhung** [giggsey/libphonenumber-for-php#165]
Pls update shortcode carrier phone number from vietnam telcos

https://github.com/giggsey/libphonenumber-for-php/blob/master/src/carrier/data/en/84.php

`return array (
  84120 => 'MobiFone',
  84121 => 'MobiFone',
  84122 => 'MobiFone',
  84123 => 'Vinaphone',
  84124 => 'Vinaphone',
  84125 => 'Vinaphone',
  84126 => 'MobiFone',
  84127 => 'Vinaphone',
  84128 => 'MobiFone',
  84129 => 'Vinaphone',
  84162 => 'Viettel Mobile',
  84163 => 'Viettel Mobile',
  84164 => 'Viettel Mobile',
  84165 => 'Viettel Mobile',
  84166 => 'Viettel Mobile',
  84167 => 'Viettel Mobile',
  84168 => 'Viettel Mobile',
  84169 => 'Viettel Mobile',
  84186 => 'Vietnamobile',
  84188 => 'Vietnamobile',
  84199 => 'G-Mobile',
  84868 => 'Viettel Mobile',
  84888 => 'Vinaphone',
  84898 => 'MobiFone',
  8490 => 'MobiFone',
  8491 => 'Vinaphone',
  8492 => 'Vietnamobile',
  8493 => 'MobiFone',
  8494 => 'Vinaphone',
  8495 => 'SFone',
  8496 => 'Viettel Mobile',
  8497 => 'Viettel Mobile',
  8498 => 'Viettel Mobile',
  84993 => 'G-Mobile',
  84994 => 'G-Mobile',
  84995 => 'G-Mobile',
  84996 => 'G-Mobile',
  84997 => 'G-Mobile'
);`

source: https://vi.wikipedia.org/wiki/M%C3%A3_%C4%91i%E1%BB%87n_tho%E1%BA%A1i_Vi%E1%BB%87t_Nam#.C4.90.E1.BA.A7u_s.E1.BB.91_.C4.91i.E1.BB.87n_tho.E1.BA.A1i_di_.C4.91.E1.BB.99ng

**Comment by giggsey** [comment]
Hi,

Please read the [README section about Invalid Numbers](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers).

If this PHP version is giving a result to Google's project, please re-open.

Closing.
