### ISSUE TITLE
Wrong country codes

### ISSUE THREAD

**Issue by BirknerAlex** [giggsey/libphonenumber-for-php#167]
Hello,

we are using this library and we seen wrong country codes.
This method is used: $phoneNumberUtil->getSupportedRegions();

Example: 

43 -> AT (Austria) is correct 
49 -> DE (Germany) is correct
33 -> Library returns ES (Spain) but it's FR France and Spain has 34

Library Output:
``` 
  30 => string 'NL' (length=2)
  31 => string 'BE' (length=2)
  32 => string 'FR' (length=2)
  33 => string 'ES' (length=2)
  34 => string 'HU' (length=2)
  35 => string 'IT' (length=2)
  36 => string 'VA' (length=2)
```

But it's weird. The Class https://github.com/giggsey/libphonenumber-for-php/blob/master/src/CountryCodeToRegionCodeMap.php has the correct numbers.

**Comment by giggsey** [comment]
It only returns a normal array, not as associative array. So the keys have no meaning.

It's just a coincidence that Austria and Germany are at the 'correct' array position, but that's all.

If you want to get the country code, there is the function `getCountryCodeForRegion`

**Comment by BirknerAlex** [comment]
Oh. I thought really it's a Number to Country mapping.

I've solved it now like this:
```
$numberCodes = [];
foreach (\libphonenumber\CountryCodeToRegionCodeMap::$countryCodeToRegionCodeMap as $number => $countries) {
    $numberCodes[$number] = $countries[0];
}
```

I our use case the first country for a code is enough to know.

Thanks!
