### ISSUE TITLE
Argentina national phone number on mobile is wrong

### ISSUE THREAD

**Issue by mikk150** [giggsey/libphonenumber-for-php#168]
When feeding into parser "+5491112345678" (E164) formatted phone number
and trying to parse it into NATIONAL format, it gives out "91112345678" which is wrong, because it should be "011 15 1234 5678" with trunk or "11 15 1234 5678" without trunk

9 is replaced with 15 after area code

**Comment by giggsey** [comment]
The demo is showing the correct value:

> National	011 15-1234-5678  

https://giggsey.com/libphonenumber/?phonenumber=%2B5491112345678&country=&language=&region=

Do you have some sample code?

**Comment by mikk150** [comment]
oh, I see now the issue... I was using PhoneNumber::getNationalNumber()

**Comment by giggsey** [comment]
Closing this issue.

Please open a new issue if you have any further questions.
