### ISSUE TITLE
Error $phoneUtil->parse('+447700900061', 'FR')

### ISSUE THREAD

**Issue by LeFredd** [giggsey/libphonenumber-for-php#169]
Hi my question is: Is the desired behavior or error?
```
$phoneUtil = PhoneNumberUtil::getInstance();
        try {
            $phoneNumber = $phoneUtil->parse('+447700900061', 'FR');
        } catch (NumberParseException $e) {
            return false;
        }

        return $phoneUtil->isValidNumber($phoneNumber);
```
This is a uk mobile phone send with ```+44```prefix, the countryCode is ```FR``` but the validation work.

If we replace ```+447700900061``` by ```07700 900061``` the validation fail.

**Comment by giggsey** [comment]
The second parameter to parse (country code) is the phone number region to assist with lookups.

If the number provided is already in an international format (Like the E164 number you have passed), then it can understand where the number is from. However, if you pass a local number (0770...), then it needs to use the region to check whether it's a French number.

**Comment by LeFredd** [comment]
Ok thanks, now I understand ;)

**Comment by giggsey** [comment]
https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberUtil.md#parse should also help
