### ISSUE TITLE
Valid number does not pass validation

### ISSUE THREAD

**Issue by geggleto** [giggsey/libphonenumber-for-php#181]
https://giggsey.com/libphonenumber/?phonenumber=416-111-2222&country=CA&language=&region=

416-111-2222 is a valid Canadian Number. 

http://www.markhamstorage.ca/

**Comment by giggsey** [comment]
Closing, as this number does not validate with Google's parent project too: https://libphonenumber.appspot.com/phonenumberparser?number=416-111-2222&country=CA

See: https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers

**Comment by HawkonDK** [comment]
try to change the number to something like **416-253-5451** Google's libphonenumber have filters there remove fake numbers like: 416-111-11111

**Comment by giggsey** [comment]
416-253-5451 gives the same results.

Valid on both

 - https://giggsey.com/libphonenumber/index.php?phonenumber=416-253-5451&country=CA&language=&region=
 - https://libphonenumber.appspot.com/phonenumberparser?number=416-253-5451&country=CA
