### ISSUE TITLE
PHP keyword static used as a new object

### ISSUE THREAD

**Issue by rocbar** [giggsey/libphonenumber-for-php#183]
My ide or Adobe CS5.5 Dreamweaver indicating the following line consists of an error: 
See package: /libphonenumber-for-php/src/PhoneNumberToCarrierMapper.php
Line 51 , “static::$instance[$mappingDir] = new static($mappingDir);”
Is that meant to be, or is it a bug?

**Comment by giggsey** [comment]
Late Static Binding (the new static) was added in PHP 5.3, so it should be
fine.

What version of PHP is your IDE code hinting for?

**Comment by rocbar** [comment]
PHP 5.6

**Comment by giggsey** [comment]
It should be fine. The unit tests cover that code, and those run on all PHP
versions from 5.3 upwards.

**Comment by rocbar** [comment]
When I tried running the sample code for 'Mapping Phone Numbers to carrier' from the site page: https://github.com/giggsey/libphonenumber-for-php I get a blank screen.  So, I wasn't sure if that was the problem.

**Comment by rocbar** [comment]
My PHP 5.6.13 is bundled with the pecl intl, do I still need to install php/pear extenion?

**Comment by giggsey** [comment]
Nope, if you are using the latest version, then the only extension that is
needed is mbstring.

Are you able to check your error logs, and get an error message?

**Comment by rocbar** [comment]
No error message from my test page: tel-num.php HTTP/1.1" 200
So far, all the other samples code worked.  I am assuming its the latest version V8.4.2 which is in the METADATA-VERSION.txt file.  And my PHP version does have the mbstring extension.

**Comment by giggsey** [comment]
Can you provide some example code?

**Comment by rocbar** [comment]
Package was installed using Composer
`	
	// get the autoload file
	$thisFile = str_replace('\\', '/', realpath(dirname(__DIR__))) . '/'; 
	$loadFiles = $thisFile .'plugins/libphonenumber-for-php-master/vendor/autoload.php';

	// check if autoloader file exist
	if(file_exists($loadFiles))
		require_once $loadFiles;

        class NumberFormat 
	{

		static public function mappingPhoneNumbersToCarrier($num, $cntry) 
		{
			// Note: The PECL intl and mbstring extension are required for the carrier mapper to be used.
			
			$phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
			$NumberProto = $phoneUtil->parse($num, $cntry);
			
			$carrierMapper = \libphonenumber\PhoneNumberToCarrierMapper::getInstance();
			
			// Outputs "Swisscom"
			echo $carrierMapper->getNameForNumber($NumberProto, "en");
		}
	}

   $showNum = NumberFormat::phoneNumberToCarrierMapper($num='+18768591023',$cntry='JM');
`

**Comment by giggsey** [comment]
> $loadFiles = $thisFile .'plugins/libphonenumber-for-php-master/vendor/autoload.php';

That looks a bit suspicious, but if it isn't causing an error, then it should be okay.

The problem is the number you are testing with: If you put that into the demo: https://giggsey.com/libphonenumber/?phonenumber=%2B18768591023&country=JM&language=&region= you'll see that it doesn't return any carrier information.

That's because libphonenumber doesn't have the carrier information for that number prefix for Jamaica.

Edit: https://github.com/googlei18n/libphonenumber/blob/master/resources/carrier/en/1.txt#L514 has data for that prefix. Interesting...

**Comment by giggsey** [comment]
Okay, found the problem.

The demo was still running 8.4.2. The carrier info for this number was added as part of 8.4.3. If you update to that version, you'll find it works.

**Comment by rocbar** [comment]
Okey, upgraded to v8.4.3 and the carrier info for country code JM is working for the number.  But still seeing a blank screen for carrier number starting with 407421 with Country code 'US'.  Off Topic: looking for a resource on how to use "As You Type Formatter" in an HTML5 form input with attr tel.

**Comment by giggsey** [comment]
Try the number on the demo: https://giggsey.com/libphonenumber/ and it'll show the carrier info if it has data.

As for a version of the As You Type Formatter to use in the browser, take a look at one of the JavaScript versions. That'll be better suited for it than using this PHP version.

**Comment by rocbar** [comment]
Thanks a lot for your help.  I started to explore JavaScript version
