### ISSUE TITLE
Assistance Needed

### ISSUE THREAD

**Issue by eaba** [giggsey/libphonenumber-for-php#184]
Hello,
How were you able to generate those phone numbers carrier prefixes?
I am a csharp developer and I have been searching the entire universe for something like that.

Will you be willing to share how you were able to do that?
 Thanks

**Comment by giggsey** [comment]
This library is a PHP port of Google's libphonenumber project. It's based on the Java version of their library, just converting it to PHP and making changes as appropriate.

**Comment by eaba** [comment]
Yes that i know.......but the prefixes, is it also a port of it?
I just want to know how that was achieved?

**Comment by giggsey** [comment]
Yes, all of it is a port.

How they are built are in the build directory. Google's data files for the prefixes are just text files in the format "prefix|text". A bit of string manipulation + looping, and they get moved into PHP arrays (quicker at runtime to read).

**Comment by eaba** [comment]
Okay.....thanks
