### ISSUE TITLE
Phone Country Code from Raw input

### ISSUE THREAD

**Issue by karborator** [giggsey/libphonenumber-for-php#186]
Is there a way to extract the country code from a raw input ?

raw input : +359888888888
country code "+359"

**Comment by giggsey** [comment]
If you look at the demo: https://giggsey.com/libphonenumber/?phonenumber=%2B359888888888&country=&language=&region=

You can extract the country code from the PhoneNumber object that is returned from the parse function.

**Comment by karborator** [comment]
Thank you 👍
