### ISSUE TITLE
How to get country name for all supplied phone numbers?

### ISSUE THREAD

**Issue by wojcikcp** [giggsey/libphonenumber-for-php#190]
According to docs: 

> The description returned **might** consist of the name of the country, **or** the name of the geographical area the phone number is from.

I have hundreds of records in DB and get results as explained above. I'd like to get only country names in all of them, is it possible?

**Comment by giggsey** [comment]
The library itself will return the highest accuracy it can.

Your best bet would be to get the country code of the phone number, and just another library (or a simple array) to translate that into a country name.

Pseudocode

```php

$countryList = [
   'GB' => 'United Kingdom',
   'NZ' => 'New Zealand',
   // etc...
];

$numberObj = $phoneNumberUtil->parse('+441174960123');

$region = $phoneNumberUtil->getRegionForNumber($numberObj);

echo $countryList[$region];
```

**Comment by wojcikcp** [comment]
That's great $ immediate solution. Thank you.
