### ISSUE TITLE
libphonenumber

### ISSUE THREAD

**Issue by amdxypf** [giggsey/libphonenumber-for-php#199]
Does libphonenumber support distinguishing between landlines and mobile phones?

**Comment by giggsey** [comment]
Yes,

Once you parse a phone number, you are able to get the number type, which
will tell you whether it's a mobile, landline (fixed-line) or another type.

Try putting some numbers into the demo. It'll show you the number types.

**Comment by amdxypf** [comment]
got it !
```
getNumberType() //output `MOBILE` or `FIXED_LINE`
```
thank you very much ๑乛◡乛๑~
