### ISSUE TITLE
Question : Which format/check you are using for validating US phone/mobile numbers

### ISSUE THREAD

**Issue by dbhattacharjee** [giggsey/libphonenumber-for-php#204]
Hi There,

We are using this bundle in our Symfony 2.x application from a long time and it worked for very well.
Recently, one of the customer reported that below numbers are not being recognized as valid US phone numbers.

**Example :** 8618601970643, 35796444692, 8613811212437,59169611818,555181404269, 440790375,
358440482158, 64210620096

We are curious to know what exact format/validation/checks you are using for validating US phone/mobile numbers.
Please do not consider this an issue, rather just a query.

**Comment by giggsey** [comment]
Hi,

I see that you've also opened an Issue on Google's libphonenumber project.

If their demo is returning the same as the demo for this PHP Port, do you
mind closing this issue, as the question will be best suited for them.

Thanks

**Comment by dbhattacharjee** [comment]
Hi @giggsey ,

Sure, I can close the issue.
As I have said during posting this, this is not an issue, rather question.

So, I am guess, you also don't have the concrete answer with you as well.

**Comment by giggsey** [comment]
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#where-do-we-get-information-from-to-determine-if-a-number-range-is-valid might help a bit.

For now, I'll close this issue, as it'll probably be answered by https://github.com/googlei18n/libphonenumber/issues/1939
