### ISSUE TITLE
unable to validate all the UK based numbers like +44 1632 960748, +44 1632 960484etc

### ISSUE THREAD

**Issue by monikamni** [giggsey/libphonenumber-for-php#211]

**Comment by giggsey** [comment]
01632 is a number range Ofcom have reserved for drama use, as a result
libphonenumber does not validate it as a valid (actively allocated) number.

See https://github.com/googlei18n/libphonenumber/issues/341 and the linked
issues there for discussion.

**Comment by monikamni** [comment]
Okay, Thank You
