### ISSUE TITLE
Validation Issue

### ISSUE THREAD

**Issue by ajoudeh** [giggsey/libphonenumber-for-php#212]
Dears, 
I get validation error for this phone number +962 (7) 82511335 its correct number??!!
and i update my current code version
![image](https://user-images.githubusercontent.com/1451200/33009348-424a339a-cddf-11e7-8de5-b0caef514f60.png)

Thanks,

**Comment by giggsey** [comment]
Hi, this number is validating on both the [libphonenumber-for-php demo](https://giggsey.com/libphonenumber/?phonenumber=%2B962+%287%29+82511335&country=&language=&region=), and Google's [libphonenumber demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B962+%287%29+82511335).

**Comment by ajoudeh** [comment]
i try it in both demo site. and it give me valid. and get the latest version of code. how i can fix it?

**Comment by giggsey** [comment]
If you are using the latest version, then it should be validating fine.

What version are you using, and do you have any example code?

**Comment by giggsey** [comment]
Wait, I just saw the screenshot.

Are you actually using libphonenumber-for-php, or a JavaScript version?

**Comment by ajoudeh** [comment]
libphonenumber-for-php

**Comment by spacetourist** [comment]
Works for me :)

**Comment by ajoudeh** [comment]
Code


![image](https://user-images.githubusercontent.com/1451200/33015103-3ca8a53a-cdf2-11e7-92a0-ce281254838f.png)


![image](https://user-images.githubusercontent.com/1451200/33015230-aabbcf98-cdf2-11e7-9003-e9521da07731.png)

**Comment by giggsey** [comment]
It looks like you're using https://github.com/Borales/yii2-phone-input

From the look of it, it should be using the latest version of libphonenumber-for-php. However, it also appears to it uses https://github.com/jackocnr/intl-tel-input for frontend validation. It could be that the JS package is out of date?
