### ISSUE TITLE
"country area code" from country code

### ISSUE THREAD

**Issue by Sarahphp1** [giggsey/libphonenumber-for-php#216]
Hi there
Is it possible to get the country phone code from the country three-letter or 2-letter codes?

For example, input 'GB' to get '44' ?

**Comment by grzegorztomasiak** [comment]
+1

**Comment by giggsey** [comment]
Off the top of my head, I'm not sure whether there is a function to do this. This project maintains API compatibility with Google's Java version of libphonenumber. So if they have a function to provide this functionality, then it should exist on this project too.

However, the link is stored in the metadata, so as a work around, you could get an example number by region, then extract the country code from that PhoneNumber object.

**Comment by Sarahphp1** [comment]
Awesome.
Thank you

**Comment by giggsey** [comment]
I'll leave this open as a reminder to update the documentation to add these additional functions.
