### ISSUE TITLE
Not able to process 0970.... numbers for the netherlands

### ISSUE THREAD

**Issue by rvleyden** [giggsey/libphonenumber-for-php#221]
When trying to parse 0970.... (+31970...) number for the netherlands there is an error returned. These numbers are mobile data only (machine 2 machine) numbers.

**Comment by giggsey** [comment]
Google does not support machine to machine numbers at this time, although they have open discussions about it.

https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers

**Comment by giggsey** [comment]
I'm closing this as this isn't an issue with this library.

If/When Google add support for M2M numbers, it'll get ported over to this version.
