### ISSUE TITLE
Validation of a valid FR mobile number is  failing

### ISSUE THREAD

**Issue by david-vde** [giggsey/libphonenumber-for-php#222]
Hello

Some customers reported us that they can not register to our application due to the fail of the validation of their mobile numbers.

It appears that every FR mobile phone numbers starting by 33632* and  nubmers starting by 337* fail the validation.

But these are valid phone numbers.

A fix for this bug would be appreciated :)

Thank you

**Comment by giggsey** [comment]
Hi,

Please take a look at the FAQ for Invalid numbers: https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers

**Comment by david-vde** [comment]
Ok didn't seen this.

it was a problem with the FR carriers I used the method PhoneNumberUtil::getNumberType() and it solved my problem.

Thank you
