### ISSUE TITLE
What is the best way to get all supported countries?

### ISSUE THREAD

**Issue by andrelopez** [giggsey/libphonenumber-for-php#227]
It would be great if we can get an array:

```
array(
 'code' => 'Country Name',
...
...
...
);
```

Thank you!

**Comment by giggsey** [comment]
There are functions called `getSupportedRegions()` and `getSupportedCallingCodes()` that return the regions and calling codes as arrays.

Those might help.

**Comment by andrelopez** [comment]
Thank you!
