### ISSUE TITLE
Valid number is returned as false in validation

### ISSUE THREAD

**Issue by ivok** [giggsey/libphonenumber-for-php#228]
My Api use this library for phone validation. It works well until this number was used - "+49 15698 547789"
This is a valid german number. In your demo page it is validated as true. In my code $utility->isValidNumber($number) returns false

```
        try {
            $number = $utility->parse($value, "");
        } catch (NumberParseException $e) {
            $this->error(self::MSG_PHONE_NUMBER);
            return false;
        }       
        if ( $utility->isValidNumber($number) === false) {
            $this->error(self::MSG_PHONE_NUMBER);
            return false;
        }
```

Am I missing something or there is a bug.

I am using "giggsey/libphonenumber-for-php": "6.3.1" version

**Comment by giggsey** [comment]
As an initial step, make sure you are using the latest version of the
library. 6.3.1 is very out of date.

**Comment by ivok** [comment]
I didnt check yet the dependencies. I will try to update it and will write again if problem persist

**Comment by ivok** [comment]
It works, Sory for issue opening
