### ISSUE TITLE
Phone number with double country code 

### ISSUE THREAD

**Issue by nratifainah** [giggsey/libphonenumber-for-php#239]
Not sure since this is not happen to all phone number.
Tried with valid phone number but shorter than usual phone number(10 digits, region ID).
When do formatting, phone  number become 6262xxxxxxxxx

**Comment by nratifainah** [comment]
And the phone number type is FIXED_LINE instead of MOBILE

**Comment by giggsey** [comment]
Do you get the same result when using [Google's demo](https://libphonenumber.appspot.com/) compared to using the [libphonenumber-for-php](https://giggsey.com/libphonenumber/) demo?

**Comment by nratifainah** [comment]
yes, got same result.
when I key in 62xxxxxxxxx, phone number type is FIXED_LINE and  phone number become 6262xxxxxxxxx.
But when I key in 0xxxxxxxxx, it returns correct format and type.

**Comment by giggsey** [comment]
I'm going to close this issue then, as it's not a problem with this library.

Take a look at [Google's FAQ for double country codes](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-wasnt-the-country-code-removed-when-parsing), which might answer your question.
