### ISSUE TITLE
Parsing prefix and number

### ISSUE THREAD

**Issue by boesing** [giggsey/libphonenumber-for-php#241]
Hey there,

I've got an ITU E.164 formatted number and want to extract either the `prefix` or the `number`. 
So, if I got the following number:

*ITU E.164:* `+49891234567`
*Prefix:* `089`
*Number:* `1234567`

Actually, the only way I see is, formatting it with: `PhoneNumberUtil::formatOutOfCountryCallingNumber`

```php
list($prefix, $number) = explode(' ', PhoneNumberUtil::getInstance()->formatOutOfCountryCallingNumber($number, 'DE'));
```

Is there any better way to parse these values?

**Comment by giggsey** [comment]
I don't believe there is an API method that provides this functionality. It might be worth asking on [Google's mailing list](https://groups.google.com/forum/#!forum/libphonenumber-discuss) for options.

Your example code won't work in all situations, for example:

```php
$phoneNumberObject = $phoneNumberUtil->parse('0117 496 0123', 'GB');

var_dump($phoneNumberUtil->formatOutOfCountryCallingNumber($phoneNumberObject, 'US'));
// string(19) "011 44 117 496 0123"
// This will result in $prefix = 011 and $number = 44 117 496 0123


var_dump($phoneNumberUtil->formatOutOfCountryCallingNumber($phoneNumberObject, 'GB'));
// string(13) "0117 496 0123"
// This will result in $prefix = 0117 and $number of 496 0123
```

**Comment by giggsey** [comment]
Closing issue as the question has been answered.

Please open a new issue if you have any further questions.
