### ISSUE TITLE
Parsing a DE number

### ISSUE THREAD

**Issue by likizbajke85** [giggsey/libphonenumber-for-php#243]
Hi,
i have the issue with  libphonenumber\PhoneNumberFormat::E164
when i try to give it DE number 49172293xxxx it returns 4949172293xxxx .
I have tried with lt with 8.9.3 lib but i still have same issue.
Thanks.

**Comment by likizbajke85** [comment]
Ok, thanks for quick answer.

**Comment by giggsey** [comment]
Closing issue as the question has been answered.

Please open a new issue if you have any further questions.
