### ISSUE TITLE
Mobile numbers without leading zero

### ISSUE THREAD

**Issue by seasoninthesky** [giggsey/libphonenumber-for-php#248]
Hi,

Why are mobile numbers without a leading zero valid? 

For example in The Netherlands and Germany. This is not usual.

```
****Parsing Result:****
{"country_code":31,"national_number":6390xxxxx,"raw_input":"6390xxxxx","country_code_source":20}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: NL
Result from getNumberType(): MOBILE
```

**Comment by giggsey** [comment]
The internal PhoneNumber object will store the national_number without any leading zeros.

When you format the phone number, this leading zero will get added back.

E.g. [+44 117 496 0000](https://giggsey.com/libphonenumber/?phonenumber=01174960000&country=GB&language=&region=)'s PhoneNumber object has a national_number of '1174960000', but when you format it to the national format, it comes out as '0117 496 0000'

**Comment by seasoninthesky** [comment]
Thanks for the answer

**Comment by giggsey** [comment]
That question might be better suited for [Google's mailing list](https://groups.google.com/group/libphonenumber-discuss).

**Comment by seasoninthesky** [comment]
Will do! :)
