### ISSUE TITLE
Daylight Savings Time Problems

### ISSUE THREAD

**Issue by jaybos** [giggsey/libphonenumber-for-php#252]
The time zone listed for a Phoenix phone number is "America/Denver"  however, Denver and Phoenix are in different time zones right now because Arizona does not adjust their clocks for Daylight Savings time, while Colorado does.   NOTE: Hawaii also does not observe daylight savings time and may have a similar issue.

Arizona numbers should use the "America/Phoenix" time zone name that you can find listed in many places:

https://docs.oracle.com/cd/B13866_04/webconf.904/b10877/timezone.htm
http://php.net/manual/en/timezones.america.php
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by giggsey** [comment]
Sorry, but this project does not make changes directly to the metadata. You'll need to report the problem to Google's libphonenumber project.

Please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for further details.
