### ISSUE TITLE
Doesn't work validation for Austrian phone numbers 

### ISSUE THREAD

**Issue by AlexanderCustom** [giggsey/libphonenumber-for-php#254]
I found this Austrian number not working: 436646595955. Because of metadata PhoneNumberMetadata_AT.php. Here are regexps but none is match to this number. And this phone numbers can't go through validation. I wanna offer to add something like this:
     .... => array(
    'NationalNumberPattern' => '43\\d{6,10}',
    'ExampleNumber' => '436646593945',
    'PossibleLength' => 
    array (
        0 => 8,
        1 => 9,
        2 => 10,
        3 => 11,
        4 => 12,
        5 => 13,
    ),
    'PossibleLengthLocalOnly' => 
    array (
    ),

Or rewrite some regexp for such numbers.

**Comment by giggsey** [comment]
Please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for metadata issues.
