### ISSUE TITLE
E.164 extensions

### ISSUE THREAD

**Issue by kiler129** [giggsey/libphonenumber-for-php#255]
Today I discovered that `\libphonenumber\PhoneNumberUtil::format()` doesn't handle extensions at all in case of E.164. I was used to see extensions in form of `phone;ext=123`, however the library doesn't do such thing.

Is this by design or do we have a bug here?

**Comment by giggsey** [comment]
See #152.

E164 shouldn't contain any extension information. This PHP project matches Google's implementation.

**Comment by kiler129** [comment]
@giggsey Yes... I just checked Google's Java implementation and indeed they do the same. I'm thinking if there's any ~~~sane~~~standard way to save extension along with extension?

**Comment by giggsey** [comment]
I'm not sure to be honest.

As you mentioned in misd-service-development/phone-number-bundle#183, serialisation could work, but that's quite a large storage increase over E164.

This might be better suited for [Google's mailing list](https://groups.google.com/forum/#!forum/libphonenumber-discuss) in case there is a general format to use for this situation.

**Comment by giggsey** [comment]
I'm going to close this issue, as it isn't a problem with this PHP port itself.

If Google update their API, this project will be updated to match.
