### ISSUE TITLE
Feature Request?

### ISSUE THREAD

**Issue by barrychapman** [giggsey/libphonenumber-for-php#256]
Is it possible to possibly pass an array `[item1, item2. ..]` to $defaultRegion as part of `PhoneNumberUtil::parse()`?

I was not sure of the circumstance if you were to - for example - have a place close to a border of two regions, and wanted to accept both regions as a default region? I know it kind of goes against the definition of a default, but you know what I mean.

**Comment by giggsey** [comment]
Sorry, but this project maintains API compatibility with Google's libphonenumber Java library.

As a result, we don't accept any feature requests here that would diverge from Google's API.
