### ISSUE TITLE
Request: Custom Format?

### ISSUE THREAD

**Issue by barrychapman** [giggsey/libphonenumber-for-php#257]
Is it possible to create a function with a series of built in 'templates' that allow for custom formatting of a phone number?

Take for example the US, you could have a few different formats that are normally accepted by both carriers and merchants:
- (313) 555-1212
- 248.555.1212
- +1 248 555 1212
- 248 555 1212

And so forth. Assume you parse a number like `2485551212` with `PhoneNumberUtil::parse()` and then pass that to a `PhoneNumberUtil::customFormat('plug-in-format-here', $phoneNumberObject)` so you can spit out whatever format you want/need?

We would like to be able to stick this in our database in a normalized format, and this would be an ideal way to do so. Thanks!

**Comment by giggsey** [comment]
Sorry, but this project maintains API compatibility with Google's libphonenumber Java library.

As a result, we don't accept any feature requests here that would diverge from Google's API.
