### ISSUE TITLE
Misleading PhoneNumberUtil Documentation

### ISSUE THREAD

**Issue by RolandBende** [giggsey/libphonenumber-for-php#259]
**In the PhoneNumberUtil Documentation:
https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberUtil.md

**Missing \libphonenumber\  in the Formatting section format() function calls

Wrong:
`var_dump($phoneNumberUtil->format($phoneNumberObject, PhoneNumberFormat::E164));
// string(13) "+441174960123"`

Correct:
`var_dump($phoneNumberUtil->format($phoneNumberObject, \libphonenumber\PhoneNumberFormat::E164));
// string(13) "+441174960123"`

**Comment by giggsey** [comment]
Good point.

However, all the examples on that page are also missing the namespace, with the exception of the initial PhoneNumberUtil::getInstance.

Options:
 - Fully qualified class names in all examples
 - use statements in each code example
 - use statements at the top of page example that initialises `$phoneNumberUtil`

Any preference?

**Comment by IMP-Roland** [comment]
use statements at the top of page example that initialises $phoneNumberUtil
