### ISSUE TITLE
Validations fails for these countries

### ISSUE THREAD

**Issue by Kreshnik** [giggsey/libphonenumber-for-php#260]
Hi,

First of all, nice work done!

There seem however to be some issue with the following preffixes;

```
+386 - Sllovenia
+377 - Monaco 
+383 - Kosovo
```

I am not able to validate numbers starting with these prefixes.

Thanks in advanced for any help.

**Comment by giggsey** [comment]
Please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for metadata issues.
