### ISSUE TITLE
PhoneNumberUtil::getNumberTypeHelper() does not recognise emergency numbers

### ISSUE THREAD

**Issue by mrextreme** [giggsey/libphonenumber-for-php#262]
It has a whole bunch of if() statements, but PhoneNumberType::EMERGENCY is missing, so emergency numbers are reported as unknown.

**Comment by mrextreme** [comment]
Yes, I use ShortNumberInfo::getInstance()->connectsToEmergencyNumber(), but it just caught my eye that this function returns with wrong info instead of doing this step before returning with UNKNOWN.

**Comment by giggsey** [comment]
Closing this as this functionality matches the Google implementation this project is a fork of.

If Google change their API, this project will be updated.
