### ISSUE TITLE
require a polyfill instead of extension?

### ISSUE THREAD

**Issue by garak** [giggsey/libphonenumber-for-php#263]
[Symfony polyfill](https://packagist.org/packages/symfony/polyfill-mbstring) could be required instead of native mbstring extension.
This could ease package installation.

**Comment by giggsey** [comment]
Good idea.

Of the top of my head, this project doesn't use any of the functions that the symfony polyfill don't provide.

Happy to accept Pull Requests :)

**Comment by garak** [comment]
Great! I'll provide a PR tomorrow
