### ISSUE TITLE
getNationalNumber() removes leading zero from italian numbers

### ISSUE THREAD

**Issue by sattes-faction** [giggsey/libphonenumber-for-php#267]
I might be on the wrong track, but shouldn't `getNationalNumber()` return also the leading zero for italian numbers? 

Providing the number `+390472276666` on the [demo page](https://giggsey.com/libphonenumber/index.php) trims the leading zero and returns "0" for `getNationalNumber()`.

**Comment by giggsey** [comment]
The PHP demo does exactly the same as [Google's demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B390472276666), so it's not an issue with this PHP version of libphonenumber.

As `isItalianLeadingZero` is true for this PhoneNumber object, it gets added back when formatted as required.
