### ISSUE TITLE
Method getNumberOfLeadingZeros() of class PhoneNumber error for Angola

### ISSUE THREAD

**Issue by BenLaMeule** [giggsey/libphonenumber-for-php#270]
Hello,

I use your library for a project : 
- version 8.9.9
- git reference 79a3ee64277b3c8f71dc379c7325155b945058d7

I noticed an issue on method PhoneNumber::getNumberOfLeadingZeros() for Angola, returning 1 instead of 0. Please find below code sample :

`$exampleNumber = PhoneNumberUtil::getInstance()->getExampleNumberForType('AO', PhoneNumberType::MOBILE);`
`var_dump($exampleNumber->getNumberOfLeadingZeros()); // returns 1`

However, in data/PhoneNumberMetadata_AO.php, 'leadingZeroPossible' is set to false.

Thanks

**Comment by giggsey** [comment]
The default of number of leading zeros is always 1. I'm not sure off the top of my head.

**Comment by korell** [comment]
Hello,
Here is the same issue for the spanish numbers.
As that page explains, there is never leading zero in a spanish phone number : https://en.wikipedia.org/wiki/Telephone_numbers_in_Spain.
But, as BenLaMeule reports, the method PhoneNumber::getNumberOfLeadingZeros() returns '1'.

Question : do you think that the result of that method reliable ?

Thanks for your work !
Matthieu

**Comment by sjoller** [comment]
> Here is the same issue for the spanish numbers.

That goes for Danish numbers too. `numberOfLeadingZeros()` === 1 and `hasNumberOfLeadingZeros()` === false. Fortunately I can use the latter to get around the former.

**Comment by korell** [comment]
Thanks Giggsey for your reply.
Yes it's not due to your lib and it was an observation to know if you already observed that behaviour.
I'll join the Google mailing list of that lib.
Best regards

**Comment by giggsey** [comment]
Closing as the question has been answered.

Please re-open if you have further related questions.
