### ISSUE TITLE
New Brazil phone number format not supported

### ISSUE THREAD

**Issue by benmac3** [giggsey/libphonenumber-for-php#275]
Example phone number: +5535988628004
This validates in for the Google library -  https://libphonenumber.appspot.com/phonenumberparser?number=%2B5535988628006
But does not validate in this library - https://giggsey.com/libphonenumber/?phonenumber=%2B5535988628006&country=&language=&region=

Nice documentation BTW!

**Comment by giggsey** [comment]
Apologies, the demo was running 8.9.7. I've just updated it to 8.9.11 and the number now shows as valid.
