### ISSUE TITLE
Valid German number is still not suportted

### ISSUE THREAD

**Issue by Pumu** [giggsey/libphonenumber-for-php#285]
Hi all, 
I have an issue related with a valid German number "004983779294906600", i checked in demo online page and google support (libphonenumber.appspot.com) and in both sandbox the number validation failed.
You can check in these urls
https://giggsey.com/libphonenumber/?phonenumber=%2B49+837+79294906600&country=&language=&region=
https://libphonenumber.appspot.com/phonenumberparser?number=4983779294906600&country=DE

But I'm totally sure that the number is valid, I use a web to know if a international number is valid or not and here you can see https://www.numberingplans.com/?page=analysis&sub=phonenr that the number is a geographic number from Germany located in Unterthingau

Are there anyone here with the same issue??

Thanks in advance.

**Comment by giggsey** [comment]
Please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for metadata issues.
