### ISSUE TITLE
international to international translation drops 1 digit

### ISSUE THREAD

**Issue by syco** [giggsey/libphonenumber-for-php#292]
Hello,
I'm doing some tests with this script:
```php
#!/usr/bin/php
<?php
require_once __DIR__ . '/vendor/autoload.php';
$phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
$ddi = $argv[1];
$e164ddi = $phoneUtil->format($phoneUtil->parse($ddi, "IE"), \libphonenumber\PhoneNumberFormat::E164);
echo "$ddi\n";
echo " $e164ddi\n";
```
but with this number I get an unexpected result:
```bash
$ php test.php +788030503103
+788030503103
 +78030503103
```
shouldn't it return the number unchanged?

**Comment by giggsey** [comment]
I'm not sure without looking into number plans for Russia.

However, Google's demo returns the same as the PHP version, so it's not a problem with this library directly: http://libphonenumber.appspot.com/phonenumberparser?number=%2B788030503103

**Comment by giggsey** [comment]
I'm going to close an issue as it's not an issue with the PHP version of libphonenumber.

If you feel it's a metadata problem with Google's libphonenumber, I recommend report an issue on their Issue Tracker.
