### ISSUE TITLE
Can't catch ParseNumberException

### ISSUE THREAD

**Issue by Efrain177** [giggsey/libphonenumber-for-php#294]
![captura de pantalla 2018-12-03 a la s 11 28 39](https://user-images.githubusercontent.com/32506049/49390668-2a2cdd00-f6ef-11e8-88e2-51515a172ecd.png)
Hello im doing the following block of code

```
try {
            $phone = PhoneNumber::make($phone);

        } catch (\libphonenumber\NumberParseException $exception) {
            $response['message'] = 'Invalid phone number';
            return $response;

        }

```
And the try catch is not catching the Exception, any ideas?

**Comment by giggsey** [comment]
I've just seen https://github.com/Propaganistas/Laravel-Phone/issues/97.

As you've opened the issue on the project directly, I'm going to close this one as it's a duplicate.
