### ISSUE TITLE
PhoneNumberUtil->isItalianLeadingZero()

### ISSUE THREAD

**Issue by tbindewald** [giggsey/libphonenumber-for-php#296]
Given the following Code for testing (not elegant :) ):

```
$phone = '079474381';
$region = 'CH';

$phoneNumberUtil = PhoneNumberUtil::getInstance();
$phoneNumber = new PhoneNumber();
$possible = '?';
$valid = '?';
try {
	$phoneNumber = $phoneNumberUtil->parse($phone, $region);
	$possible = ($phoneNumberUtil->isPossibleNumber($phoneNumber)===true) ? 'yes' : 'no';
	$valid = ($phoneNumberUtil->isValidNumber($phoneNumber)===true) ? 'yes' : 'no';
} catch (NumberParseException $e) {
	echo 'EXCEPTION: '.$e->getMessage().PHP_EOL.PHP_EOL;
}

echo 'Number         : '.$phone.PHP_EOL;
echo 'Region         : '.$region.PHP_EOL;
echo 'isPossibleNr   : '.$possible.PHP_EOL;
echo 'isValidNr      : '.$valid.PHP_EOL;
echo 'parsedNr       : '.'+'.$phoneNumber->getCountryCode().'.'.$phoneNumber->getNationalNumber() .PHP_EOL;
echo 'IT-leadingZero : '.($phoneNumber->isItalianLeadingZero()===true ? 'true' : 'false');

```

This will produce the following output:

```
Number         : 079474381
Region         : CH
isPossibleNr   : yes
isValidNr      : no
parsedNr       : +41.79474381
IT-leadingZero : true

```

isItalianLeadingZero() is expected to be false, if the library already knows, it's NOT an italian number (here: CH = switzerland).

This value also leads to isPossibleNumber=true - which isn't because it's too short.

Then please exchange the $phone with '0794743819'.

This will produce the following output:

```
Number         : 0794743819
Region         : CH
isPossibleNr   : yes
isValidNr      : yes
parsedNr       : +41.794743819
IT-leadingZero : false
```

This is correct.

Possible solution:

Please check for (detected) countrycode === 39. Only then allow isItalianLeadingZero() to be true.

**Comment by giggsey** [comment]
Google's [demo](http://libphonenumber.appspot.com/phonenumberparser?number=079474381&country=CH) does the same thing for the invalid number.

The Italian Leading Zero isn't just used by Italy, so a simple check like this won't work: https://github.com/giggsey/libphonenumber-for-php/blob/master/src/PhoneNumber.php#L36

**Comment by tbindewald** [comment]
Do we know, which countries do have those leading Zeros?

if(!in_array($countrycode,[39,xx,xx,xx,....]) { ...}

It looks a little bit odd to see this attribute changing from true to false by just adding another digit at the end.

Maybe we have to dig deeper?

**Comment by giggsey** [comment]
I'm guessing because it's not a valid number, so it's detecting that the input number had a leading zero, and set the property on the PhoneNumber object. For the valid number, it was able to load the metadata for the region fully, which doesn't have the Italian leading zero.

The PHP is returning the same as Google's Java demo, so I'm wary of changing the PHP API that will introduce inconsistencies between the two versions.

**Comment by tbindewald** [comment]
I understand that. Thank you. So ... this issue should be reportet to Googles Project?

**Comment by giggsey** [comment]
Probably for the best. I suggest emailing the mailing list instead of creating an issue.

I'm going to close this issue, as it's not a problem with this library directly. Any future changes Google may make will be replicated for this PHP port.
