### ISSUE TITLE
Region Code from Raw Input

### ISSUE THREAD

**Issue by Tarcisiofl** [giggsey/libphonenumber-for-php#297]
Hello Everyone!

I already have got the country code from a raw input, but now I need to extract the region code.
Then, is it possible to get the region code as below?

`Raw Input: +359888888888       Country Code: "+359"   Region Code: "888"`

`Raw Input: +5534999999999     Country Code: "+55"     Region Code: "34"`

`Raw Input: +16462222222        Country Code: "+1"        Region Code: "646"`

I was thinking about to format it and get the information like a pattern, but I was unable to fin a pattern.

**Comment by giggsey** [comment]
There has been a similar question asked in #66 that may assist you.

**Comment by giggsey** [comment]
Are you happy for me to close this issue?

**Comment by Tarcisiofl** [comment]
Sure
