### ISSUE TITLE
Please update google metadata

### ISSUE THREAD

**Issue by shtumi** [giggsey/libphonenumber-for-php#308]
Phone numbers
+998781206514
+998781206515
are valid here:
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
but not in you library

**Comment by giggsey** [comment]
Out of interest, do you know what version of the library added support for these versions?

I'll be updating this version to https://github.com/googlei18n/libphonenumber/releases/tag/v8.10.8 today

**Comment by shtumi** [comment]
as 8.10.8 is latest version for today, so yes, it should be there.

**Comment by giggsey** [comment]
Will be fixed when #309 is merged + released
