### ISSUE TITLE
`isValidNumberForRegion()` returns `false` instead of `true` if the number is parsed `FROM_NUMBER_WITH_PLUS_SIGN`

### ISSUE THREAD

**Issue by Aerendir** [giggsey/libphonenumber-for-php#310]
I've tested my mobile Italian number using the [online demo](https://giggsey.com/libphonenumber/).

If I pass my number as `+393493176XXX` without specifying the region, then `isValidNumberForRegion()` returns `false`.

If I pass my number as `3493176XXX` but specifying the region `IT`, then `isValidNumberForRegion()` returns `true`.

Is this an intended behavior?

I've not investigated the issue at the moment, but in the meantime I'm informing you of the strange behavior to get more info about it.

**Comment by giggsey** [comment]
Is valid number for region checks based on the region that you are parsing
with. For the first example, this is empty, so the function can never
return true

**Comment by Aerendir** [comment]
@giggsey , but the region is the prefix `+39`, so the library should use it.

For this reason I'm saying it is a strange behavior: potentially, the library can derive the region...

**Comment by giggsey** [comment]
Could you confirm with a code sample what you mean?

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$util = \libphonenumber\PhoneNumberUtil::getInstance();

$number = $util->parse('+393493176000');

$isValid = $util->isValidNumberForRegion($number, 'IT');

var_dump($isValid); // true


$number = $util->parse('3493176000', 'IT');

$isValid = $util->isValidNumberForRegion($number, 'IT');

var_dump($isValid); // true

```

Both methods you describe return true for me?

**Comment by giggsey** [comment]
Are you happy for me to close this issue?

**Comment by Aerendir** [comment]
I will try ASAP... In the meantime, if you confirm it works, for me it is ok to close the issue.

Thank you for your time! :)
