### ISSUE TITLE
NG - Airtel phone number "09012140763" is invalid

### ISSUE THREAD

**Issue by luismflopes** [giggsey/libphonenumber-for-php#311]
Hi all,

I tested a real Nigerian Airtel phone number "09012140763" but the result is invalid.

Result from isValidNumber(): false

Used the available demo: https://libphonenumber.appspot.com/phonenumberparser?number=09012140763&country=NG

Can you check again Airtel phone numbers range?

Best Regards,
Luis Lopes

**Comment by giggsey** [comment]
If the number is being reported as invalid on Google's demo, then it'll also get reported as invalid for the PHP version.

See the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) on dealing with invalid numbers in this port.
