### ISSUE TITLE
Error validate number country VietNamese (VN)

### ISSUE THREAD

**Issue by tbdavid94** [giggsey/libphonenumber-for-php#317]
I use phone number is 0862049456 test but return false although it is active

Pls support for me. Thanks team
![Screenshot from 2019-05-16 09-32-30](https://user-images.githubusercontent.com/31137542/57822218-8e36ef80-77bd-11e9-99b3-9a2321102c94.png)

**Comment by giggsey** [comment]
Hi, the Google demo shows that this number is also invalid: https://libphonenumber.appspot.com/phonenumberparser?number=0862049456&country=VN

Please take a look at the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers).
