### ISSUE TITLE
Numbers not equal for germany

### ISSUE THREAD

**Issue by webmake** [giggsey/libphonenumber-for-php#318]
Hello,
here is example that gives result not as expected:
```
\libphonenumber\PhoneNumberUtil::getInstance()->parse('491234567890', 'DE')->equals(\libphonenumber\PhoneNumberUtil::getInstance()->parse('+491234567890', \libphonenumber\PhoneNumberUtil::UNKNOWN_REGION))
```
because of `nationalNumber` `491234567890` for first example
second is only `1234567890`

**Comment by giggsey** [comment]
This is because 49 is a valid national prefix in Germany.

https://giggsey.com/libphonenumber/?phonenumber=491234567890&country=DE&language=&region= is +49491234567890 in E164.

**Comment by webmake** [comment]
So why for lithuanian numbers and other countries it works?
```
\libphonenumber\PhoneNumberUtil::getInstance()->parse('37061234567', 'LT')->equals(\libphonenumber\PhoneNumberUtil::getInstance()->parse('+37061234567', \libphonenumber\PhoneNumberUtil::UNKNOWN_REGION))
```

**Comment by giggsey** [comment]
Because Germany has a valid prefix that starts with 49.

So the international number is +4949...

Google has a section on their FAQ regarding this: https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-wasnt-the-country-code-removed-when-parsing

**Comment by webmake** [comment]
Okay, I see now that two ways gives valid number for lithuania
```
\libphonenumber\PhoneNumberUtil::getInstance()->parse('61234567', 'LT')->equals(\libphonenumber\PhoneNumberUtil::getInstance()->parse('+37061234567', \libphonenumber\PhoneNumberUtil::UNKNOWN_REGION))
```
```
\libphonenumber\PhoneNumberUtil::getInstance()->parse('37061234567', 'LT')->equals(\libphonenumber\PhoneNumberUtil::getInstance()->parse('+37061234567', \libphonenumber\PhoneNumberUtil::UNKNOWN_REGION))
```,
but how then determine if number contains prefix or not in DE case?

**Comment by giggsey** [comment]
Are you happy for me to close this issue?

**Comment by webmake** [comment]
Yes sure, this is not this library issue, but googlei18n library limitations. Thank you
