### ISSUE TITLE
Validate UK mobiles including the channel islands

### ISSUE THREAD

**Issue by recci** [giggsey/libphonenumber-for-php#319]
I have come up with the following code to validate UK mobile numbers including the channel islands. 

Is this how it would be done?

```php       
             $this->regionCodes = array('GB', 'GG', 'JE', 'IM');
            $number = trim($phoneNumber);
                try {
                    $phoneNumberObject = $phoneUtil->parse($number, 'GB');
                }
                catch (\libphonenumber\NumberParseException $e) {

                    $this->phoneNumbers[] = array($number,'', self::INVALID);
                    $this->log($number.' '.$e);
                    error_log($e);
                    continue;
                }

                $regionCode = $phoneUtil->getRegionCodeForNumber($phoneNumberObject);
                $valid = false;

                if(in_array($regionCode, $this->regionCodes)){
                    $valid = $phoneUtil->isValidNumber($phoneNumberObject);
                }

                $type = $phoneUtil->getNumberType($phoneNumberObject);
                $carrier = '';
                $validMobile = self::INVALID;
                if ($valid && $type === 1) {
                    //if it is a valid mobile number but carrier is unknown
                    $carrier = ($carrierMapper->getNameForNumber($phoneNumberObject, 'en') === '' ? 'unknown': $carrierMapper->getNameForNumber($phoneNumberObject, 'en')) ;
                    $validMobile = self::VALID;
                }
```

**Comment by giggsey** [comment]
That looks okay, I have a few suggestions though:

 - You could probably replace the get region code with just a check for the country code on the object (44 instead of looking for GB, GG, JE etc.).
 - I'd use the actual PhoneNumberType constant instead of 1 (improves readability)
 - Rework the getNameForNumber function to use a temp variable, otherwise you'll be calling the function twice

**Comment by recci** [comment]
Thanks for getting back to me so quickly.  I am unsure how to use the PhoneNumberType constant in this situation. 
        
          $phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
        $carrierMapper = \libphonenumber\PhoneNumberToCarrierMapper::getInstance();
        $phoneNumberType = \libphonenumber\PhoneNumberType::MOBILE;

        foreach ($this->files as $file) {
            $phoneNumbers = file($file);
            foreach ($phoneNumbers as $phoneNumber) {
                $number = trim($phoneNumber);
                try {
                    $phoneNumberObject = $phoneUtil->parse($number, 'GB');
                }
                catch (\libphonenumber\NumberParseException $e) {

                    $this->phoneNumbers[] = array($number,'', self::INVALID);
                    $this->log($number.' '.$e);
                    error_log($e);
                    continue;
                }

                $regionCode = $phoneUtil->getRegionCodeForNumber($phoneNumberObject);
                $valid = false;

                if(in_array($regionCode, $this->regionCodes)){
                    $valid = $phoneUtil->isValidNumber($phoneNumberObject);
                }

                $type = $phoneUtil->getNumberType($phoneNumberObject);
                $carrier = '';
                $validMobile = self::INVALID;

                if ($valid && $type === $phoneNumberType) {
                    //if it is a valid mobile number but carrier is unknown
                    $carrier = ($carrierMapper->getNameForNumber($phoneNumberObject, 'en') === '' ? 'unknown': $carrierMapper->getNameForNumber($phoneNumberObject, 'en')) ;
                    $validMobile = self::VALID;
                }
                $this->phoneNumbers[] = array($number,$carrier, $validMobile);
                if($this->logResults){
                    $this->log($number.' carrier:'.$carrier.' status:'.$validMobile);
                }
            }
        }

**Comment by giggsey** [comment]
Yeah, that works fine.

You can also move the constant down directly to the if statement (no real difference for performance).

The carrier change will be a small performance win as well, as you're currently doing it twice for each successful carrier lookup.

```php
            if ($valid && $type ===  \libphonenumber\PhoneNumberType::MOBILE) {
                //if it is a valid mobile number but carrier is unknown
                $carrier = $carrierMapper->getNameForNumber($phoneNumberObject, 'en');

if ($carrier === '') {
    $carrier = 'unknown'
}

                $validMobile = self::VALID;
            }
```

**Comment by recci** [comment]
Yes, I see what you mean now. And you don't need to worry about checking GB, GG, JE etc because country code is 44 regardless. 

Thanks for you help!

**Comment by giggsey** [comment]
No worries.

I'm closing this issue now. Feel free to re-open if you have further questions.
