### ISSUE TITLE
Some Isle of Man mobile numbers triggers false negatives on validation

### ISSUE THREAD

**Issue by UlrikStreetPoulsen** [giggsey/libphonenumber-for-php#321]
Some Isle of Man numbers will trigger as false negatives when validated.

Number beginning with the below digits (provider in parenthesis) will trigger as invalid:

07624 50 (Bluewave Communications)
07624 56 (Sure)

These are in fact valid numbers. Source https://www.area-codes.org.uk/mobile/#076

Example of this being triggered as invalid:

https://giggsey.com/libphonenumber/?phonenumber=07624569700&country=IM&language=&region=

**Comment by giggsey** [comment]
Hi,

This number is reported as invalid by libphonenumber's project: https://libphonenumber.appspot.com/phonenumberparser?number=07624569700&country=IM

However, these two number ranges do appear to be allocated (Mid last year), so it's a bug with Google. You can do that from [here](https://issuetracker.google.com/issues/new?component=192347&title=Validation%20issue%20with%2007624569700%20(IM)&template=829703).

**Comment by UlrikStreetPoulsen** [comment]
Thanks. I  have submitted a bug ticket.

**Comment by giggsey** [comment]
Cool.

I'm going to close this issue as it's not a problem with this PHP port of the library. Once Google fix the bug and release a new version, this project will be updated.
