### ISSUE TITLE
Too long Polish TollFree number

### ISSUE THREAD

**Issue by ciarans** [giggsey/libphonenumber-for-php#322]
https://giggsey.com/libphonenumber/?phonenumber=%2B488004911826

This Phone number was from Twilio, but when it was parsed no data could be found on it and the error was thrown. Not sure if this a problem with the library.

**Comment by giggsey** [comment]
Hi,

Google's demo is returning the same thing: https://libphonenumber.appspot.com/phonenumberparser?number=%2B488004911826

Please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) regarding invalid numbers.
