### ISSUE TITLE
Kenyan Numbers not updated in this package

### ISSUE THREAD

**Issue by moses-nganga** [giggsey/libphonenumber-for-php#324]
There is a difference in some recent numbers when validated in this package. The google package demo returns the number as valid but this package demo return the number as invalid. How can i address that?
For example the number:
+254743123456

**Comment by giggsey** [comment]
Hi,

Can you try the demo again? I've just updated it from 8.10.13 to 8.10.14 (I often forget after doing a release)

**Comment by moses-nganga** [comment]
That was a quick reply, thank you. It still shows as invalid. below are the two results.
[](https://giggsey.com/libphonenumber/index.php?phonenumber=%2B254743234567&country=ke&language=&region=ke)
[](https://libphonenumber.appspot.com/phonenumberparser?number=%2B254743234567&country=KE)

**Comment by giggsey** [comment]
It shows as valid for me?

The only difference was isValidForRegion(), which was showing as false in your example URL because you had the country as lowercase instead of KE.

**Comment by moses-nganga** [comment]
You are absolutely right! Awesome stuff. Thank you. I'll update it in my app!
