### ISSUE TITLE
How Can I Compare Two Mobile Numbers Same Or Not

### ISSUE THREAD

**Issue by wifirevaithi** [giggsey/libphonenumber-for-php#332]
hi,

 I Need To Compare Two Numbers like (+911234567890) and (1234567890) it must return true and this is just example i need this feature for all country region

**Comment by giggsey** [comment]
There is a 'equals' function on the Phone Number object.

Example code:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$util = \libphonenumber\PhoneNumberUtil::getInstance();

$number = $util->parse('+911234567890');

$number2 = $util->parse('1234567890', 'IN');

$same = $number->equals($number2);

var_dump($same);
// bool(true)
```

**Comment by giggsey** [comment]
Closing issue as the question has been answered.

If you have any further questions, please open a new issue.
