### ISSUE TITLE
PhoneNumber::equals does not compare extension value

### ISSUE THREAD

**Issue by cyganm** [giggsey/libphonenumber-for-php#337]
`\libphonenumber\PhoneNumber::equals` method does not compare extension value at all. 
```
$sameExt = $this->hasExtension() == $other->hasExtension() &&
            (!$this->hasExtension() || $this->hasExtension() == $other->hasExtension());
```

should be
```
$sameExt = $this->hasExtension() == $other->hasExtension() &&
            (!$this->hasExtension() || $this->getExtension() == $other->getExtension());
```

**Comment by giggsey** [comment]
Good spot.

Are you able to submit a merge request with this fix, and a unit test to check.

If not, I'll try to get to it within a week or so (before Google's next release)

**Comment by cyganm** [comment]
@giggsey PR submitted

**Comment by giggsey** [comment]
Thank you!

It'll be part of the next release when Google do a release upstream.
