### ISSUE TITLE
Brazil phone with code 0055 does not work

### ISSUE THREAD

**Issue by Devdits** [giggsey/libphonenumber-for-php#341]
**Country**: Brazil (BR)
**Phone**: 005537988419236

00 prefix works fine with mexican phone numbers(0052), but not with brazilian.

Check it on https://libphonenumber.appspot.com/

## 005537988419236
![image](https://user-images.githubusercontent.com/8290411/66379358-f4ffb400-e9bd-11e9-9a1b-8f5728d1d481.png)
---
## +5537988419236
![image](https://user-images.githubusercontent.com/8290411/66379089-7a369900-e9bd-11e9-8612-bd63ebeaf91a.png)

**Comment by giggsey** [comment]
Trying a [GB number](https://giggsey.com/libphonenumber/?phonenumber=%2B441174960123&country=GB&language=&region=) and getting the out of country format from Brazil, it suggests there is no valid prefix.


I suggest asking this question to the Google Mailing list for the parent libphonenumber, as it's not a problem with the PHP port of the project.
