### ISSUE TITLE
Is there a reason why $nationalNumber isn't an integer ?

### ISSUE THREAD

**Issue by kelyak** [giggsey/libphonenumber-for-php#343]
Hi,

I looked through your documentation and couldn't find a reason why PhoneNumber $nationalNumber is a string instead of an integer like it seems to be in google's java version of the library.
When that variable isn't empty, can I assume that its content is an integer ?

Thanks,
Sincerely,
K.

By the way, thanks a lot for your awesome work on porting this library to php !

**Comment by giggsey** [comment]
That's a fair question.

It's due to a PHP issue, with the comment in PhoneNumberUtil:

```
         /*
         * We have to store the National Number as a string instead of a "long" as Google do
         *
         * Since PHP doesn't always support 64 bit INTs, this was a float, but that had issues
         * with long numbers.
         *
         * We have to remove the leading zeroes ourself though
         */
```

**Comment by kelyak** [comment]
Ooooh, ok I see. I didn't think I would find a comment about it that deep in the code. I should've looked a bit more for it.
I'll keep that in mind while dealing with that data.
Closing the issue, I got exactly the information that I needed.
Thanks a lot, and have a nice day ! :D
