### ISSUE TITLE
Update metadata for Albanian Numbers Metadata "PhoneNumberMetadata_AL.php"

### ISSUE THREAD

**Issue by ErmalKristo** [giggsey/libphonenumber-for-php#344]
Hi 

We are having a issue with validation of new range of numbers introduced by a Mobile Provider.
The numbers 0677XXXXXX are not being validated.

```
  'mobile' => 
  array (
    'NationalNumberPattern' => '6(?:[689][2-9]|7[2-6])\\d{6}',
    'ExampleNumber' => '662123456',
    'PossibleLength' => 
    array (
      0 => 9,
    ),
    'PossibleLengthLocalOnly' => 
    array (
    ),
  )
```
Regards

**Comment by giggsey** [comment]
Hi,

Can you check the FAQ for Invalid Numbers: https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers
