### ISSUE TITLE
get carrier with country code

### ISSUE THREAD

**Issue by parsibox** [giggsey/libphonenumber-for-php#346]
hi
how can i get list off carrier name for a country code?
for example carrier of IR

**Comment by giggsey** [comment]
Sorry, I don't believe there is a method to do that.

I don't recommend it, but you could just include the raw data file directly. It returns an array of prefixes to carriers. It's unlikely that this file path/format will change between minor versions, but it could happen.

**Comment by parsibox** [comment]
i do this but for some country ther is no file in data folder
this error for Argentina
vendor/giggsey/libphonenumber-for-php/src/carrier/data/en/54.php
![image](https://user-images.githubusercontent.com/12513476/68541637-26054700-03b7-11ea-88b2-0854e0688cf0.png)

any suggestion?

**Comment by giggsey** [comment]
Not all countries will have this metadata.

Additionally, the metadata that exists is only for mobile networks, not all carriers.

**Comment by giggsey** [comment]
I'm closing this issue as the initial question has been answered.

If you have any further questions, please open another ticket.
