### ISSUE TITLE
[regression] French phone number not valid using 8.11.1

### ISSUE THREAD

**Issue by williamdes** [giggsey/libphonenumber-for-php#352]
Since you published a patch it should not break parsing ?

```php
phone('+33 (0)4 06 21 24 41', 'FR')->formatE164()
```
```
Propaganistas/LaravelPhone/Exceptions/NumberParseException with message 'Number does not match the provided country.'
```

I am french and `+33 (0)4 06 21 24 41` seems to be a valid number and should not throw `'Number does not match the provided country.'`

**Comment by giggsey** [comment]
Hi,

This number is now showing as invalid on Google's libphonenumber demo: https://libphonenumber.appspot.com/phonenumberparser?number=%2B33+%280%294+06+21+24+41&country=FR

Please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for invalid numbers.

**Comment by williamdes** [comment]
@giggsey I will need to open an issue on the php Faker repository

**Comment by williamdes** [comment]
Thank you for the quick response
