### ISSUE TITLE
Issue in validating french mobile numbers

### ISSUE THREAD

**Issue by soufiane-jhioui** [giggsey/libphonenumber-for-php#354]
Hello Everybody,
The library doesn't validate french mobile numbers starting with 0715xxxxxx
Example :
In France the number 07159612xx is a valid number but the library does not recognize it.

It's a really urgent matter, thanks for your help

**Comment by giggsey** [comment]
Hi, https://libphonenumber.appspot.com/phonenumberparser?number=0715961200&country=FR is showing an invalid.

Please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) regarding invalid numbers.

**Comment by KevinBon** [comment]
> 
> Example :

> 07159612

Thes prefix [0715 is not valid](https://www.arcep.fr/demarches-et-services/professionnels/base-numerotation.html?tx_arcepbasetechnique_basetechnique%5B__referrer%5D%5B%40extension%5D=ArcepBasetechnique&tx_arcepbasetechnique_basetechnique%5B__referrer%5D%5B%40vendor%5D=GAYA&tx_arcepbasetechnique_basetechnique%5B__referrer%5D%5B%40controller%5D=BaseTechnique&tx_arcepbasetechnique_basetechnique%5B__referrer%5D%5B%40action%5D=search&tx_arcepbasetechnique_basetechnique%5B__referrer%5D%5Barguments%5D=YTowOnt93f79ac872f3e891e3d121304494af15ceeb744e4&tx_arcepbasetechnique_basetechnique%5B__referrer%5D%5B%40request%5D=a%3A4%3A%7Bs%3A10%3A%22%40extension%22%3Bs%3A18%3A%22ArcepBasetechnique%22%3Bs%3A11%3A%22%40controller%22%3Bs%3A13%3A%22BaseTechnique%22%3Bs%3A7%3A%22%40action%22%3Bs%3A6%3A%22search%22%3Bs%3A7%3A%22%40vendor%22%3Bs%3A4%3A%22GAYA%22%3B%7Da2bf59f355c30621a92ab741b949e14e74a32abc&tx_arcepbasetechnique_basetechnique%5B__trustedProperties%5D=a%3A1%3A%7Bs%3A6%3A%22search%22%3Ba%3A1%3A%7Bs%3A7%3A%22numeros%22%3Bi%3A1%3B%7D%7D6c5a73b9b235b8db1e19b0bafed7ac83147025d4&tx_arcepbasetechnique_basetechnique%5Bsearch%5D%5Bnumeros%5D=0715#c981)

You can have an overview of the ones working on [wikipedia](https://fr.wikipedia.org/wiki/Liste_des_pr%C3%A9fixes_des_op%C3%A9rateurs_de_t%C3%A9l%C3%A9phonie_mobile_en_France) or on [the Arcep simulator](https://www.arcep.fr/demarches-et-services/professionnels/base-numerotation.html).

**Comment by SJhioui** [comment]
Thank you for your reply. 
This ticket can be closed
