### ISSUE TITLE
Add support for Dutch data only phone numbers (12 digits )

### ISSUE THREAD

**Issue by LauLaman** [giggsey/libphonenumber-for-php#355]
First of Thanks for this package i've been using it for years now and really love it.

Here in the Netherlands more than 90% of the 60M mobile numbers (06) are in use thats why we have a special range for data-only devices. This new number is a 12 digit number and starts with 079 (including leading zero)

**National:** 097123456789
**International:** +3197123456789

**Formatted National:** 097 12 34 56 789
**Formatted International:** +31 (0)97 12 34 56 789

This new range is used for:
- Machine to Machine (M2M)
Independent working devices that communicate with each other automatically. Examples: smart energy meters, navigation systems, mobile internet dongles on laptops, e-readers and blood pressure meters.

- Machine to Human (M2H)
Independent working devices. Examples: security or alarm systems that call the security company, cars that call the emergency number after a collision.

- Human to Machine (H2M)
Independent working devices that someone sets remotely. Examples: security cameras and thermostats.

- Human to Human (H2H)
Connections where people choose a programmed number to communicate with others at the touch of a button. Examples: telephones in elevators for automatic connection to an emergency service, tablets that only send text messages, apps and emails.

More information can be found at the website of the ACM (**A**uthority for **C**onsumers and **M**arkets):
- [Incorrect use of dedicated mobile-phone codes should stop](https://www.acm.nl/en/publications/publication/14815/Incorrect-use-of-dedicated-mobile-phone-codes-should-stop)
- [Information about Dutch 097-numbers for non-Dutch providers](https://www.acm.nl/en/publications/information-about-dutch-097-numbers-non-dutch-providers)
- [06- en 097-nummers voor spraak en data - 🇳🇱](https://www.acm.nl/nl/onderwerpen/telecommunicatie/telefoonnummers/telefoonnummers-gebruiken/06--en-097-nummers-voor-spraak-en-data)

**Comment by giggsey** [comment]
Hi, please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) regarding invalid numbers.

Additionally, Google have a section in their FAQ about [M2M numbers](https://github.com/google/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers)

**Comment by LauLaman** [comment]
Hi @giggsey Thanks my bad. ive created a ticket at google.

There Reply:
> Hi,
> 
> Thanks for providing all the necessary details. This is duplicate of https://issuetracker.google.com/issues/74493346 
> We accept this issue.
> 
> We are presently in between of bulk updates to existing metadata.
> So planned to support M2M ranges by end of Q2, with a chance of getting extended to Q3.
