### ISSUE TITLE
PhoneNumberUtil::isPossibleNumber without region results in Runtime TypeError

### ISSUE THREAD

**Issue by gregor-tb** [giggsey/libphonenumber-for-php#360]
```
    public function isPossibleNumber($number, $regionDialingFrom = null)
    {
        if ($regionDialingFrom !== null && is_string($number)) {
            try {
                return $this->isPossibleNumber($this->parse($number, $regionDialingFrom));
            } catch (NumberParseException $e) {
                return false;
            }
        } else {
            $result = $this->isPossibleNumberWithReason($number);
            return $result === ValidationResult::IS_POSSIBLE
                || $result === ValidationResult::IS_POSSIBLE_LOCAL_ONLY;
        }
    }
```

Calling this seems not supported:
> \libphonenumber\PhoneNumberUtil::getInstance()->isPossibleNumber('+123467', null)

But instead of throwing an InvalidArgumentException or handle it (return null or so), it tries to enter _$this->isPossibleNumberWithReason($number)_. That results in a TypeError, because it does not accept strings.

**Comment by giggsey** [comment]
Good spot.

Looking at the doc block for that, it says:

```
     * Note: There are two ways to call this method.
     *
     * isPossibleNumber(PhoneNumber $numberObject)
     * isPossibleNumber(string '+441174960126', string 'GB')
```
This matches the Java API, which only accepts those two calls. As PHP doesn't support method overloading, I've done my best to merge the two functions together.

I can modify it to throw a BadArgumentException if you try to pass in (string, null).

**Comment by giggsey** [comment]
I didn't actually need to throw an exception, as you can just pass null as the region to `parse()`, and it'll try to understand it.

So the region is now optional when passing a string phone number.

This bug fix will get released when Google release their next version of the metadata (probably within two weeks).

Thanks for reporting.
