### ISSUE TITLE
Attempted to call function "mb_strcut" from namespace "libphonenumber"

### ISSUE THREAD

**Issue by nisiah78** [giggsey/libphonenumber-for-php#365]
Hi Guys,
i am stucked with this issue in my project.
i always have this issue with symfony 2.8, it is already an installed project that i have clonned from private repos on github. 
i have mb_string extension installed correctly that i can see from my php enabled extension.
i use php 7.1 7.2 and 7.3 with debian 10.

any helps are the welcome.

**Comment by giggsey** [comment]
Are you sure you have the mbstring extension enabled?

Does `extension_loaded('mbstring')` return true?

**Comment by nisiah78** [comment]
oups, i didn t pay attention to that, yes it returns false.
thank you sir.
let me enable and see if everything is fine
