### ISSUE TITLE
Regression on PhoneUtil::getNumberType

### ISSUE THREAD

**Issue by vincentchalamon** [giggsey/libphonenumber-for-php#376]
A regression seems to have been introduced in version 8.10.1, causing tests to fail on `misd-service-development/phone-number-bundle`. The regression part concerned is `PhoneUtil::getNumberType`.

Test case: https://github.com/misd-service-development/phone-number-bundle/blob/6503084e853ee9ea1479a698e8efea8d03b85fe0/Tests/Validator/Constraints/PhoneNumberValidatorTest.php#L140

Using version up to 8.10.0, this test is passing, but starting from version 8.10.1, it's failing...

**Comment by giggsey** [comment]
This is the problem of using real data in tests (I'm guilty of it here too). The real world changes, but the tests don't.

0843 123 4567 is now counted as a Premium Rate Number by [libphonenumber](https://libphonenumber.appspot.com/phonenumberparser?number=448431234567&country=GB)

**Comment by vincentchalamon** [comment]
Using https://github.com/odolbeau/phone-number-bundle now, cause https://github.com/misd-service-development/phone-number-bundle/ is not maintained anymore.

Thanks for feedback
