### ISSUE TITLE
Denmark phone number error

### ISSUE THREAD

**Issue by matheasrex** [giggsey/libphonenumber-for-php#378]
Hi!

I have a phone number from denmark: +45 20 999*** (3 digits for 3 * but you Know, GDPR:) )
And I receive a false for isValidNumberForRegion check.

That's why my user cannot validate herself. Although the client validation (by google) passes.

Could you help me with this issue?

**Comment by giggsey** [comment]
Did you pass in the region 'DK' to isValidNumberForRegion?

It seems to work for me:
![image](https://user-images.githubusercontent.com/305730/80083350-6e6f8600-854d-11ea-9e30-1137c87e5355.png)

**Comment by matheasrex** [comment]
Oh, you're right. I made the mistake. Sorry.
