### ISSUE TITLE
isMobileNumberPortableForRegion French not match

### ISSUE THREAD

**Issue by davaxi** [giggsey/libphonenumber-for-php#380]
Hi, 

I try to used PhonNumberUtil but result of test no match reality:

```php
function isValidFrenchMobile($phoneNumber) 
{
    $phoneUtil = PhoneNumberUtil::getInstance();
    try {
        $frenchNumber = $phoneUtil->parse($value, 'FR');
        $result = $phoneUtil->isValidNumberForRegion($frenchNumber, 'FR');
        return $result && $phoneUtil->isMobileNumberPortableRegion('FR');
    } catch (NumberParseException $e) { return false; }
}

var_dump(isValidFrenchMobile('0102030405')); // true but expected false

```
Mobile french number only start with 06 and 07, why this number match ?

**Comment by giggsey** [comment]
You're not actually checking the number type for the `$frenchNumber`

For that, you want `$phoneUtil->getNumberFormat($frenchNumber) === PhoneNumberType::MOBILE`

**Comment by davaxi** [comment]
I try your code but, method `getNumberFormat` not exist for class `PhoneNumberUtile` it's on `PhoneMetadata` and this method expected index. I dump data and all keys for "mobile" notion has true...

**Comment by giggsey** [comment]
Sorry, was trying from memory.

Try getNumberType

**Comment by davaxi** [comment]
Thanks. Documentation not explain :) For others, work code : 

```php

<?php

require __DIR__ . '/vendor/autoload.php';

function isValidFrenchMobile($phoneNumber)
{
    $phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
    try {
        $frenchNumber = $phoneUtil->parse($phoneNumber, 'FR');
        $result = $phoneUtil->isValidNumberForRegion($frenchNumber, 'FR');
        return $result && $phoneUtil->getNumberType($frenchNumber) === \libphonenumber\PhoneNumberType::MOBILE;
    } catch (\libphonenumber\NumberParseException $e) { return false; }
}

```

**Comment by giggsey** [comment]
Can I ask for clarification about the docs.

Were you looking at
https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberUtil.md
?

**Comment by davaxi** [comment]
Sorry, I had not seen this page.
Thanks for your help.
