### ISSUE TITLE
Issue with Belgium validation

### ISSUE THREAD

**Issue by dunebaud** [giggsey/libphonenumber-for-php#381]
getExampleNumberForType("BE")->getCountryCode() return "1", it should be "32"
getExampleNumberForType("BE")->getNationalNumber() return "2015550123", it should be "712455592"

I just started to use this library, maybe I missed something

**Comment by giggsey** [comment]
Yup, I believe that's a bug.

Java supports method overloading (PHP doesn't), and this function tried to merge both setups.

**Comment by giggsey** [comment]
For now, it'll work if you supply both params

**Comment by giggsey** [comment]
Ahh, I see half of the problem.

The PHP doc says:
>     * If $regionCodeOrType is the only parameter supplied, then a valid number for the specified number type
>     * will be returned that may belong to any country.

So if you want to use getExampleNumberForType, it's either `(type)` or `(region, type)`.

If you want an example number for a region, use `getExampleNumber(region)`

**Comment by dunebaud** [comment]
Sorry, my mistake... everything is fine now.
