### ISSUE TITLE
Get regex to use elsewhere

### ISSUE THREAD

**Issue by jpswade** [giggsey/libphonenumber-for-php#394]
It'd be really nice if there was some kind of interface that you could use to get the phone number regex so you could use that within HTML5 regex so the two could be consistent.

See: http://html5pattern.com/Phones

**Comment by giggsey** [comment]
I would recommend grabbing a JavaScript version of libphonenumber in order to do frontend validation.

**Comment by jpswade** [comment]
That’s how you get inconsistencies...

**Comment by giggsey** [comment]
There are multiple JS ports of libphonenumber, and like this PHP port, they
release as close to Google as possible.

There are functions within the library to get the regex, although I'm not
sure they are public. But then you need to decide which ones to use. Each
region will have a general regex, then more detailed ones for the different
number formats.

You'd then need to deal with the user typing the number in different
formats. For example, I may type a UK number as 0117 496 0123 or
+441174960123 or even just 1174960123. All three of read by the library as
the correct number.

**Comment by jpswade** [comment]
I'm really only interested in one region for general purposes, which is why pulling in large javascript packages of hundreds of megabytes seems a bit overkill, while, if it could be pulled from this library, in theory, it should evaluate to a few bytes. 

Google's libphonenumber supports javascript out of the box and is 1.2kb when minified and gzipped so this might just do the trick.
