### ISSUE TITLE
How to store phone number in database?

### ISSUE THREAD

**Issue by szepeviktor** [giggsey/libphonenumber-for-php#397]
How to store phone numbers in SQL db?

- 2 fields: country code + national number
- 1 field: international format
- otherwise

Please advise.

Please consider adding the answer to the README.
Thank you.

**Comment by szepeviktor** [comment]
If I store it in one field in international format how to determine the country? Country code could be 1, 2 or 3 digits.

**Comment by giggsey** [comment]
Personally, I store phone numbers as strings in E164. Formatting & processing is done in the application layer.

But it depends on your application and use case, and it's not really a question I can answer for you.

**Comment by BoilerTom90** [comment]
here's what we've done:

- we have a country table that stores the countries calling code and the 2
character region code.
- we have a number table that stores the number w/out the country code, and
we use a foreign key constraint to the country table.




*~~~~~~~~~~~~~~~~~~~*
*Tom Hoffman*

**Comment by szepeviktor** [comment]
Thank you!
