### ISSUE TITLE
Different Result (Google's Online - libphonenumber-for-php)

### ISSUE THREAD

**Issue by alvin30595** [giggsey/libphonenumber-for-php#398]
Hi, I noticed there is different in isValidNumberForRegion() for a number' results. Please dm me as I would not prefer to disclose the number at here, thanks

**Comment by giggsey** [comment]
Could you try again now - I've just updated the Demo from 8.12.5 to 8.12.8

**Comment by alvin30595** [comment]
I tried but still the same, do you want the phone number to clarify ? thanks

**Comment by giggsey** [comment]
Sure, you can email it directly to me if you want. [username]@gmail.com

**Comment by alvin30595** [comment]
I had sent you an email, please let me know your findings in here. Thanks

**Comment by giggsey** [comment]
Hi,

The results look the same to me?

**Comment by alvin30595** [comment]
Then must be my mistake on checking it. Sorry for troubling you about it.

**Comment by giggsey** [comment]
It's possible that it did change between 8.12.5 and 8.12.8. I'm sometimes a bit slow to update the PHP demo site on releases.

**Comment by alvin30595** [comment]
There is a possibility of that, but really thanks for your help
