### ISSUE TITLE
Library does not recognize numbers starting with (+995) 511 *** *** as valid numbers

### ISSUE THREAD

**Issue by AlexanderMer** [giggsey/libphonenumber-for-php#401]
Hello, everyone!

I am trying to validate phone numbers like (+995) 511 *** *** which is a valid Georgian phone number serviced by "MagtiCom" provider.

995511 code is present in **src/carrier/data/en/995.php** and is correctly assigned to "MagtiCom"

However it does not pass **PhoneNumberUtil->getNumberTypeHelper()** function.
Given phone number falls through all **if**-s and ends up on getNumberTypeHelper()'s last return statement which returns  **PhoneNumberType::UNKNOWN**

In my understanding, it should return **PhoneNumberType::MOBILE**

After some debugging, I can say that the problem is that national numbers (like 511 28 61 71) do not match this regex pattern **5(?:0(?:0(?:0\d|50)\d|555[5-9])|(?:111\d|8(?:58[89]|888))\d|(?:2222|3333)[0-4]|52(?:00\d|22[0-4])|75(?:00\d|7(?:7[7-9]|8[01])))\d{3}|(?:5(?:[14]4|5[0157-9]|68|7[0147-9]|9[1-35-9])|790)\d{6}**

Please correct me if I'm wrong, in the meanwhile i'll try to correct the pattern and maybe publish a pull request if successful
 

==UPDATE==

The above mentioned regex pattern is in PhoneNumberMetadata_GE.php, line 43

**Comment by giggsey** [comment]
Can you try your example number on Google's demo page, and see what that responds with? https://libphonenumber.appspot.com/

**Comment by AlexanderMer** [comment]
+995**511**286171 is not recognized as valid number
+995**599**286171 and is parsed and even carrier info is displayed

I fixed the regex. Should I submit a pull request to this repo or Google's?

**Comment by giggsey** [comment]
Google aren't currently accepting any metadata pull requests. You'll need to create an issue if you believe the number is being reported incorrectly. You can find the information in their [Contribution Guide](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue).

If/Once Google release a new version, there will be a release of this PHP port shortly afterwards. This project does not accept metadata changes directly.
