### ISSUE TITLE
Overseas France number tests return inconsistent results

### ISSUE THREAD

**Issue by Oxemis** [giggsey/libphonenumber-for-php#408]
Hello,

Thank you for this great library!
We have a problem with the French overseas territories numbers test.

A concrete example: the numbers of Martinique (Country Code: 596).
We can use, from France, the number without the "country code" (example: 06.96.xx.xx.xx) but also the number in international format (+596.696.xx.xx.xx).

The numbers 06.96.xx.xx.xx.xx and +596.696.xx.xx.xx.xx are therefore strictly identical from France.

However, at the moment, we get two different country codes with LibPhoneNumber :

```
        $phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
        $number = $phoneUtil->parse("06 696 00 00 00", "FR");
        echo $number->getCountryCode();        ' <<<< 33
        $number = $phoneUtil->parse("+596 6 696 00 00 00", "FR");
        echo $number->getCountryCode();        ' <<<< 596
```

We would expect both numbers to return the same (so Martinique - 596 which gives the most accuracy).
Is there an option to manage this?

Thanks !

**Comment by giggsey** [comment]
Hi,

Trying the first number in [Google's demo](https://libphonenumber.appspot.com/phonenumberparser?number=06+696+00+00+00&country=FR) returns an invalid number.

If you think this is in error, you'll need to file an issue with Google.

**Comment by Oxemis** [comment]
Hi !

I'm sorry the correct number is 06 96 00 00 00
The test in the Google's demo show the problem : 

For [06 96 00 00 00](https://libphonenumber.appspot.com/phonenumberparser?number=06+96+00+00+00&country=FR)
For [+596 6 696 00 00 00](https://libphonenumber.appspot.com/phonenumberparser?number=%2B596696000000&country=FR)

Both of them are the same number and they should result in the same Country Code (MQ).
Looking to submit the problem to Google but I can't find where I can do that ?

Thanks for you help !

**Comment by giggsey** [comment]
You'll need to use their issue tracker: https://issuetracker.google.com/hotlists/886952

More details can be found in their contributing guide: https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#checklist-before-filing-an-issue

**Comment by Oxemis** [comment]
Thanks @giggsey !
I've added the issue to their tracker.
Thanks for your help and your great work 👍

**Comment by VincentLanglet** [comment]
Hi @Oxemis, any news about this issue ?

**Comment by Oxemis** [comment]
Hi @VincentLanglet,

Yes, I've opened an issue on the Google tracker (https://issuetracker.google.com/issues/171168257).
They changed the default behavior but not in the wanted way...
Now 06 96 xx xx xx and country = fr returns invalid.
I hoped they would have returned MQ but after a lot of discussion with their developers they decided that's better to refuse the number.
