### ISSUE TITLE
38039 is Ukrainian number for Kyivstart carrier

### ISSUE THREAD

**Issue by egorsmkv** [giggsey/libphonenumber-for-php#409]
A number is blocked by the library if I am using parsing with the UA region. 

As I am seeing here: https://github.com/giggsey/libphonenumber-for-php/blob/master/src/carrier/data/uk/380.php there is no this prefix.

Where can I add this prefix?

**Comment by egorsmkv** [comment]
Interesting, that the demo also doesn't recognize the number: https://libphonenumber.appspot.com/phonenumberparser?number=%2B380390417035&country=UA

**Comment by giggsey** [comment]
Hi,

Please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for invalid numbers.

As Google's demo doesn't recognise the number, you'll need to raise an issue with them if the prefix is valid.

**Comment by egorsmkv** [comment]
@giggsey filled the issue in Google's library: https://issuetracker.google.com/issues/171082066
