### ISSUE TITLE
Make a source files branch with all dependencies?

### ISSUE THREAD

**Issue by TomGalla11** [giggsey/libphonenumber-for-php#411]
Hello can you make a branch with all source files and dependencies.
Example:
-SRC(Branch)
--Dependencies (Folder)
---Dep1 (Folder)
----Dep files (Files)

---Dep2 (Folder)
----Dep files (Files)

--src (Your Project files folder)
---google-libphonenumber (All files)

Because I cannot use composer on my web server. And all in one place without composer.json etc. is better.
I hope you can do anything.

Regards
Tom Galla

**Comment by maxhelias** [comment]
Use composer in your web server or change your web server is better.
Nothing prevents you from using composer on your machine to get all dependencies and moving them manually on your server instead of this request.

**Comment by giggsey** [comment]
As @maxhelias suggests, you can do this locally before you upload to your web server.

I will not be creating a branch with deps like this. You can use any PSR-4 autoloader to load the files, and the only dependency is giggsey/locale (which you can look up yourself in composer.json/on Packagist). As mentioned in #224, you could even skip giggsey/locale if you don't use that functionality.

Closing

**Comment by TomGalla11** [comment]
Ok, thank you.
