### ISSUE TITLE
PHP version contradiction

### ISSUE THREAD

**Issue by nachopas** [giggsey/libphonenumber-for-php#414]
In README.md you claim that

> PHP versions 5.3 up to PHP 7.4 are currently supported.

But in commit 3d79856 composer.json got this:

```
  "require": {
    "php": ">=5.3.2",
    "giggsey/locale": "^1.7",
    "symfony/polyfill-mbstring": "^1.17"
  },
```

which is conflicting with the fact that symfony/polyfill-mbstring v1.20.0 requires php >=7.1

I maintain a legacy project and I can't update it beyond 8.12.4. I understand this is not intended because it's a breaking change and version numbers don't conform.

**Comment by giggsey** [comment]
I see that you've closed this already, but just to confirm.

symfony/polyfill-mbstring 1.17 supports PHP 5.3.3 (Okay, we have dropped 5.3.2 support, but if you're that out of date, at least update your 5.3 version): https://github.com/symfony/polyfill-mbstring/blob/v1.17.0/composer.json

**Comment by nachopas** [comment]
Yes, that is correct. After sending it I saw what you just said :)

Problem is composer said it was satisfiable by symfony/polyfill-mbstring
1.20 and installed it, and that's the one that requires php7. The legacy
project I'm maintaining is php5.6. I forced 1.19 and works fine.

Thanks anyway. And thanks for your great job!
