### ISSUE TITLE
Netherlands phone number does not pass validation

### ISSUE THREAD

**Issue by valentin-pazushko** [giggsey/libphonenumber-for-php#417]
For example, +3197010253162 does not pass validation.
Problem is that the returned number type from `getNumberTypeHelper` method is `UNKNOWN`.
Why?

**Comment by giggsey** [comment]
Hi, the number doesn't validate via [Google's demo](https://libphonenumber.appspot.com/phonenumberparser?number=%2B3197010253162&country=NL) either.

If you believe this number is meant to be valid, you'll need to open an issue with them.
