### ISSUE TITLE
Fix Moroccan mobile number pattern

### ISSUE THREAD

**Issue by Brahim1992** [giggsey/libphonenumber-for-php#421]
Hello,
I'm from Morocco and i'm using this amazing bundle to validate phone numbers, however i realized that phone numbers starting with 7 are considered invalid, you can see from here [https://en.wikipedia.org/wiki/Telephone_numbers_in_Morocco](url) that phone numbers starting with 07 belong to mobile network.
Can you make this change ?
Many thanks

**Comment by giggsey** [comment]
Hi,

Please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) regarding invalid numbers.

This project does not accept direct changes to the metadata.
