### ISSUE TITLE
Ivory Coast Numbering Plan Change 

### ISSUE THREAD

**Issue by jorge-costa-ptc** [giggsey/libphonenumber-for-php#422]
Ivory Coast will have its numbering plan changed starting from January 31st.
Phone numbers like this "+225 12345678" will become "+225 27 12345678", this new "27" (for example purposes) prefix will be added between the country and the rest of the number.

More info: https://www.rebtel.com/en/help/article/360018567259-numbering-plan-change-for-ivory-coast/

**Comment by giggsey** [comment]
Hi,

Please take a look at the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) regarding invalid numbers.

This project takes metadata changes from Google's project. If they are aware of the change, they'll update their metadata in a future release. Afterwards, this project will update.
