### ISSUE TITLE
Incorrect phone number verification

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [giggsey/libphonenumber-for-php#424]
Phone: +88029822217
Country: BD

```php
$value = '+88029822217';
$phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
try {
	$parse = $phoneUtil->parse($value, 'BD');
	$isValidNumber = $phoneUtil->isValidNumber($parse);
	var_dump($isValidNumber);
} catch (\libphonenumber\NumberParseException $e) {
	var_dump($e->__toString());
}
```
return false and it should be true

**Comment by giggsey** [comment]
Hi,

Google's demo also returns false for this number: https://libphonenumber.appspot.com/phonenumberparser?number=%2B88029822217&country=BD

If you think this is wrong, I'd suggest filing an issue on Google's issue tracker so they can update their metadata.
