### ISSUE TITLE
Ivory Coast will have its numbering plan changed - Google new Release

### ISSUE THREAD

**Issue by vascoleite** [giggsey/libphonenumber-for-php#426]
Hi,
Ivory Coast will have its numbering plan changed starting from January 31st.
For:
MOOV
MTN
ORANGE

Google already release a new version: https://github.com/google/libphonenumber/releases/tag/v8.12.17
Will be possible a new release before January 31?

Thanks

**Comment by giggsey** [comment]
Have some patience. You opened this less than 90 minutes after Google released the upstream version.

The new version will be here within a few hours (I normally do the releases within a day of Google)

**Comment by giggsey** [comment]
#427

**Comment by giggsey** [comment]
8.12.17 has now been released.
