### ISSUE TITLE
Wrong regex in src/data/PhoneNumberMetadata_FR.php

### ISSUE THREAD

**Issue by clement-muset** [giggsey/libphonenumber-for-php#428]
Hi,

In this file (src/data/PhoneNumberMetadata_FR.php), the mobile NationalNumberPattern regex seems wrong.

It doesn't consider number like : 0690000000 or 0790000000 while these numbers are possible french mobile number

Thank you

**Comment by giggsey** [comment]
Hi,

Please see the FAQ regarding invalid numbers.

**Comment by acantepie** [comment]
Hi,
Google libs considers all numbers beginning by 06 90 XX XX XX invalid, but possible.
(And some of them are valid).

Is it possible to add PossibleNumberType Constraint (or something similar) to validate phonumber with PhoneNumberUtil::isPossibleNumber() ?

**Comment by giggsey** [comment]
The PHP port should return exactly the same. Just comparing '06 90 11 22 33', it returns the same (valid = false, possible = true) on both libraries.

**Comment by acantepie** [comment]
Okay, but is it possible to add constraint that check if number is possible ? (The problem is getNumberType() return UNKNOWN even if number is possible.)

**Comment by acantepie** [comment]
I have found !
Its' a Guadeloupe numbe => https://libphonenumber.appspot.com/phonenumberparser?number=0690112233&country=GP
The problem is i can't use multiple region code to validate PhoneNumber.

**Comment by giggsey** [comment]
I won't make API changes on the PHP side that aren't on Google's side. Otherwise they'll return inconsistent results.

As for multiple region codes, are you not able to try them in a loop? If you know the number of going to be French, or one of it's overseas departments, then try them in a loop until you get a valid number.

**Comment by acantepie** [comment]
I undesrtand.
There is AtLeastOneOf annotation on SF5 (https://symfony.com/doc/current/reference/constraints/AtLeastOneOf.html) but i am using sf4.

Finally, I have just created a new Validator trying only to parse number with an unknown region.
