### ISSUE TITLE
How to search by phone number using any format

### ISSUE THREAD

**Issue by Brahim1992** [giggsey/libphonenumber-for-php#429]
Hello,
Thanks for this amazing bundle.
I want to perform a search query on the phone number field, which it's stored in this format on the database : +2126xxxxxxxx.
The problem is that i can't get a match when searching with another format like : 06xxxxxxxx or +21206xxxxxxxx.
Any workaround to make the match happen ?
Many thanks

**Comment by giggsey** [comment]
This may be better posted on Google's mailing list, as you might get more feedback there (this isn't just a PHP question).

What we do (which isn't perfect):

We're storing the numbers normalised to E164 in the DB, just like you. When someone enters a number, we try to convert it to E164, and search based on that. We also do a partial number search on their input, and strip any leading zeros (the majority of our customers are UK based, which has a leading zero) and do a partial search for this.

Examples:

If the number in the DB is +441174960123.

 - Search: '01174960123'. Convert to E164, exact match.
 - Search '1174960123'. Convert to E164, exact match
 - Search '0117'. Unable to parse number. Strip leading zero, partial search on %117%.

**Comment by Brahim1992** [comment]
This solution will definitely work, i didn't think of it.
Many thanks.
