### ISSUE TITLE
Remove dependency on ext-intl

### ISSUE THREAD

**Issue by giggsey** [giggsey/libphonenumber-for-php#43]
This is a thought I've had for a few weeks now, but writing it down so progress can be tracked.
## The Problem

The ext-intl dependency only exists because the Offline Geocoder needs to use [Locale](http://uk3.php.net/Locale) functions to get the country name.

This makes the library dependent on the version of libicu installed on the server, which could be out of date.

For instance, one of my Ubuntu (latest LTS release) machines returns different country names to the Travis boxes, so the unit tests do not pass on my local machine.
## The Proposal

Introduce a new package that only contains the functions that the Offline Geocoder requires, and compile the latest data from [CLDR](http://cldr.unicode.org/). This would be a separate package from libphonenumber-for-php to allow the two to update independently.
### Functions Required
- [ ] [`getPrimaryLanguage()`](http://php.net/manual/en/locale.getprimarylanguage.php)
- [ ] [`getRegion()`](http://php.net/manual/en/locale.getregion.php)
- [ ] [`getDisplayRegion()`](http://php.net/manual/en/locale.getdisplayregion.php)

**Comment by adamlc** [comment]
@giggsey you might be able to use Symfony/Intl to get the country names if thats all you need Intl for :)

http://symfony.com/doc/current/components/intl.html

**Comment by giggsey** [comment]
I think I've looked before, and the newer versions of it still need the
extension.
