### ISSUE TITLE
+3371700**** This number showing invalid inspite of being a valid number

### ISSUE THREAD

**Issue by VivekBisht21** [giggsey/libphonenumber-for-php#433]
Hello Team, 

we updated to latest tag `8.12.19`, still
+3371700**** This number showing invalid inspite of being a valid number.

https://giggsey.com/libphonenumber/index.php?phonenumber=%2B33+717001974&country=FR&language=&region=

**Comment by giggsey** [comment]
Hi,

Take a look at the FAQ regarding invalid numbers. The number you provided also shows as invalid when using Google's demo.

**Comment by silvermarten88** [comment]
I am having the same problem. number is valid in google java demo. 068565**** FR

**Comment by giggsey** [comment]
> I am having the same problem. number is valid in google java demo. 068565**** FR

That validates using the PHP demo: https://giggsey.com/libphonenumber/index.php?phonenumber=0685651234&country=FR&language=&region=

**Comment by silvermarten88** [comment]
@giggsey 

1. Will double check
2. Yes

thanks

**Comment by silvermarten88** [comment]
@giggsey 

1) i have updated from 8.12.15 => 8.12.20, still seeing the 
```

"libphonenumber\NumberParseException
The string supplied did not seem to be a phone number."
```

**Comment by giggsey** [comment]
I've just tried this code with 8.12.20, and it works fine:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$numberUtil = \libphonenumber\PhoneNumberUtil::getInstance();

$number = $numberUtil->parse('0685651234', 'FR');

var_dump($numberUtil->isValidNumber($number)); // true
```

**Comment by silvermarten88** [comment]
@giggsey I guess im doing something wrong i will have to investigate, i will update you.
thanks a lot.

**Comment by zarunet** [comment]
If you landed here after wondering why your placeholder `0712345678` or whatever was rejected, here's why :

French 07 numbers are only valid from `0730xxxxxx` to `0789xxxxxx`. [Source](https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200004A0002PDFE.pdf)
