### ISSUE TITLE
Problem with Vatican city

### ISSUE THREAD

**Issue by webmake** [giggsey/libphonenumber-for-php#438]
Country code +379
error:
`Could not interpret numbers after plus-sign.`

**Comment by giggsey** [comment]
Hi,

There probably should be a bit more information here.

Regardless, take a look at the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers), as that'll probably answer your question.

**Comment by webmake** [comment]
I cannot share full number due GDPR, but everything is okay with same number but prefix +39, but +379 also legit https://countrycode.org/vatican

**Comment by webmake** [comment]
I tested via https://github.com/google/libphonenumber it gives same result, so closing this one bug report..
