### ISSUE TITLE
Issue with isValidNumber()

### ISSUE THREAD

**Issue by bberjawi** [giggsey/libphonenumber-for-php#441]
When testing a French number starting with 92 (e.g. '+33692******') (replace the 8 * by any numbers) on the demo page, the result of isValidNumber() is false. Which is normal.

But on my code, the result is always true : 
```
$phoneNumberUtil = \libphonenumber\PhoneNumberUtil::getInstance();
$numberProto = $phoneNumberUtil->parse('+33692******');
var_dump($phoneNumberUtil->isValidNumber($numberProto)); // true
```

Any explanation ?

**Comment by giggsey** [comment]
Could you try the demo again, I always forget to update it after a new release.

**Comment by bberjawi** [comment]
Nothing change, the demo always return false, which is correct because number that starts with 692 are no longer valid in France.

**Comment by giggsey** [comment]
Is your version up to date?

**Comment by bberjawi** [comment]
my version was not up to date, i have juste installed it, and it is blocked on 8.12.4 due to my project requirements.
No problem with the last version 8.12.23

Thank you for you help
