### ISSUE TITLE
Mobile number for La Réunion (FR) is not recognized

### ISSUE THREAD

**Issue by tomcodes** [giggsey/libphonenumber-for-php#446]
Hello!  
First of all thank you very much for the library that's very useful.

Yesterday when I deployed to production (I know, on a Friday, right?) I noticed several bugs around phone numbers management for one particular user that lives in [La Réunion](https://en.wikipedia.org/wiki/R%C3%A9union) (overseas department of France).

After a bit of debugging I managed to pinpoint the issue to how libpbonenumber-for-php handles phones numbers for La Réunion.

I rely on [Laravel-phone](https://github.com/Propaganistas/Laravel-Phone) library for this code snippet:

```php
PhoneNumber::make('+33692112233')->formatNational();
```

I can not provide the country as I am trying to guess the country from the number.
This triggers the following error:

```
Propaganistas\LaravelPhone\Exceptions\NumberParseException
Number requires a country to be specified. 
```

Looking at the exception led me to [this particular line](https://github.com/Propaganistas/Laravel-Phone/blob/master/src/PhoneNumber.php#L277).

It seems the number is not recognized as belonging to any country.

You can see a demo of this issue with the following test URL:

https://giggsey.com/libphonenumber/index.php?phonenumber=%2B33693112233&country=&language=&region=

The +3369 prefix seems to be the issue (corresponding to La Réunion prefix); if you put another prefix it works: properly:

https://giggsey.com/libphonenumber/index.php?phonenumber=%2B33683112233&country=&language=&region=

I'd be glad to contribute to a fix for this but don't know where to start.  
Thanks for any feedback on this matter!

**Comment by giggsey** [comment]
Isn't this because Réunion's country code is +262?

**Comment by tomcodes** [comment]
Yes, Réunion's country is indeed +262, but I am afraid it is a bit more complicated than that. It seems some numbers starting also with +336 are routed to the Réunion:

https://www.arcep.fr/demarches-et-services/professionnels/base-numerotation.html?tx_arcepbasetechnique_basetechnique%5B__referrer%5D%5B%40extension%5D=ArcepBasetechnique&tx_arcepbasetechnique_basetechnique%5B__referrer%5D%5B%40vendor%5D=GAYA&tx_arcepbasetechnique_basetechnique%5B__referrer%5D%5B%40controller%5D=BaseTechnique&tx_arcepbasetechnique_basetechnique%5B__referrer%5D%5B%40action%5D=search&tx_arcepbasetechnique_basetechnique%5B__referrer%5D%5Barguments%5D=YTowOnt93f79ac872f3e891e3d121304494af15ceeb744e4&tx_arcepbasetechnique_basetechnique%5B__referrer%5D%5B%40request%5D=a%3A4%3A%7Bs%3A10%3A%22%40extension%22%3Bs%3A18%3A%22ArcepBasetechnique%22%3Bs%3A11%3A%22%40controller%22%3Bs%3A13%3A%22BaseTechnique%22%3Bs%3A7%3A%22%40action%22%3Bs%3A6%3A%22search%22%3Bs%3A7%3A%22%40vendor%22%3Bs%3A4%3A%22GAYA%22%3B%7Da2bf59f355c30621a92ab741b949e14e74a32abc&tx_arcepbasetechnique_basetechnique%5B__trustedProperties%5D=a%3A1%3A%7Bs%3A6%3A%22search%22%3Ba%3A1%3A%7Bs%3A7%3A%22numeros%22%3Bi%3A1%3B%7D%7D6c5a73b9b235b8db1e19b0bafed7ac83147025d4&tx_arcepbasetechnique_basetechnique%5Bsearch%5D%5Bnumeros%5D=06931#c981

ARCEP is the official authority regulating telecommunications in France.

**Comment by giggsey** [comment]
This question would be best suited for Google's mailing list then.

**Comment by tomcodes** [comment]
Oh I see, sorry I did not realize that this library was based on metadata from Google's libphonenumber. I'll create the issue on their repo then.

Thank you!
