### ISSUE TITLE
Netherlands Antilles Country Code: Missing or invalid default region

### ISSUE THREAD

**Issue by masonmcelvain** [giggsey/libphonenumber-for-php#447]
Hi!

I originally posted this issue on brick/phonenumber https://github.com/brick/phonenumber/issues/14#issue-921854737, and a contributor directed me to post the issue here as that library is a wrapper around this one.

When trying to parse phone numbers of the format `599 XXXX XXXX` with country code `AN`, `parse()` raises a `PhoneNumberParseException` with the message `Missing or invalid default region.`.

e.g.
```php
$phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
try {
   $number = $phoneUtil->parse('59912345678', 'AN');
   echo $number->format(\libphonenumber\PhoneNumberFormat::E164);
} catch (\libphonenumber\NumberParseException $e) {
   echo $e->getMessage();
}
```

[Netherlands Antilles was dissolved in 2010](https://en.wikipedia.org/wiki/Telephone_numbers_in_Cura%C3%A7ao_and_the_Caribbean_Netherlands#:~:text=International%20Call%20Prefix%3A%2000,%2C%20Sint%20Eustatius%20and%20Saba) - is this why phone numbers from this country are not supported by `parse()`?

The [Netherlands Antilles Alpha-2 code was 'AN'](https://www.iso.org/obp/ui/#iso:code:3166:AN), and the Alpha-2 codes of most other countries seem to work with `parse()`.

The [country calling code of Netherlands Antilles](https://countrycode.org/netherlandsantilles) was `599`, and it is now in use in Curaçao and the Caribbean Netherlands.

Thanks for your time and maintaining this package 😄

**Comment by giggsey** [comment]
Firstly, the bad news. This library is just a PHP Port of Google's libphonenumber project. The API & metadata are both mirrors of their project. Asking on their mailing list will be the best bet for an accurate answer.

However, the library only maintains current numbering data, so this is probably why 'AN' isn't supported anymore. In fact, their FAQ mentions Netherlands Antilles: https://github.com/google/libphonenumber/blob/master/FAQ.md#why-are-bouvet-island-bv-pitcairn-island-pn-antarctica-aq-etc-not-supported

**Comment by masonmcelvain** [comment]
Thanks for the quick response and linking the documentation. It seems that I'll just have to work around this, as I doubt I'll be able to change the maintainer's mind about supporting dissolved countries.

I also realized that you hinted at the libphonenumber in your [README](https://github.com/giggsey/libphonenumber-for-php#faq). Thanks for the detailed response anyways!
