### ISSUE TITLE
How to get clean phone number and extension

### ISSUE THREAD

**Issue by viciexperts** [giggsey/libphonenumber-for-php#451]
Hello,
Thank you for this great tool.
What is the best way to get the cleaned phone number and also the phone extension?

```
 $phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
$NumberProto = $phoneUtil->parseAndKeepRawInput('+44 7858 474757', 'GB');
 echo '<pre>';
 var_dump($NumberProto);
 var_dump(substr($phoneUtil->format($NumberProto, \libphonenumber\PhoneNumberFormat::E164),3));
  echo '</pre>';
```

Is there a way to get the national phone number variable:   ["nationalNumber":protected]=>  string(10) "7858474757"
Also the extension:   ["extension":protected]=>
Like this https://www.npmjs.com/package/google-libphonenumber
Thank you

Output:
```
object(libphonenumber\PhoneNumber)#11 (9) {
  ["countryCode":protected]=>
  int(44)
  ["nationalNumber":protected]=>
  string(10) "7858474757"
  ["extension":protected]=>
  NULL
  ["italianLeadingZero":protected]=>
  NULL
  ["rawInput":protected]=>
  string(15) "+44 7858 474757"
  ["countryCodeSource":protected]=>
  int(0)
  ["preferredDomesticCarrierCode":protected]=>
  NULL
  ["hasNumberOfLeadingZeros":protected]=>
  bool(false)
  ["numberOfLeadingZeros":protected]=>
  int(1)
}
string(10) "7858474757"
```

**Comment by giggsey** [comment]
The PhoneNumber object has getters for all of the properties. E.g. `getNationalNumber()`, and `getExtension()`

**Comment by viciexperts** [comment]
Is not working. I see that function locate at PhoneNumber.php:289:    public function getNationalNumber()

But is not working:  Uncaught Error: Call to undefined function getNationalNumber()

```
$phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
$countryCode='GB';

$NumberProto = $phoneUtil->parseAndKeepRawInput('+44 7858 474757 x 258', $countryCode);


echo '<pre>';
var_dump($NumberProto);
echo "<br>Phone:";
echo $NumberProto.getNationalNumber();
```
output:
object(libphonenumber\PhoneNumber)#11 (9) {
  ["countryCode":protected]=>
  int(44)
  ["nationalNumber":protected]=>
  string(10) "7858474757"
  ["extension":protected]=>
  string(3) "258"
  ["italianLeadingZero":protected]=>
  NULL
  ["rawInput":protected]=>
  string(21) "+44 7858 474757 x 258"
  ["countryCodeSource":protected]=>
  int(0)
  ["preferredDomesticCarrierCode":protected]=>
  NULL
  ["hasNumberOfLeadingZeros":protected]=>
  bool(false)
  ["numberOfLeadingZeros":protected]=>
  int(1)
}

Phone:

**Comment by giggsey** [comment]
That's not PHP.

It should be echo $NumberProto->getNationalNumber();

**Comment by viciexperts** [comment]
It works. Thank you.
