### ISSUE TITLE
iranian phone number not valid?

### ISSUE THREAD

**Issue by hooman-mirghasemi** [giggsey/libphonenumber-for-php#452]
https://mobilebnk.com/hamrahe-aval/

phone number like +98993XXXXXXX
and 
+98994XXXXXXX
should be valid. and this libraray say this number is not valid:
+989934XXXXXX

All number start with 
+98994XXXXXXX
+98993XXXXXXX
should be valid.

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.

**Comment by hooman-mirghasemi** [comment]
sorry but https://libphonenumber.appspot.com/
link dont open for me, show 403!

**Comment by giggsey** [comment]
Are you trying to access the Google App Engine instance from within Iran? There are articles suggesting that it is blocked.

**Comment by hooman-mirghasemi** [comment]
Unfortunately yes. And I could not enter the link with any VPN

**Comment by giggsey** [comment]
I just tried '+989934111111' on both Google's demo, and the libphonenumber-for-php demo, and they both validate fine.

**Comment by hooman-mirghasemi** [comment]
+989934772366
please try this number. it is valid number some one using this. can he try to signup in our site with this.

**Comment by giggsey** [comment]
I've edited your comment to remove the number.

The number validates on both libraries:

![gnome-shell-screenshot-XVDP60](https://user-images.githubusercontent.com/305730/127123897-acd21edd-01c5-48ae-8bb4-4f50181148f5.png)

Are you on the latest version of libphonenumber-for-php?

**Comment by hooman-mirghasemi** [comment]
yes i am using 

"version": "8.12.28"

**Comment by hooman-mirghasemi** [comment]
I try it in tow project one in yii2 
and an other one in laravel using Laravel Phone.
both using "version": "8.12.28"
I also try +989934111111
but both of them not valid number!

**Comment by giggsey** [comment]
Are you calling `parse('+98993[removed by giggsey]')` in full E164, or are they entering it in another format with a default region set?

**Comment by hooman-mirghasemi** [comment]
I exactly type E164 format with +98 in my fileds.
and do not set any default region in laravel project.

in yii2 project i set iran as default regeion but also i enter full number with e164 format: +989934111111

**Comment by giggsey** [comment]
Could you try a simple demo script?

```
<?php
require __DIR__ . '/vendor/autoload.php';

$numberUtil = \libphonenumber\PhoneNumberUtil::getInstance();

$number = $numberUtil->parse('+989934111111');

var_dump($numberUtil->isValidNumber($number)); // true
```

**Comment by hooman-mirghasemi** [comment]
I try it 
it return true!
I confiused. why this code you send return true.

but. https://github.com/Propaganistas/Laravel-Phone
with laravel validation code:
` 'cell' => [ Rule::phone()->detect()->type('mobile')],`

return false!

**Comment by giggsey** [comment]
It's not a mobile number, but VOIP.

**Comment by hooman-mirghasemi** [comment]
I found the problem the number not detect as mobile .
I remove type in both project type was mobile.

**Comment by hooman-mirghasemi** [comment]
Thank you! 
But I khow this is normal simcard. not voip phone!

https://simcart.com/simcard/%D9%87%D9%85%D8%B1%D8%A7%D9%87-%D8%A7%D9%88%D9%84/0993/%D8%A7%D8%B9%D8%AA%D8%A8%D8%A7%D8%B1%DB%8C/

carrier sim card is hamrahe aval

**Comment by giggsey** [comment]
That's the bit that'll need reporting to Google then

**Comment by hooman-mirghasemi** [comment]
https://shop.mci.ir/sim-cards/credit/emerald

![Screenshot from 2021-07-27 13-52-37](https://user-images.githubusercontent.com/11981070/127130108-f505447c-9acc-44ca-aabf-4eb759182777.png)

but Unfortunately I live in Iran and can not open google most services 
If possible, please report it to Google.
Thank you!

**Comment by giggsey** [comment]
https://issuetracker.google.com/issues/194754688

**Comment by hooman-mirghasemi** [comment]
Thank you very much

**Comment by giggsey** [comment]
I'll try to remember and post any updates here.

For now, I'll close this issue.

**Comment by giggsey** [comment]
Update:

> Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

**Comment by giggsey** [comment]
@hooman-mirghasemi Just an update that Google marked the issue as fixed on August 2nd. I've just confirmed it with the latest version of libphonenumber (it may have been in the previous release), and the number is now showing as mobile.

**Comment by hooman-mirghasemi** [comment]
Thank you!
