### ISSUE TITLE
PH 0913 is invalid

### ISSUE THREAD

**Issue by lloricode** [giggsey/libphonenumber-for-php#455]
Hi Philippines have update with additional 0913, but using this package seems not recognize. 

giggsey/libphonenumber-for-php: 8.12.28 
php: 7.4.18 | 8.0.8

test playground
https://giggsey.com/libphonenumber/index.php?phonenumber=09132123123&country=PH&language=&region=
![Screenshot from 2021-08-05 08-19-09](https://user-images.githubusercontent.com/8251344/128271962-e2b714c5-d4e8-4e9d-8661-b0324c60259a.png)

update:
https://www.prefix.ph/prefixes/2019-updated-complete-list-of-philippine-mobile-network-prefixes/
![Screenshot from 2021-08-05 08-15-56](https://user-images.githubusercontent.com/8251344/128271748-6552544b-4c89-4455-843d-e66359a79b84.png)

we using package as 3rd party [propaganistas/laravel-phone:4.3.1](https://github.com/Propaganistas/Laravel-Phone/releases/tag/4.3.1)

Thank you

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.

**Comment by lloricode** [comment]
> Hi,
> 
> Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.
> 
> You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.

Hi @giggsey thank for the response, will check this as soon, thank you
