### ISSUE TITLE
Missing area codes 891 in RU phone numbers

### ISSUE THREAD

**Issue by reptily** [giggsey/libphonenumber-for-php#459]
Hi,
The library does not accept phone number with area codes 891 
example +78912223366
This is phone number is valid in RU
Use version 8.12.29

https://libphonenumber.appspot.com/phonenumberparser?number=+78912223366&country=RU
demo https://giggsey.com/libphonenumber/?phonenumber=+78912223366&country=RU&language=&region=

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.

**Comment by reptily** [comment]
Hi,
Thanks for the info. The number is valid. You can see it here: https://libphonenumber.appspot.com/phonenumberparser?number=%2B78912223366&country=RU&geocodingLocale=und-891

New issue created in google https://issuetracker.google.com/issues/196983131

**Comment by giggsey** [comment]
Thanks,

I'll close this issue for now.

When/If Google fix it, this PHP port will be updated on their next release.
