### ISSUE TITLE
getNationalNumber() is dropping the leading zero for AU phone numbers.

### ISSUE THREAD

**Issue by b-hayes** [giggsey/libphonenumber-for-php#462]
As the title says. The leading 0 is required to dial the number in Australia without it you get an incorrect or incomplete answering message.

This test unit will fail:
```
        $number = '0433456881'; 
        self::assertEquals($number,
            PhoneNumberUtil::getInstance()
                ->parse($number, 'AU')
                ->getNationalNumber()//results in "433456881"
        );
```

This is what I get:
```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'0433456881'
+'433456881'
```

Any variation of this will also fail  such as:
'0433 456 881', 'AU
'+61 433 456 881','AU' 
'0433456881', 'AU'
'+61433456881', 'AU'

**Comment by b-hayes** [comment]
What's the point of the national phone number method then if we need to implement our own checks for every possible country.

This is my work around fo AU hone numbers atm.
```

        if ($this->phoneNumberObject) {
            $this->nationalNumber = $this->phoneNumberObject->getNationalNumber();
        }

        //fix AU phone numbers
        if ($this->phoneNumberObject && $this->countryCode == 'AU') {
            $auNationalAreaCodesWithoutTheLeadingZero = [
                'Central East	New South Wales & Australian Capital Territory' => '2',
                'South East	Victoria & Tasmania' => '3',
                'Mobile Telephones	Australia-wide' => '4',
                'North East	Queensland' => '7',
                'Central & West	Western Australia, South Australia & Northern Territory' => '8',
            ];
            if (in_array($this->nationalNumber[0], $auNationalAreaCodesWithoutTheLeadingZero)) {
                $this->nationalNumber = '0' . $this->nationalNumber;
            }
        }
```

**Comment by b-hayes** [comment]
Ah sorry, didn't notice the link you gave.
```
PhoneNumberUtil::getInstance()
    ->format($phoneNumberObject, PhoneNumberFormat::NATIONAL)
```
returns '0433 456 881' which is valid but now contains spaces.

Is there a way to get a valid number without spaces?

**Comment by b-hayes** [comment]
Then I realized it adds brackets too lol. 
So now this is the workaround if using the suggested format() method:
```
            $phoneNumberUtil = PhoneNumberUtil::getInstance();
            $this->phoneNumberObject = $phoneNumberUtil->parse($phoneNumber, $countryCode);
            $nationalNumberWithSpaces = $phoneNumberUtil->format($this->phoneNumberObject, PhoneNumberFormat::NATIONAL);
            $this->nationalNumber = str_replace([' ','(', ')'],'', $nationalNumberWithSpaces);
```
You can see why I think this is a problem right?

I can't imagine why anyone would want the phone object created from parse() to contain bad data.

**Comment by b-hayes** [comment]
What's the point of the `getNationalNumber()` then?

I can't imagine anyone expecting an invalid phone number after successfully creating a phone number object with `parse()`. 
Its just bad data you cant use.

Should parse not be setting up the object with accurate information in the first place?

Here is the workarounds I've had to go through so far...

Fist assumption was the library was broken so reported issue and then did this in my code:
```
//fix AU phone numbers
        if ($this->phoneNumberObject && $this->countryCode == 'AU') {
            $auNationalAreaCodesWithoutTheLeadingZero = [
                'Central East	New South Wales & Australian Capital Territory' => '2',
                'South East	Victoria & Tasmania' => '3',
                'Mobile Telephones	Australia-wide' => '4',
                'North East	Queensland' => '7',
                'Central & West	Western Australia, South Australia & Northern Territory' => '8',
            ];
            if (in_array($this->nationalNumber[0], $auNationalAreaCodesWithoutTheLeadingZero)) {
                $this->nationalNumber = '0' . $this->nationalNumber;
            }
        }
```

Then I tried using the format method. But this gave me numbers with spaces and brackets added in so had to add a workaround again:
```
            $phoneNumberUtil = PhoneNumberUtil::getInstance();
            $this->phoneNumberObject = $phoneNumberUtil->parse($phoneNumber, $countryCode);
            $nationalNumberWithSpaces = $phoneNumberUtil->format($this->phoneNumberObject, PhoneNumberFormat::NATIONAL);
            $this->nationalNumber = str_replace(' ','', $nationalNumberWithSpaces);
```
Then I realized there is a formatNumberForMobileDialing() method. 
```
$this->nationalNumber = $phoneNumberUtil->formatNumberForMobileDialing($this->phoneNumberObject, $countryCode, false);
```
But now that method isn't working for US numbers returning the number with country code.

You can see why I think it's a problem right?

Would it not be easier to just have the `getNationalNumber()` method return the correct data?

**Comment by b-hayes** [comment]
Assuming this is the safest way to get the national number for all countries. So sticking with this unless you have some better advice.
```
            $phoneNumberUtil = PhoneNumberUtil::getInstance();
            $this->phoneNumberObject = $phoneNumberUtil->parse($phoneNumber, $countryCode);
            //note: ->getNationalNumber() is broken for AU numbers so we have to for display first and then strip the extra chars out.
            $formattedNationalNumber = $phoneNumberUtil->format($this->phoneNumberObject, PhoneNumberFormat::NATIONAL);
            $this->nationalNumber = str_replace([' ','(', ')'],'', $formattedNationalNumber);
        } catch (NumberParseException $e) {
```

**Comment by giggsey** [comment]
Lets rewind a little bit: What are you trying to achieve?

The PhoneNumber data object returned by parse() is for use in other methods in PhoneNumberUtil (format, isValid etc.). Whilst you can access the properties on it, it's not recommended, as most countries are not as simple as getNationalNumber() (as you've discovered with the leading zeros in Australia).

Formatting to the national number has plenty of edge cases that the library will take care of. Australian numbers are formatted with the spaces and brackets (e.g. `(02) 5124 2613` (Canberra Health Services)).

**Comment by b-hayes** [comment]
> Lets rewind a little bit: What are you trying to achieve?

I am receiving numbers in international format along with the two-letter country code and I am converting them back into a local number for a legacy system to save. Without going in-depth rest assured I can't save the numbers in international format without extensive work.

So I'm sticking with the string replace of the formatted numbers.

> The PhoneNumber data object returned by parse() is for use in other methods in PhoneNumberUtil 
yeah Im starting to see that object>methodsNotToBeUsed() lol.

**Comment by giggsey** [comment]
Okay.

Instead of the manual str_replace, you can use normalizerDiallableCharsOnly() to remove all the 'extra'.

What we do to format numbers to display on physical handsets is:

```php
if ($phoneUtil->isValidNumber($number)) {
    $number->clearExtension();
    $returnNumber = $phoneUtil->formatOutOfCountryCallingNumber($number, $region);

    $returnNumber = PhoneNumberUtil::normalizeDiallableCharsOnly($returnNumber);
}
```

**Comment by b-hayes** [comment]
Still haven't gotten back to this yet so my str replace method is still being used 😂. Would the `formatOutOfCountryCallingNumber()` add country codes to the number defeating the purpose?

**Comment by giggsey** [comment]
If region is the same as the number region, it'll be national format.
Otherwise it'll be international.

**Comment by b-hayes** [comment]
Ah right, that makes sense. Thanks for the help. I'll try and come back and implement it this way when I get on top of things.
