### ISSUE TITLE
Add phone code country .

### ISSUE THREAD

**Issue by port20031** [giggsey/libphonenumber-for-php#465]
Hi.
How to add new data (country, code) to the database?

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.

**Comment by port20031** [comment]
The base is not complete.
How to add a telephone mask with a country to the database?

**Comment by giggsey** [comment]
You need to report an issue to Google if you have discovered a number range that is not supported correctly.

If/When they accept and fix the issue, it'll get updated here after their next release. This PHP port is not responsible for the metadata.

**Comment by port20031** [comment]
Thank you! 


<br class="Apple-interchange-newline">
