### ISSUE TITLE
[Help] How to invalidate number

### ISSUE THREAD

**Issue by MrNonoss** [giggsey/libphonenumber-for-php#471]
Hi!

I am probably doing something wrong, but I have issue to in/validate phone numbers.

Here is a short example:
```php
function tphValidate($p)
{
	$phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
	$phoneInfo = $phoneUtil->parse($p, null);
	$isValid = $phoneUtil->isValidNumber($phoneInfo);
	return $isValid;
}
```
Will return "1" if the supplied $p is a valid E164 phone number, but won't return anything is $p is something else.
What should I do to get a false?

Many thanks for your help.

**Comment by giggsey** [comment]
```php
var_dump(tphValidate('+441174960123')); // bool(true)
var_dump(tphValidate('+4411749603')); // bool(false)
```

Hi, it is returning false already. Just be careful of parse(), as it will throw Exception is the number is obviously wrong (unparseable)

**Comment by giggsey** [comment]
Yes, otherwise:

```php
var_dump(tphValidate('+rubbish'));

// PHP Fatal error:  Uncaught Error type: 1. The string supplied did not seem to be a phone number.


```
