### ISSUE TITLE
Invalid Singapore Number

### ISSUE THREAD

**Issue by mlph-relefante** [giggsey/libphonenumber-for-php#478]
Hi,

I have these digits +6580222781 that I tried both on the Google Online Demo and Giggsey Online Demo. 
For Google, it is valid while here, it is not. 
Please assist on how to proceed. 

Thank you. 
<img width="430" alt="Screen Shot 2021-11-18 at 7 22 46 PM" src="https://user-images.githubusercontent.com/61221763/142406517-a9366efc-4c78-47b3-aaf1-f9da9010bc3d.png">
<img width="451" alt="Screen Shot 2021-11-18 at 7 22 33 PM" src="https://user-images.githubusercontent.com/61221763/142406533-b34a1778-ddf0-4058-8582-0b5259df8a00.png">

**Comment by giggsey** [comment]
Apologies, I hadn't updated the demo with the latest release.

I've just updated it and the number is now validating fine

**Comment by mlph-relefante** [comment]
I tried again and now it is valid. I might need to update the lib in our code then. Thank you!
