### ISSUE TITLE
Case sensitive isValidRegionCode function 

### ISSUE THREAD

**Issue by blacklizard** [giggsey/libphonenumber-for-php#480]
The function `isValidRegionCode` should accept region/country code in both lower case and upper case as per `google/libphonenumber`

Reference `https://github.com/google/libphonenumber/blob/7f20d4f7c26bb5d23f2caf86ec37d60f992a3031/javascript/i18n/phonenumbers/phonenumberutil.js#L1671`

If this issue is acceptable, I will create a PR

**Comment by giggsey** [comment]
Good spot, thanks.

Please do submit a PR. Are there any other places that need to strtoupper?

**Comment by blacklizard** [comment]
So far this is the only place i've encountered while porting my code from js to php. Will create PR after finish work

**Comment by giggsey** [comment]
Fixed in #534
