### ISSUE TITLE
After 8.12.40 to 8.12.41 issue

### ISSUE THREAD

**Issue by dvaezazizi** [giggsey/libphonenumber-for-php#487]
After: Upgrading giggsey/libphonenumber-for-php (8.12.40 => 8.12.41)

$data->phone = $phoneNumberUtil->format($phoneNumberObject, \libphonenumber\PhoneNumberFormat::E164);

Getting "\libphonenumber\PhoneNumberFormat" undefined type

**Comment by giggsey** [comment]
Can you share some sample code?

E.g.

```php
<?php
require 'vendor/autoload.php';
$phoneNumberUtil = ...
```

**Comment by dvaezazizi** [comment]
Issue resolved. This was a vscode php intellisense issue.
