### ISSUE TITLE
BUG: Valid phone not parsed properly based on the country default argument

### ISSUE THREAD

**Issue by kanevbg** [giggsey/libphonenumber-for-php#493]
https://giggsey.com/libphonenumber/index.php?phonenumber=00114104911111&country=US&language=&region=
vs
https://giggsey.com/libphonenumber/index.php?phonenumber=00114104911111&country=GB&language=&region=

Why there is difference? When a proper default US for country is supplied it does resolve to isItalianLeadingZero = true but if I use GB which is wrong default, than isItalianLeadingZero is false and the parser works correctly thus the formatting too.

**Comment by giggsey** [comment]
`01114104911111` is accepted, although I'm not sure why.

As Google's library returns the same results: https://libphonenumber.appspot.com/phonenumberparser?number=00114104911111&country=US, I think you'll be best asking on their mailing list.

**Comment by kanevbg** [comment]
So I did: https://issuetracker.google.com/issues/218578950

**Comment by giggsey** [comment]
Closing this issue as it's not an issue with this PHP port.

If/When Google fix the issue, it'll get mirrored here.
