### ISSUE TITLE
Missing leading zero CI national phone number ?

### ISSUE THREAD

**Issue by Fly06-Fr** [giggsey/libphonenumber-for-php#495]
Hello,
We are experiencing a problem with Ivory Coast mobile numbers.
The leading zero is required for both national and international dialing and this is correctly handled by the library when using the format() method.
Don't you think that in such a situation, the number returned by the getNationalNumber() method should include the leading zero? (which is not currently the case).
Example: https://giggsey.com/libphonenumber/index.php?phonenumber=0789881234&country=CI
Many thanks in advance for your reply.

**Comment by giggsey** [comment]
getNationalNumber() shouldn't be used for formatting. The format() function
will handle any leading zeros in the number.

There is a separate function on the PhoneNumber object to return the
leading zeros.

**Comment by Fly06-Fr** [comment]
Hi Joshua and thank for the quick reply.

The leading zero in Ivory Coast mobile phone numbers is not a [trunk prefix](https://en.wikipedia.org/wiki/Trunk_prefix#Africa), it is just the first digit of the two digit operator prefix. Contrary to many others countries, there is no trunk prefix in the [Ivory Coast dialing  plans](https://en.wikipedia.org/wiki/Telephone_numbers_in_Ivory_Coast).

Hence, the number returned by the getNationalNumber() method for a given CI mobile number should include the leading 0 and be 10 digit long.

**Comment by giggsey** [comment]
As the Google demo returns the same thing: https://libphonenumber.appspot.com/phonenumberparser?number=0789881234&country=CI, I think you'll need to file an issue with them.

**Comment by Fly06-Fr** [comment]
Done.
I will keep you updated.
Thank you.

**Comment by Fly06-Fr** [comment]
Hi Joshua,
The issue has not been accepted as a bug by the google/libphonenumber team.

I got the following answer :  _Though the national_number field of parsed proto do not contain 0, the 0s are represented as italian_leading_zero (TRUE) and number_of_leading_zeros (1). Reason: 0s are lost as national_number is a number type field. Please do consider those fields if you need to fetch these details._ 

The point is that the number returned by the getNationalNumber() method is useless since it is not recognized as a valid number by the library in that case. By digging into the source files, I found the PhoneNumberUtil::getNationalSignificantNumber() method which actually returns the national_number but including the italian leading zeros. 

Do you confirm that the relevant number to store into a database is this "national significant number" and not the national_number?

**Comment by giggsey** [comment]
If you are storing the phone number, I'd be storing E164.

**Comment by Fly06-Fr** [comment]
This is probably the best solution but for historical reasons we are storing phone numbers by using two fields:

- international_prefix
- national_number

And for the time being I must cope with this design.

**Comment by Fly06-Fr** [comment]
Do you know which countries other than Italy and Ivory Coast have those leading zeros?

**Comment by giggsey** [comment]
Not sure. There is a 'leadingZeroPossible' property within the metadata, but that doesn't appear to be used for anything.

Otherwise, PhoneNumberUtil::setItalianLeadingZerosForPhoneNumber() is called at runtime to set it from the national number.

**Comment by giggsey** [comment]
Are you happy for this issue to now be closed?
