### ISSUE TITLE
New entry 26138 for Telma, Madagascar

### ISSUE THREAD

**Issue by IhariR** [giggsey/libphonenumber-for-php#499]
The Telma telco in Madagascar has since 2022 rolled out new numbers with prefix "38".
The array in \src\carrier\data\en\261.php should thus get new entry "26138 => 'Telma'":

return array (
  26132 => 'Orange',
  26133 => 'Airtel',
  26134 => 'Telma',
  26138 => 'Telma',
  26139 => 'Blueline',
);

**Comment by giggsey** [comment]
Thanks for the contribution.

However, this project does not accept changes for the data directly.

Please see the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for metadata issues.

**Comment by IhariR** [comment]
Understood; I’ll check the FAQ; thank you.

 

De : Joshua Gigg ***@***.*** 
Envoyé : jeudi 7 avril 2022 11:12
À : giggsey/libphonenumber-for-php
Cc : IhariR; Author
Objet : Re: [giggsey/libphonenumber-for-php] New entry 26138 for Telma, Madagascar (Issue #499)

 

Thanks for the contribution.

However, this project does not accept changes for the data directly.

Please see the FAQ <https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers>  for metadata issues.
