### ISSUE TITLE
Wrong Timezone Argentina

### ISSUE THREAD

**Issue by rossoman** [giggsey/libphonenumber-for-php#501]
Please change timezone America/Buenos_Aires to America/Argentina/Buenos_Aires

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers/metadata.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the timezone still shows as invalid.
