### ISSUE TITLE
Invalid international number

### ISSUE THREAD

**Issue by pistik1987** [giggsey/libphonenumber-for-php#505]
Hi,
I have a problem verifying international number
+4210944888777

https://giggsey.com/libphonenumber/?phonenumber=%2B4210944888777&country=SK&language=&region=
The result shows that it is valid, but the correct international format is +421944888777 without a leading zero after the international country code.

If I use formatting for the international format, the result is correct +421 944 888 777

So shouldn't the isValidNumber function return false?

Thanks.

**Comment by giggsey** [comment]
Hi,

The Google demo returns the same result: https://libphonenumber.appspot.com/phonenumberparser?number=%2B4210944888777&country=SK, so you'll need to raise an issue with them.

**Comment by giggsey** [comment]
Closing due to metadata issue.
