### ISSUE TITLE
Hungarian landline number validation fails

### ISSUE THREAD

**Issue by gabka913** [giggsey/libphonenumber-for-php#506]
I'm trying to parse and validate `+36 1 488 588` phone number. It fails despite that it is a valid hungarian landline number.
Also tried with online demo.
Can I somehow resolve this?

Thanks

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.

**Comment by giggsey** [comment]
Closing due to metadata issue.
