### ISSUE TITLE
Whatsapp format friendly

### ISSUE THREAD

**Issue by catalinux** [giggsey/libphonenumber-for-php#508]
According to their  their doc https://faq.whatsapp.com/general/chats/how-to-use-click-to-chat/?lang=en in order to use their chat links you need the following format.  

> Examples:
> 
> Use: https://wa.me/1XXXXXXXXXX
> 
> Don't use: https://wa.me/+001-(XXX)XXXXXXX
> 
> 

Can you tell me which format is this. As I can't figure out from these 

![image](https://user-images.githubusercontent.com/2072712/167890835-36384110-2bf2-489d-8aaf-1c4f9911bced.png)

**Comment by giggsey** [comment]
I just tried E164 with my mobile number, and it appeared to work

**Comment by catalinux** [comment]
I think It depends on the country code. For example  this phone numbers  has `+40741254459` according to https://giggsey.com/libphonenumber/index.php?phonenumber=%28741%29+254-459&country=RO&language=&region=

but this not work:
https://api.whatsapp.com/send?phone=+40741254459&text=&nbsp;

**Comment by giggsey** [comment]
Try getting rid of the leading +.

So https://api.whatsapp.com/send?phone=40741254459&text=

**Comment by catalinux** [comment]
I know. That would be hack :) , not a format from the is somehow "documented" by the librari.

**Comment by giggsey** [comment]
urlencode the E164 appears fine too: https://api.whatsapp.com/send?phone=%2B40741254459&text=I+love+libphonenumber

**Comment by catalinux** [comment]
You're perfectly right!
