### ISSUE TITLE
Different international format for dutch phone numbers

### ISSUE THREAD

**Issue by johanadivare** [giggsey/libphonenumber-for-php#518]
I have two phone numbers that have a different format when using `INTERNATIONAL` format:

https://libphonenumber.appspot.com/phonenumberparser?number=31208903099&country=NL 
https://libphonenumber.appspot.com/phonenumberparser?number=31223521234&country=NL

First phone number has 2 and then space `+31 xx xxx xxxx` (2/3/4) and second has 3 and then space `+31 xxx xxx xxx` (3/3/3) is there a reason for this difference?

**Comment by giggsey** [comment]
Hi,

You'll need to raise this with the parent libphonenumber project, rather than this PHP Port.
