### ISSUE TITLE
validate Chinese mobile number fail

### ISSUE THREAD

**Issue by soooldier** [giggsey/libphonenumber-for-php#52]
Hi~
    When i use this library to validate this number "18612249027ab" with region "CN". It seems that this number is a valid mobile number.But exactly it is a wrong mobile number, Chinese mobile does't contain letters.

ps: I am so sorry about my poor english : ) 

Best regards
Thanks very much

**Comment by giggsey** [comment]
Have a look at https://github.com/googlei18n/libphonenumber/issues/576

**Comment by giggsey** [comment]
@soooldier Are you happy for me to close this issue?

**Comment by giggsey** [comment]
Issue closed as no feedback from @soooldier.
