### ISSUE TITLE
Error on validating Dutch phone number

### ISSUE THREAD

**Issue by Florian-B** [giggsey/libphonenumber-for-php#522]
Hello,

We are using [libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php) on version `8.12.52` and we are experimenting an issue on dutch phone number validation.

The following phone number seems to be valid : `+31 88 222 1999`.

As stated on [https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Netherlands](https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Netherlands):

> 088 | Location independent, basic rate (for companies)

The library invalidate this phone number.

Thanks !

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.

**Comment by Florian-B** [comment]
Hi,

You will find links to both demos:

- https://giggsey.com/libphonenumber/index.php?phonenumber=%2B31+88+222+1999&country=&language=&region=
  - Region NL detected but isValidNumberForRegion() is false
- https://libphonenumber.appspot.com/phonenumberparser?number=%2B31+88+222+1999

Thanks

**Comment by giggsey** [comment]
You didn't specify a default region, so it's unable to check isValidNumberForRegion().

See:
 - https://giggsey.com/libphonenumber/index.php?phonenumber=%2B31+88+222+1999&country=NL&language=&region=
 - https://libphonenumber.appspot.com/phonenumberparser?number=%2B31+88+222+1999&country=NL

**Comment by Florian-B** [comment]
I just found the issue, we are using Symfony bundle [PhoneNumberBundle](https://github.com/odolbeau/phone-number-bundle) and we had implemented validation constraint with restriction by phone number type.

The issue is fixed ! Sorry 😢
