### ISSUE TITLE
Only validate Country Code

### ISSUE THREAD

**Issue by codetestmg** [giggsey/libphonenumber-for-php#523]
Thanks for this library.I have a situation where the request contains

```
{
"country_code":"+44",
"phone_number":"98765432101"
}
```
is it possible to validate only the country code without phone_number ?

**Comment by giggsey** [comment]
Are you trying to validate that the country code is valid (+44)?

If so, try [`getRegionCodesForCountryCode(44)`](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberUtil.md#getregioncodesforcountrycode), which will return an array of region codes.

**Comment by codetestmg** [comment]
@giggsey yes you are right.I wanted to validate +44.Thanks for mentioning the doc link. So if it returns an empty array then it will be an invalid country code.
