### ISSUE TITLE
Problem with version greater than 8.12.51, you get the country code twice

### ISSUE THREAD

**Issue by identityako** [giggsey/libphonenumber-for-php#527]
Problem with version greater than 8.12.51, you get the country code twice

Example: 
$phone= libphonenumber\PhoneNumberUtil::getInstance();
$phoneNumberObj = $phone->parse('4915777777777', strtoupper('DE'));

Result: 494915777777777

**Comment by giggsey** [comment]
Hi,

There have been issues reported in the past with German numbers appearing to show the double prefix at the start.

#318 and https://github.com/google/libphonenumber/blob/master/FAQ.md#why-wasnt-the-country-code-removed-when-parsing
