### ISSUE TITLE
Legit mobile number but false result

### ISSUE THREAD

**Issue by mlsg-gb** [giggsey/libphonenumber-for-php#530]
Hello, 

I have a mobile number that has been used for a long time. On top of that, I have verified it on https://libphonenumber.appspot.com/ and http://giggsey.com/libphonenumber/ and it is showing that it is a valid number but it is false for isValidNumberForRegion(). I also noticed that the getNumberType() is FIXED_LINE_OR_MOBILE instead of MOBILE. 

May I check how I can change this mobile number to MOBILE instead of FIXED_LINE_OR_MOBILE?
Thank you in advance!

![image](https://user-images.githubusercontent.com/112613714/187858891-7ceaa3c5-29d9-41d0-8305-c3c0b1999a4c.png)

**Comment by giggsey** [comment]
Are you trying to parse() the number passing in the region of IN? That's how isValidNumberForRegion() works.

As for FIXED_LINE_OR_NUMBER, you can try asking Google on their mailing list, or report an issue if you can find evidence the metadata is wrong.

**Comment by giggsey** [comment]
Closing as the question was answered on Google's mailing list
