### ISSUE TITLE
invalid numbers

### ISSUE THREAD

**Issue by mzaharov** [giggsey/libphonenumber-for-php#532]
Hi! I'm using your library for number validation, but there are numbers that don't validate. Here is a list of valid numbers, but they give a validation error

22353544471
85238729607
85216888054
85214455244
12780897004
12940011880
85218367847
12115783640
12755371873
85287372384
85217365637
85214759821
85215007249
85277044051
85232351064
85272167190
85271615399
85241505464
85217297419
12668366105
12141279554
12919828545
12811286804
12929316252
110756598501
85218723472

Can I somehow resolve this?

Thanks you!

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.
