### ISSUE TITLE
Missing Metadata

### ISSUE THREAD

**Issue by alin-rankingcoach** [giggsey/libphonenumber-for-php#538]
Version: 8.12.57 (latest atm)

`RuntimeException [ 0 ]: missing metadata: /var/www/live/application/vendor/giggsey/libphonenumber-for-php/src/data/PhoneNumberMetadata_it.php ~ APPPATH/vendor/giggsey/libphonenumber-for-php/src/MultiFileMetadataSourceImpl.php [ 95 ]`

Downgraded to 8.12.56 and there is no issue anymore.

**Comment by giggsey** [comment]
Can you provide more of a backtrace?

I'd be interested in how you are calling it? I'm wondering if you are passing in a region of 'it' (lowercase)

**Comment by alin-rankingcoach** [comment]
Yes, It seems that we were using lowercase and it's now case sensitive. 
I think this change of default behaviour might break a lot of projects that automatically update the library. 
Will fix this on our side anyway. Thank you!

**Comment by giggsey** [comment]
Can you share a code example so I can try to replicate it to avoid errors
in future releases?

**Comment by alin-rankingcoach** [comment]
Here we were just searching for a phone number in a text. 
`$phoneNumberMatcher = $phoneNumberUtil->findNumbers($text, $user->country_shortcode);`

Just use lowercase country codes instead of uppercase and it should give you the same error.
