### ISSUE TITLE
Reduce size of package

### ISSUE THREAD

**Issue by maxbaldanza** [giggsey/libphonenumber-for-php#539]
Hi,
I'm using this repo within an application that runs on Lambda and when we deploy we're hitting the Lambda max size.

```
An error occurred: ConsoleLambdaFunction - Resource handler returned message: "Code uncompressed size is greater than max allowed size of 272629760. (Service: Lambda, Status Code: 400, Request ID: 306ca182-b955-4455-a80b-2bde4f02ec8e)"
```
I've noticed that the geocoding folder is 14MB and it's not something we actually use within our project so ideally would like to remove it. I noticed that originally this was a separate repo and was then added back in here: https://github.com/giggsey/libphonenumber-for-php/issues/1

Is there a possibility of it being split out again or a way to exclude all the geolocation data when we install?

**Comment by giggsey** [comment]
Sorry, it's not something that is going to happen in the near future.

To split them out again would require a major version bump, as it's a backwards incompatible change.


I'd suggest some sort of bodge of removing the geocoding data directory as part of your build process.

**Comment by giggsey** [comment]
I wonder about creating a libphonenumber-for-php-lite package that only includes the main metadata (no geocoding, no timezone mapping)? It'd also provide people an alternative if they don't want giggsey/locale (#224)

**Comment by maxbaldanza** [comment]
That would be great 👍 We don't use the timezone mapping either so would really help 🙌 
Let me know if I can help in anyway

**Comment by giggsey** [comment]
Closing, as giggsey/libphonenumber-for-php-lite has been released.
