### ISSUE TITLE
Tests fail on HHVM

### ISSUE THREAD

**Issue by giggsey** [giggsey/libphonenumber-for-php#54]
From memory, this is an issue with the Regex used.

Need to write a simple testable script with a failing number

**Comment by joacub** [comment]
in php7 fail this

**Comment by giggsey** [comment]
@joacub What do you mean?

**Comment by joacub** [comment]
Fail macher regex expresion, return 502 error, the error not is manage

**Comment by giggsey** [comment]
@joacub Sorry, but this still doesn't make much sense.

Can you post a code sample that is causing an error, and the full error message you are getting.

**Comment by joacub** [comment]
The cose error is : 
    private function doMatch($type = 'find')
    {
        $final_pattern = '(?:' . $this->pattern . ')';
        switch ($type) {
            case 'matches':
                $final_pattern = '^' . $final_pattern . '$';
                break;
            case 'lookingAt':
                $final_pattern = '^' . $final_pattern;
                break;
            case 'find':
            default:
                // no changes	    
                break;
        }
        $final_pattern = '/' . $final_pattern . '/x';
        return (preg_match($final_pattern, $this->subject, $this->groups, PREG_OFFSET_CAPTURE) == 1) ? true : false;
    }

The php7 not response error, php7 crashed

**Comment by giggsey** [comment]
What functions are you calling that get to this function? What version of PHP are you running?

**Comment by joacub** [comment]
The php version is 7.0.1, test with This Number 6161217474 and in us locale

**Comment by giggsey** [comment]
I just upgraded the demo to support both PHP 5.6 and PHP7.

When trying your number in the PHP 7 demo, it works fine for me: http://libphonenumber-for-php.giggsey.net/?phonenumber=6161217474&country=US&language=&region= (the footer on the page shows the php version)

**Comment by joacub** [comment]
How to compile php7 ? With ppa or other

**Comment by giggsey** [comment]
I installed it using a ppa, but that's irrelevant to this library?

**Comment by joacub** [comment]
In ubuntu 15.10 is possibol pecl is corrupt or bad compile i dont now the problem but tente problem exist

**Comment by joacub** [comment]
this is system message kernel: [ 1808.603216] php-fpm7.0[1920]: segfault at 10 ip 00007fa07b10d2b7 sp 00007ffeddc7e690 error 4

**Comment by joacub** [comment]
the problem is library pcre, the version 8.35 in ubuntu 15.10 not run correctly, i have compile manual new version 8.37 and now perfectly regex

**Comment by giggsey** [comment]
I just tried running the unit tests on a local vagrant box (using hhvm version 3.10.1), and the tests passed fine.

Travis seems to be running hhvm version 3.6.6. So maybe this has actually been fixed in a recent travis version.

**Comment by giggsey** [comment]
Travis tests now use the latest HHVM version, so closing this issue.
