### ISSUE TITLE
libphonenumber-for-php-lite Package

### ISSUE THREAD

**Issue by giggsey** [giggsey/libphonenumber-for-php#540]
This is a planning issue for creating a libphonenumber-for-php-lite package.

**Aim**
Create a package that follows the same versioning, but has the core (and minimal) functionality.

**Components**
 - ✔️ [Phone Number Util](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberUtil.md)
 - ❓ [Short Number Info](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/ShortNumberInfo.md)
 - ❌ [As You Type Formatter](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/AsYouTypeFormatter.md)
 - ❌ [Phone Number Matcher](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberMatcher.md)
 - ❌ [Phone Number Offline Geocoder](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberOfflineGeocoder.md)
 - ❌ [Phone Number to Carrier Mapper](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberToCarrierMapper.md)
 - ❌ [Phone Number to Time Zones Mapper](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberToTimeZonesMapper.md)

**Questions**
 - Should we keep the same PHP version support? Or target 7.4 and above only with all the PHP related improvements (type hinting etc)
~80% of installs are PHP 7.4 and above. The main version of the library will still support PHP 5.3 until the next major release.
**Edit: The lite version will keep updating itself by only supporting supported PHP versions. As 7.4 goes EOL very soon, it'll only start with PHP 8**
![image](https://user-images.githubusercontent.com/305730/198310596-f42ddbbc-4f57-4e58-b7cd-a7c8bea34da6.png)

Related to #539, #224

**Comment by maxbaldanza** [comment]
> Should we keep the same PHP version support? Or target 7.4 and above only with all the PHP related improvements (type hinting etc)
~80% of installs are PHP 7.4 and above. The main version of the library will still support PHP 5.3 until the next major release.

I'm not a maintainer but if it was me then I'd personally only support supported PHP versions which as of next month would mean >=8

**Comment by giggsey** [comment]
https://packagist.org/packages/giggsey/libphonenumber-for-php-lite

I haven't tagged it, as I'm hoping to improve mutation testing. I'll tag it once Google release 8.13

Comparing zip sizes, the full version is 3MB, compared to 317KB for the lite version.

**Comment by alewolf** [comment]
I'm using the library in the [Pixel Manager for WooCommerce](https://wordpress.org/plugins/woocommerce-google-adwords-conversion-tracking-tag/). More than 50'000 WooCommerce shops use our plugin. 

WooCommerce minimum PHP requirement is PHP 7.2 and 7.4 is strongly recommended: https://woocommerce.com/document/update-php-wordpress/
