### ISSUE TITLE
Mobile code 600 for KG operator Beeline is not supported

### ISSUE THREAD

**Issue by pavlun** [giggsey/libphonenumber-for-php#544]
Please make update and add code 600 for KG operator Beeline. Thanks,

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.
