### ISSUE TITLE
Can't get region for this number

### ISSUE THREAD

**Issue by eskie-aloware** [giggsey/libphonenumber-for-php#547]
Just input an AU number
https://giggsey.com/libphonenumber/?phonenumber=%2B61483901111&country=AU&language=&region=

but we cant get the region code for it

**Comment by giggsey** [comment]
Have you tried with a valid number? The demo is reporting that this number is invalid.

**Comment by eskie-aloware** [comment]
we got that number from twilio.. i just changed the last 4 numbers

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.

**Comment by eskie-aloware** [comment]
Thank you for replying.. It seems that there is a problem on twilio.. we already sent a message to them..

**Comment by giggsey** [comment]
Closing this issue as it was handled via the mailing list
