### ISSUE TITLE
Latest releases stop parsing some phone numbers

### ISSUE THREAD

**Issue by KiPa187** [giggsey/libphonenumber-for-php#549]
Hey there!
We have updated to the latest version and got issues with some phone numbers.
For example, CI phone numbers (+225)
You can check it on 22558583937
\libphonenumber\PhoneNumberUtil::isPossibleNumber() returns false, but phone is correct and it's works on 8.12.17 version.

**Comment by giggsey** [comment]
Hi,

Does the number work on the Google demo? If so, please see the FAQ about invalid numbers
