### ISSUE TITLE
Missing 07 as valid prefix for french mobile lines

### ISSUE THREAD

**Issue by selossevianney** [giggsey/libphonenumber-for-php#55]
Hello,

I would like to add the 07 prefix for french mobile lines but I don't know which file I have to modify. Can you, please, tell me what I have to do?

Thx.

selosse vianney

**Comment by giggsey** [comment]
Hi,

The project uses metadata that is part of the parent [libphonenumber](https://github.com/googlei18n/libphonenumber) project that is managed by Google.

If you think there is a metadata issue, can you report it to them. Once they release any new versions, this package will update and release a new version.


I did search for French 07 issues, and I found https://github.com/googlei18n/libphonenumber/issues/500 - does this help?

**Comment by selossevianney** [comment]
Yeah that helped. Thank you.

It seemed that I was testing  07 number that was not french.

2015-03-05 12:05 GMT+01:00 Joshua Gigg <notifications@github.com>:

> Closed #55 <https://github.com/giggsey/libphonenumber-for-php/issues/55>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giggsey/libphonenumber-for-php/issues/55#event-246685377>
> .
>



-- 
SELOSSE Vianney

Élève ingénieur 5ème année
Ecole Polytech'Nice Sophia

Tel : *06/19/83/21/66*
adresse : 9 rue jean du vivier
59710 Avelin

**Comment by pham01** [comment]
Hello,

I tried with a 07 mobile phone number but it's not working 
https://giggsey.com/libphonenumber/index.php

isValidNumber is false but in the metadata we have 6 or 7 : 
`'mobile' => 
  array (
    'NationalNumberPattern' => '(?:6\\d\\d|7(?:00|[3-9]\\d))\\d{6}',
    'ExampleNumber' => '612345678',
    'PossibleLength' => 
    array (
    ),
    'PossibleLengthLocalOnly' => 
    array (
    ),
  ),

Do you have an issue for that ?
Thx :)`

**Comment by pham01** [comment]
@giggsey Yes I have the same, so it's a google problem ?

**Comment by giggsey** [comment]
@pham01 Possibly. Take a look at [Google's Issue Reporting Guide](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue) for instructions on raising an issue with them.

**Comment by pham01** [comment]
@giggsey Ok thank you 
I saw with them, it works with only valid 07 phone number (french) and I'd tried with a random number 07 with a good format but not exist.
