### ISSUE TITLE
french phone numbers for exemple 0696811359 doesn't work

### ISSUE THREAD

**Issue by shooter1985** [giggsey/libphonenumber-for-php#554]
all french phone numbers like 069[numbers] fails

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.
