### ISSUE TITLE
support 04 prefix for MTN Irancell in Iran

### ISSUE THREAD

**Issue by sajadshouli** [giggsey/libphonenumber-for-php#558]
the package throw exception for these numbers in `isValid()`, `formatE164()` , `formatNational`  functions in `propaganistas/laravel-phone`

```
+98 9 04 000 0000
0098 9 04 000 0000
98 9 04 000 0000
0 9 04 000 0000
```
Since many people in Iran have this phone number format, please change the validation support 04 prefix

Wikipedia source: https://en.wikipedia.org/wiki/Telephone_numbers_in_Iran

![image](https://user-images.githubusercontent.com/80545265/219872914-ca2495e1-7ddf-4495-94c1-3414a5c674ae.png)

the Irancell website that you can buy number with 04 prefix:

Irancell website: https://shop.irancell.ir/en/sim-search

![image](https://user-images.githubusercontent.com/80545265/219873043-916afbf8-08f8-4489-bb1d-cf99699f646b.png)

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.
