### ISSUE TITLE
Replace phone numbers in big text

### ISSUE THREAD

**Issue by Pok4** [giggsey/libphonenumber-for-php#559]
Hello,
Im from Bulgaria and i try to replace phone numbers in specific long text.
The matcher function is OK, everything works, but i want to replace finded phone numbers with specific one (only one)

Ok, some examples

> 
> на имота. Моля, кажете, че сте видeли обявата в този сайт.
> Референтен номер: LXH-101061
> Тел: 0882 404 029, 056 706 331
> Отговорен брокер:Станислав Андреев
> Без комисиона от купувача

The problem is about matcher function.. This:
$phoneNumberMatch->number()->getNationalNumber()

only returns 882404029 and 56706331 and i cant use str_replace to directly replace the phones in text..
I want to have exact phones in matcher function with "0" included in front on phones. (some of the phones have +359 in front of them) Maybe i can remove 0 on the phone which i want to replace original ones... But for now i need your help about replace function..

Here is my code:
```
	  $phoneNumberMatcher = $phoneNumberUtil->findNumbers($description, 'BG');
	  foreach ($phoneNumberMatcher as $phoneNumberMatch) {
		$description = str_replace($phoneNumberMatch->number()->getNationalNumber(),$phone_maca,$description);
	  }
```

Please, give me advice how to do it...

**Comment by Pok4** [comment]
For now i do this:
`$description = preg_replace("/([\s".$phoneNumberMatch->number()->getNationalNumber()."]{7,}+)/",' '.$phone_maca.' ',$description);`
it works for now, but i think that there is better solution..

**Comment by giggsey** [comment]
There is a rawString() method on the PhoneNumberMatch object, would that help?
