### ISSUE TITLE
form default_region

### ISSUE THREAD

**Issue by selossevianney** [giggsey/libphonenumber-for-php#56]
Hi there,

I have a form and I wonder how(if it's possible) can I get the country code corresponding to the given phone number? Because today a belgian guy filled my form with his belgian mobile phone number and it seemed that belgian mobile phones and french fixed lines are alike. I know that in this case it would be hard to get the right country code but before today, only french guys filled my form and soon it will be belgian and swiss people that will fill my form and maybe others in the future, so, Can I get the country code to the given number and How?

Thank you guys!

**Comment by giggsey** [comment]
The library needs to know which country the number supplied is part of (like you said, numbers can look the same in multiple countries).

So you either need to ask the user, or take a guess yourself.

**Comment by selossevianney** [comment]
Thank you for your quick answer. And yeah, I was afraid of your answer. Sorry to ask but in the form, if I don't specify the default_region or if I specify it to PhoneNumberUtil::UNKNOWN_REGION it doesn't work, so, what do I have to do to get phone numbers coming from all over the world ?

**Comment by giggsey** [comment]
You can set the region to 'ZZ' when using `parse()`.

**Comment by selossevianney** [comment]
I'll try it. Thanks for your time.

**Comment by giggsey** [comment]
@selossevianney Any luck?

Can I close this issue?

**Comment by selossevianney** [comment]
Sorry, yes you can. Thanks.

2015-03-26 11:39 GMT+01:00 Joshua Gigg <notifications@github.com>:

> @selossevianney <https://github.com/selossevianney> Any luck?
>
> Can I close this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giggsey/libphonenumber-for-php/issues/56#issuecomment-86446194>
> .
>



-- 
SELOSSE Vianney

Élève ingénieur 5ème année
Ecole Polytech'Nice Sophia

Tel : *06/19/83/21/66*
adresse : 9 rue jean du vivier
59710 Avelin

**Comment by selossevianney** [comment]
You took all my pain away :).

2015-03-26 11:42 GMT+01:00 Vianney Selosse <selossevianney@gmail.com>:

> Sorry, yes you can. Thanks.
>
> 2015-03-26 11:39 GMT+01:00 Joshua Gigg <notifications@github.com>:
>
>> @selossevianney <https://github.com/selossevianney> Any luck?
>>
>> Can I close this issue?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/giggsey/libphonenumber-for-php/issues/56#issuecomment-86446194>
>> .
>>
>
>
>
> --
> SELOSSE Vianney
>
> Élève ingénieur 5ème année
> Ecole Polytech'Nice Sophia
>
> Tel : *06/19/83/21/66*
> adresse : 9 rue jean du vivier
> 59710 Avelin
>



-- 
SELOSSE Vianney

Élève ingénieur 5ème année
Ecole Polytech'Nice Sophia

Tel : *06/19/83/21/66*
adresse : 9 rue jean du vivier
59710 Avelin
