### ISSUE TITLE
Different result vs Google Demo

### ISSUE THREAD

**Issue by ConstantinLuta** [giggsey/libphonenumber-for-php#563]
Google's Online Demo - https://libphonenumber.appspot.com - gives a different result to the libphonenumber-for-php demo for number +40792744201

<img width="535" alt="Screenshot 2023-03-14 at 10 01 45" src="https://user-images.githubusercontent.com/3023719/224934310-d9c1a52b-4ac9-4d45-b325-68310ce5e3cf.png">

VS

<img width="351" alt="Screenshot 2023-03-14 at 10 03 29" src="https://user-images.githubusercontent.com/3023719/224934874-5e94510e-455b-4a56-a9fe-08ed71368c33.png">

**Comment by giggsey** [comment]
Apologies, the demo was running an older version. It's been updated, and now shows that number as valid.

The footer of the demo shows the version it's running
