### ISSUE TITLE
Platform dependencies incompatible with oldest php version 

### ISSUE THREAD

**Issue by kinouzero** [giggsey/libphonenumber-for-php#575]
Hi,

I've this error on a website where I used your project 

`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.0". You are running 5.4.45. in /var/www/domyks/vendor/composer/platform_check.php on line 25`

I need this to run on php 5.4, but your `Locale` dependencies required php 7.2 in the composer.json so the retrocompatibility doesn't work.

Thanks

**Comment by giggsey** [comment]
giggsey/locale v1 supports PHP 5.x. https://github.com/giggsey/libphonenumber-for-php/blob/master/composer.json#L63 shows that this library supports both versions of locale.

My guess is you ran composer update on a box that had 7.2+, then copied the files to a PHP 5.4 host?

**Comment by kinouzero** [comment]
Good point, I work in a docker container running in 5.4 but in my laptop on local I run 7.4 and I ran composer install locally.

Thanks
