### ISSUE TITLE
Problem with trimming zeros 

### ISSUE THREAD

**Issue by murat11** [giggsey/libphonenumber-for-php#578]
Many phone numbers have leading zeros after the country code. Ivory Coast for example  https://www.wikiwand.com/en/Telephone_numbers_in_Ivory_Coast 

But this code removes it from resulting number
https://github.com/giggsey/libphonenumber-for-php/blob/218caeeeb224bf2f553597b5c3a1647ff936db64/src/PhoneNumberUtil.php#L1799

**Comment by giggsey** [comment]
Doesn't
static::setItalianLeadingZerosForPhoneNumber($normalizedNationalNumber,
$phoneNumber); deal with that?

**Comment by murat11** [comment]
As I can see it does not work. Maybe that util instance must be configured in some special way
![image](https://github.com/giggsey/libphonenumber-for-php/assets/10486500/84f88988-a943-401b-8bb4-d13c9f552de5)

**Comment by giggsey** [comment]
Doesn't that debug show it working?

The `$phoneNumber` object has `italianLeadingZero` set to true, and the `numberOfItalianZeros` is set to 1.
