### ISSUE TITLE
Unverifiable Turkey Number 

### ISSUE THREAD

**Issue by mrkemaltas** [giggsey/libphonenumber-for-php#579]
+90550xxxxxx is currently used in Turkey , but when I run the function below, numbers starting with 550 are not validated.

 $phoneNumber = $phoneUtil->parse($value, $this->country_code);

 if (!$phoneUtil->isValidNumberForRegion($phoneNumber, $this->country_code)) {
    $fail(__('auth.phone_invalid'));
 }

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.
