### ISSUE TITLE
Mobile type format for MD region

### ISSUE THREAD

**Issue by ruscon** [giggsey/libphonenumber-for-php#59]
version
"giggsey/libphonenumber-for-php":"7.0.2"

http://giggsey.com/libphonenumber/?phonenumber=%2B373+68+111+111&country=MD&language=&region=MD
show (it's mobile type)
+373 681 11 111

must be formatted as: +373 68 111 111

For local (landline) phonenumber - all good
http://giggsey.com/libphonenumber/?phonenumber=%2B373%2022%20111%20111&country=MD&language=&region=MD

you can see formats in wiki
https://en.wikipedia.org/wiki/Telephone_numbers_in_Moldova

```
0-xx-xx-xx-xx call between localities and mobile phone companies
+373-xx-xx-xx-xx call to Moldova from abroad
```

similar discussion https://github.com/googlei18n/libphonenumber/issues/632

**Comment by giggsey** [comment]
As Google's demo is also providing the same result as the PHP version, I'm going to close this issue, as it's not an issue with the PHP port.

If googlei18n/libphonenumber#632 results in a metadata update, this project will pick up on that in the next release.
