### ISSUE TITLE
Issue with symfony/console:6.0

### ISSUE THREAD

**Issue by fatemejudy** [giggsey/libphonenumber-for-php#590]
I want to upgrade Laravel version from 8.67.0 to 9.0, and as it said in the [Upgrade Guide](https://laravel.com/docs/9.x/upgrade), I should upgrade `nunomaduro/collision` to version 6.1 and it requires `symfony/console:6.0`.
But the latest version of this package does not support `symfony/console:6.0` and  I have a conflict with this package! 

my error message:
`laravel/framework v9.0.0 requires symfony/console ^6.0 -> found symfony/console[v6.0.0-BETA1, ..., 6.3.x-dev] but these were not loaded, likely because it conflicts with another require.`

**Comment by giggsey** [comment]
`symfony/console` is only a dev dependency in this project, so it won't impact your project when you are requiring libphonenumber-for-php.

The conflict must be coming from another library. `composer why symfony/console` might help

I've used this library with all versions of Laravel with no issues.

**Comment by fatemejudy** [comment]
Yes, you were right and that command helped me. Thanks
