### ISSUE TITLE
Missed Tagged Phone Number as Invalid

### ISSUE THREAD

**Issue by yhael-aloware** [giggsey/libphonenumber-for-php#591]
We noticed that this package has issues validating a US number `+161411439768`.

We had to bypass this valid number in our app.

Please add it / fix the logic for it to pass validation since the current version can't handle it correctly.

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.
