### ISSUE TITLE
is there a method to get back the region/iso string for a given number?

### ISSUE THREAD

**Issue by victusfate** [giggsey/libphonenumber-for-php#594]
something like
```
$number = '+16315555555';
$phoneUtil = PhoneNumberUtil::getInstance();
$numberProto = $phoneUtil->parse($number);
echo $numberProto->getISOCode();
# prints US
```

**Comment by giggsey** [comment]
https://giggsey.github.io/libphonenumber-for-php/docs/PhoneNumberUtil.html#getregioncodefornumber ?

**Comment by victusfate** [comment]
❤️

**Comment by victusfate** [comment]
just a heads up its coming back null in this example
```
$number = '+4407700900000';
$phoneUtil = PhoneNumberUtil::getInstance();
$numberProto = $phoneUtil->parse($number);
echo $phoneUtil->getRegionCodeForNumber($numberProto);
```

should I call another method to set the country code first?

**Comment by giggsey** [comment]
That's not a valid GB number. Get rid of the leading zero (+447...)

**Comment by victusfate** [comment]
Oh isn't that the E164 version ?

**Comment by giggsey** [comment]
I'd suggest using the demo:
https://giggsey.com/libphonenumber/?phonenumber=%2B447700900000&country=&language=&region=

This number is still invalid, so there is no region for it.

**Comment by victusfate** [comment]
thanks, appreciate the help!
