### ISSUE TITLE
Incorrectly validates inputs such as +1510ABC-DEFG

### ISSUE THREAD

**Issue by AsankaL** [giggsey/libphonenumber-for-php#595]
Why this lib mark input like +1510ABC-DEFG as a valid phone number?

```
        $phoneUtil = PhoneNumberUtil::getInstance();
        $result = $phoneUtil->parse('+1510ABC-DEFG');
        var_dump($phoneUtil->isValidNumber($result)); // output is true
```

**Comment by giggsey** [comment]
Letters are converted to their equivalent numbers, based on the telephony
keypad.

See https://en.wikipedia.org/wiki/Phoneword for details.
