### ISSUE TITLE
Fatal error: Uncaught Error type: 1. The string supplied did not seem to be a phone number.

### ISSUE THREAD

**Issue by tree28** [giggsey/libphonenumber-for-php#601]
An Observation- 
When testing a number from the wild uncaught errors can stop processes when numbers do not confirm, which can often be true from numbers entered from the wild.

The number supplied was: 1
0 also produces the error.

An Edit-
It appears that single digit numbers provide the error. I have only tested 0 1 2 3.

The error–
Fatal error: Uncaught Error type: 1. The string supplied did not seem to be a phone number. thrown in /var/www/vendor/giggsey/libphonenumber-for-php/src/PhoneNumberUtil.php on line 1673

**Comment by giggsey** [comment]
Closing in favour of #602
