### ISSUE TITLE
Fatal Error: Uncaught Error type: 4. The string supplied is too long

### ISSUE THREAD

**Issue by tree28** [giggsey/libphonenumber-for-php#602]
An Observation–
Numbers from the wild that are too long cause uncaught fatal errors.

The number supplied was: 111111111111111111111

The error–
Fatal error: Uncaught Error type: 4. The string supplied is too long to be a phone number. thrown in /var/www/vendor/giggsey/libphonenumber-for-php/src/PhoneNumberUtil.php on line 1783

**Comment by giggsey** [comment]
I'm going to reply to one of these issues, not both, as they are both the same.

As with your previous issue, you should be catching the NumberParseException that is thrown if obviously invalid content is passed into parse().

In your use case, it might be worth also trying [`isPossibleNumber()`](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberUtil.md#ispossiblenumber) first, although you'll still need to pass a region in so it can try to parse it internally.

Your best strategy would be to catch the exceptions, and reject those numbers
