### ISSUE TITLE
Some phone numbers from brazil are not recognized (UNKNOWN phone type)

### ISSUE THREAD

**Issue by lazychaser** [giggsey/libphonenumber-for-php#604]
+558198595959
+558195033540

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.
