### ISSUE TITLE
Prefixes for Benin are not correct

### ISSUE THREAD

**Issue by agossouvi** [giggsey/libphonenumber-for-php#607]
According to this : https://fr.wikipedia.org/wiki/Liste_des_indicatifs_t%C3%A9l%C3%A9phoniques_au_B%C3%A9nin  prefixes used by libphonenumber-for-php are not correct. 

Please check.

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.
