### ISSUE TITLE
PhoneNumberUtil::parseAndKeepRawInput doesn't behave like the JS version

### ISSUE THREAD

**Issue by patheticcockroach** [giggsey/libphonenumber-for-php#61]
Hi,

First thank you for this nice port from the original JS library to PHP.

A great thing in the original version was the ability to process a phone number without knowing the region. I'm quite new to the PHP version, but as far as I understood, it aims at reproducing the behavior of JS version.
In the JS version ([demo here] (https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html)), PhoneNumberUtil.parseAndKeepRawInput(phoneNumber, regionCode) can be invoked with a missing/empty regionCode. In this PHP port, it terminates with an exception "Missing or invalid default region".

I browsed the code a bit and found that PhoneNumberUtil::parseAndKeepRawInput() calls PhoneNumberUtil::parseHelper() with $checkRegion parameter set to true (line 1330). Changing this to false fixes the exception, but then the library still isn't able to process the number. For instance, +33655442211 is properly identified as French mobile number by the JS version, but not processed by the PHP version.

I assume it's something not yet implemented, but just in case it's a bug I thought I'd post about it here.

**Comment by giggsey** [comment]
This library is actually a port of the Java version, not the JavaScript.

In the Java version, the function `parseAndKeepRawInput` matches the PHP. I also tried the JS demo, and it didn't allow me to submit the form without a defaultRegion.

I'll submit an issue to googlei18n/libphonenumber, and see if the Java version is meant to do it.

**Comment by lutzissler** [comment]
To fulfill patheticcockroach’s use case, why not submit any code as default region (valid or not, as long as it’s not empty)? The result of `getRegionCodeForNumber()` will be the region code determined from the phone number anyway.

**Comment by patheticcockroach** [comment]
Hi,
Thanks. Yes indeed, in my use case it turned out a programmer messed up pre-processing and added code to remove the leading "+" in the E164 phone number. Keeping the "+" and setting the second argument to null just works fine.

**Comment by giggsey** [comment]
Closing this issue for now.

If Google change the Java API, I'll update this PHP version.
