### ISSUE TITLE
PHP 8.1: Serializable interface deprecated

### ISSUE THREAD

**Issue by yasanov** [giggsey/libphonenumber-for-php#613]
PHP Deprecated Warning – yii\base\ErrorException

libphonenumber\PhoneNumber implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary).

In PHP 8.1 Serializable interface deprecated and it will be removed starting with PHP 9

**Comment by giggsey** [comment]
As this library still supports PHP 5.3, we need to support both methods.

PHP 8.1+ is covered by __serialize(): https://github.com/giggsey/libphonenumber-for-php/blob/master/src/PhoneNumber.php#L560-L603
