### ISSUE TITLE
Invalid numbers 000-000-0000 and 000-000-0001 for US are shown as valid by isPossibleNumber

### ISSUE THREAD

**Issue by mschroebel** [giggsey/libphonenumber-for-php#615]
People enter 000-000-0000, 000-000-0000 and similar numbers when they do not want to provide a telephone number.

Your fantastic tool returns these as possible numbers as 01 and 11. They are not valid numbers. Dialing 0 (used to at least) get you to a telephone operator.

Output from script below:
000-000-0000 01 1
0000000000   01 1
000-000-0001 11 1
0000000001   11 1

$phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
$num = '000-000-0000';
echo $num . " ";
$phone_num = $phoneUtil->parse($num, 'US');
echo $phone_num->getNationalNumber() . "";
echo $phoneUtil->isPossibleNumber($phone_num) . " ";
echo $phoneUtil->isPossibleNumber($num, 'US') . "\n";

$num = '0000000000';
echo $num . " ";
$phone_num = $phoneUtil->parse($num, 'US');
echo $phone_num->getNationalNumber() . "";
echo $phoneUtil->isPossibleNumber($phone_num) . " ";
echo $phoneUtil->isPossibleNumber($num, 'US') . "\n";

$num = '000-000-0001';
echo $num . " ";
$phone_num = $phoneUtil->parse($num, 'US');
echo $phone_num->getNationalNumber() . "";
echo $phoneUtil->isPossibleNumber($phone_num) . " ";
echo $phoneUtil->isPossibleNumber($num, 'US') . "\n";

$num = '0000000001';
echo $num . " ";
$phone_num = $phoneUtil->parse($num, 'US');
echo $phone_num->getNationalNumber() . "";
echo $phoneUtil->isPossibleNumber($phone_num) . " ";
echo $phoneUtil->isPossibleNumber($num, 'US') . "\n";

**Comment by giggsey** [comment]
Hi,

`isPossibleNumber()` does a very basic check to see if the number could potentially be valid. It does by checking that the input are digits, and that is is the right length for a number.

You should use `isValidNumber()` to do a proper check.
