### ISSUE TITLE
US phone being validated as a BR phone

### ISSUE THREAD

**Issue by henriquemoody** [giggsey/libphonenumber-for-php#621]
Hi there,

When parsing the phone number `+1 650 253 00 00` with the default region `BR`, I was expecting that either `parse` would throw an exception or that `PhoneNumberUtil::isValidNumber` would consider the phone as invalid.
```php
$phoneNumberUtil = \libphonenumber\PhoneNumberUtil::getInstance();
$phoneNumberObject = $phoneNumberUtil->parse('+1 650 253 00 00', 'BR');

var_dump($phoneNumberUtil->getRegionCodeForNumber($phoneNumberObject));
// string(2) "US"

var_dump($phoneNumberUtil->isValidNumber($phoneNumberObject));
// bool(true)
```

Am I missing anything?

**Comment by giggsey** [comment]
You hit the nail on the head with the use of 'default region'.

parse() will use that to try to parse your number, but as you provided the input in E164, it's able to work out the correct region from that instead.

To check, you can compare the regions like you have in the linked commits, or use [isValidNumberForRegion()](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberUtil.md#isvalidnumberforregion).

I'd also recommend running [isValidNumber()](https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberUtil.md#isvalidnumber), as parse() will allow possible numbers too.

**Comment by henriquemoody** [comment]
I missed the `isValidNumberForRegion()`, that's good to know!

Thanks for the quick reply!
