### ISSUE TITLE
French mobile number starting with 07

### ISSUE THREAD

**Issue by LaRepDuClic** [giggsey/libphonenumber-for-php#623]
It appears the new french mobile number ("new" since 2010) are not taken into account ?

in src/data/PhoneNumberMetadata_FR.php, line 39

`'NationalNumberPattern' => '(?:6(?:[0-24-8]\\d|3[0-8]|9[589])|7[3-9]\\d)\\d{6}',`

**Comment by giggsey** [comment]
Hi,

Please check the FAQ regarding invalid numbers

**Comment by LaRepDuClic** [comment]
OK. I didn't know certain rules about the mobile numbers. Thanks.
