### ISSUE TITLE
How make early detection of invalid number?

### ISSUE THREAD

**Issue by mistercz** [giggsey/libphonenumber-for-php#63]
isPossibleNumberWithReason returns true for number +420999999999. But isValidNumberForRegion returns false... I'm wondering how to detect invalid number during typing... If user enter "+420999" it should be marked as invalid.... how to do it ?

Thank you very much!

**Comment by giggsey** [comment]
You would need the As You Type Formatter, which I believe has validation too.

We don't support that this PHP Port (because you wouldn't be typing character by character into a PHP script).

**Comment by mistercz** [comment]
You can do checks via ajax PHP service. So there are situations where this feature could be useful. Thank  you

**Comment by giggsey** [comment]
True, but you would be better off assisting the user via front-end JavaScript, and doing validation at the end of input.

If you have 50ms latency between each key press (assuming the client's Internet connection to the server is quick, the script is quick etc.), it's not going to give a very good user experience.
