### ISSUE TITLE
Iraq Metadata Update

### ISSUE THREAD

**Issue by akamomer** [giggsey/libphonenumber-for-php#630]
Hello Team,

Below is correct data for Iraq:
return array (
    96473 => 'ITPC',
    9647400 => 'Itisaluna',
    9647401 => 'Itisaluna',
    9647435 => 'Kalimat',
    9647444 => 'Mobitel',
    9647480 => 'ITC Fanoos',
    9647481 => 'ITC Fanoos',
    9647491 => 'ITPC',
    9647494 => 'Imam Hussien Holy Shrine',
    9647495 => 'IraqTel',
    9647496 => 'IraqTel',
    9647500 => 'Korek',
    9647501 => 'Korek',
    9647502 => 'Korek',
    9647503 => 'Korek',
    9647504 => 'Korek',
    9647505 => 'Korek',
    9647506 => 'Korek',
    9647507 => 'Korek',
    9647508 => 'Korek',
    9647509 => 'Korek',
    9647510 => 'Korek',
    9647511 => 'Korek',
    9647512 => 'Korek',
    9647513 => 'Korek',
    9647514 => 'Korek',
    9647515 => 'Korek',
    9647516 => 'Korek',
    9647700 => 'Asiacell',
    9647701 => 'Asiacell',
    9647702 => 'Asiacell',
    9647703 => 'Asiacell',
    9647704 => 'Asiacell',
    9647705 => 'Asiacell',
    9647706 => 'Asiacell',
    9647707 => 'Asiacell',
    9647708 => 'Asiacell',
    9647709 => 'Asiacell',
    9647710 => 'Asiacell',
    9647711 => 'Asiacell',
    9647712 => 'Asiacell',
    9647713 => 'Asiacell',
    9647714 => 'Asiacell',
    9647715 => 'Asiacell',
    9647716 => 'Asiacell',
    9647717 => 'Asiacell',
    9647718 => 'Asiacell',
    9647719 => 'Asiacell',
    9647720 => 'Asiacell',
    9647721 => 'Asiacell',
    9647722 => 'Asiacell',
    9647723 => 'Asiacell',
    9647724 => 'Asiacell',
    9647725 => 'Asiacell',
    9647726 => 'Asiacell',
    9647727 => 'Asiacell',
    9647728 => 'Asiacell',
    9647729 => 'Asiacell',
    9647730 => 'Asiacell',
    9647731 => 'Asiacell',
    9647732 => 'Asiacell',
    9647733 => 'Asiacell',
    9647734 => 'Asiacell',
    9647735 => 'Asiacell',
    9647736 => 'Asiacell',
    9647800 => 'Zain',
    9647801 => 'Zain',
    9647802 => 'Zain',
    9647803 => 'Zain',
    9647804 => 'Zain',
    9647805 => 'Zain',
    9647806 => 'Zain',
    9647807 => 'Zain',
    9647808 => 'Zain',
    9647809 => 'Zain',
    9647810 => 'Zain',
    9647811 => 'Zain',
    9647812 => 'Zain',
    9647813 => 'Zain',
    9647814 => 'Zain',
    9647815 => 'Zain',
    9647816 => 'Zain',
    9647817 => 'Zain',
    9647818 => 'Zain',
    9647819 => 'Zain',
    9647820 => 'Zain',
    9647821 => 'Zain',
    9647822 => 'Zain',
    9647823 => 'Zain',
    9647824 => 'Zain',
    9647825 => 'Zain',
    9647826 => 'Zain',
    9647827 => 'Zain',
    9647828 => 'Zain',
    9647829 => 'Zain',
    9647830 => 'Zain',
    9647831 => 'Zain',
    9647832 => 'Zain',
    9647833 => 'Zain',
    9647834 => 'Zain',
    9647835 => 'Zain',
    9647901 => 'Zain',
    9647902 => 'Zain',
    9647903 => 'Zain',
    9647904 => 'Zain',
    9647905 => 'Zain',
    9647906 => 'Zain',
);

File: https://github.com/giggsey/libphonenumber-for-php/blob/9ca4179e4332d21578cb29f0c0406f0a2b8803e3/src/carrier/data/en/964.php

Reference: https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000670001MSWE.docx

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers or metadata.
