### ISSUE TITLE
Vietnamese number not validating

### ISSUE THREAD

**Issue by FireyFly89** [giggsey/libphonenumber-for-php#633]
We've got a Vietnamese client who cannot enter their phone number: (**1644697xxx**) I've tried validating it with the laravel-phone library, where it said to test it on the giggsey website if it validates, and it indeed **does not validate**.

Is this an actual error in the validator for Vietnamese numbers? I'm honestly not sure.

![image_2024-05-30_160758418](https://github.com/giggsey/libphonenumber-for-php/assets/26187644/9db9c01a-d95f-49ed-b56f-1a4636da8f5b)

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.
