### ISSUE TITLE
Area code 350 is not being accepted

### ISSUE THREAD

**Issue by sociribeiro** [giggsey/libphonenumber-for-php#642]
**Creation**: Area code 350 was put into service on November 28, 2022 and was the 445th area code in service. It was one of 19 area codes introduced in 2022. It was the 37th area code in the state of California. California currently has 38 area codes. It was created to relieve the pressure on [the 209 area code](https://www.allareacodes.com/209) as the numbers in 209 were being exhausted.

![Screenshot 2024-07-26 at 11 08 20](https://github.com/user-attachments/assets/1986fcea-9e14-416a-980a-da99a75b3815)

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.
