### ISSUE TITLE
Prefix for BENIN

### ISSUE THREAD

**Issue by agossouvi** [giggsey/libphonenumber-for-php#647]
There are many errors in the Benin numbering plan... and the prefixes do not match at all. 

https://fr.wikipedia.org/wiki/Liste_des_indicatifs_t%C3%A9l%C3%A9phoniques_au_B%C3%A9nin

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.

**Comment by kirilinko** [comment]
At the moment, I don't think there's any problem, because Benin hasn't yet switched to 01 for its current telephone numbers. But from November, I think it will be applied and could create errors. I use it without error. When do you get errors?
