### ISSUE TITLE
Some valid German numbers seem to be returned as invalid. 

### ISSUE THREAD

**Issue by afcamps** [giggsey/libphonenumber-for-php#656]
Sorry about RGPD compliance, 

We have had issues with valid numbers under other external controls. 

This number is invalid in the  version `>=8.13.43`.

eg:  +4915253846891

https://www.ipqualityscore.com/reverse-phone-number-lookup/lookup/DE/4915253846891

**Comment by giggsey** [comment]
Hi,

That number validates on both the Google and PHP demo pages:
 - https://giggsey.com/libphonenumber/?phonenumber=%2B4915253846891&country=&language=&region=
 - https://libphonenumber.appspot.com/phonenumberparser?number=%2B4915253846891

**Comment by afcamps** [comment]
Hi @giggsey, 

Thanks for your quick reply,
My bad, I copied the wrong number.

https://www.ipqualityscore.com/reverse-phone-number-lookup/lookup/DE/1765992346

In version `v8.13.42`
![image](https://github.com/user-attachments/assets/a05cbbb3-291d-4935-85d4-8dae716518b2)

In `master`
![image](https://github.com/user-attachments/assets/964d7608-1a68-434e-b620-5272279fae91)

**Comment by giggsey** [comment]
Google's demo is reporting it as invalid: https://libphonenumber.appspot.com/phonenumberparser?number=01+765992346&country=DE

Check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers. You should report the issue to them.

**Comment by afcamps** [comment]
Thanks for your time,

I've seen the google lib results, I'll dig into that.
Sorry I missed the FAQ section. 

I'm closing this issue.
