### ISSUE TITLE
A way to get area/carrier code and phone number by themselves

### ISSUE THREAD

**Issue by ArtemGordinsky** [giggsey/libphonenumber-for-php#66]
Hi,
There is ```\libphonenumber\PhoneNumber::getCountryCode()``` for retrieving country codes, but no such methods for area/carrier code or the number itself (without country and carrier codes). Are there any other ways to accomplish that?

**Comment by giggsey** [comment]
Have a look at [getLengthOfGeographicalAreaCode()](https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/PhoneNumberUtil.php#L609), including the warning above it.

That might have the information you want.

**Comment by ArtemGordinsky** [comment]
Thanks!
For my use case, reliability of area or carrier code extraction is not critical. So maybe there's also a way to get carrier code for mobile numbers? Sorry if I'm asking too many questions, but I just couldn't find it.

**Comment by giggsey** [comment]
Wouldn't the snippet in the comments above that function give you what you want for mobiles?

**Comment by ArtemGordinsky** [comment]
Looks like it does, but only for landlines. When I try a Ukrainian mobile number (e.g. 380969735537), ```getLengthOfGeographicalAreaCode()``` returns 0.

**Comment by giggsey** [comment]
Ahh yes, I see why. That function only works if the number if `$numberType == PhoneNumberType::FIXED_LINE || $numberType == PhoneNumberType::FIXED_LINE_OR_MOBILE`.

It makes sense that it can't return a geographical area code for numbers that aren't geographical.

I'll try to see if there is another function.

**Comment by giggsey** [comment]
Okay, I don't think it's possible. You can get the number in National Format, so it looks like `096 973 5537`. You could format it for mobile dialling, but that's unlikely to be any different from the national format.

**Comment by ArtemGordinsky** [comment]
How hard it would be to add such a method? I would gladly contribute.

**Comment by giggsey** [comment]
How would you actually work out the value though?

What's the answer for the number you provided? Or the answer for a UK mobile (+447700900000)?

**Comment by ArtemGordinsky** [comment]
No idea, actually :smile:
It's just that when I format the number as RFC3966, it correctly separates the carrier code (96), so I assumed that there must be some non-public method for doing that. Not sure about the UK number though — is "7700" correct?

**Comment by giggsey** [comment]
Your number in international format is `+380 96 973 5537`.
That UK number in international format is `+44 7700 900000`.

The library has the formatted rules for the various types of numbers.

In the UK, 07700 would sort of be considered the area/carrier code. In reality, because of number portability, it doesn't actually mean anything.

**Comment by ArtemGordinsky** [comment]
Well, I guess I'll just parse the formatted number to get the carrier code then. Should be enough in my case.
Thanks for your help!
