### ISSUE TITLE
new indicator +213 (28) -- -- --

### ISSUE THREAD

**Issue by alyes09** [giggsey/libphonenumber-for-php#665]
To add a new phone indicator for Algerian numbers in the giggsey/libphonenumber-for-php library,
 The new indicator  is 28   in PhoneNumberMetadata_DZ.php   .
Can you add it ?

'fixedLine' => [
        'NationalNumberPattern' => '9619\\d{5}|(?:1\\d|2[013-9]|3[0-8]|4[013-689])\\d{6}',
        'ExampleNumber' => '12345678',
        'PossibleLength' => [],
        'PossibleLengthLocalOnly' => [],
    ]

**Comment by giggsey** [comment]
Hi,

Please check the [FAQ](https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers) for checking with invalid numbers.

You'll need to check the number using [Google's Demo](https://libphonenumber.appspot.com/), then report the issue to them if the number still shows as invalid.

**Comment by alyes09** [comment]
Hello sir ,
this indicator of algeria is  new and valide  :  but  google say not valid  , you can look this capture 
![image](https://github.com/user-attachments/assets/c4b418c0-1cd5-471d-b4bb-45a6eed196dc)
