### ISSUE TITLE
The lib adds 398 if the number has ext. empty

### ISSUE THREAD

**Issue by mcapodacqua** [giggsey/libphonenumber-for-php#67]
Here is the result in the demo:
http://giggsey.com/libphonenumber/?phonenumber=%2B5493516315733+ext.&country=AR&language=&region=

as you can see, the input number is `+5493516315733 ext.`, and the parsed national number is `93516315733398`

**Comment by giggsey** [comment]
If you try the same thing on the [demo for Google's libphonenumber](https://libphonenumber.appspot.com/phonenumberparser) (which this project is a PHP fork of), you'll find it does the same thing.

Note how it does say the number is invalid (TOO_LONG), but if you actually had an extension, it would cope fine.

The reason it's changing `ext` into `398` is that it's converting the letters into the numbers they represent.

**Comment by mcapodacqua** [comment]
I see it on googlei18n/libphonenumber#459 .
You can go ahead and close this if you want, I think this is something that needs to be fixed in the master library first.
Thanks for the feedback @giggsey.

**Comment by giggsey** [comment]
If/Once it's fixed upstream, it'll get ported down to here, and released the next time Google tag a release.
