### ISSUE TITLE
Fatal error in ShortNumberInfo::isPossibleShortNumber

### ISSUE THREAD

**Issue by RuslanGetmansky** [giggsey/libphonenumber-for-php#68]
Fatal error appears here:
https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/ShortNumberInfo.php#L311 in `$phoneMetadata->getGeneralDesc()` when `$phoneMetadata` is null. 

It happens if region is not found in `ShortNumbersRegionCodeSet::$shortNumbersRegionCodeSet`. For example the number 322 for region NE (Niger)

**Comment by giggsey** [comment]
Thanks for that @RuslanGetmansky.

It'll get tagged in a new release once Google release their next version (to keep the version numbers in sync).

**Comment by RuslanGetmansky** [comment]
Thanks for fixing @giggsey

**Comment by giggsey** [comment]
It's also a bug in the Java version, so I've reported it upstream too.
