### ISSUE TITLE
[Feedback wanted] PhoneNumber->__toString() gives misleading data

### ISSUE THREAD

**Issue by giggsey** [giggsey/libphonenumber-for-php#75]
The current version of the PHP returns `+[Country Code][National Number]`.

However, this is misleading, as it looks like it's E164. However, for some regions/types of number, this is not valid. For example, the example number of Italy is `+390212345678`, but if you parse this number, then do a `__toString()` on it, it'll actually return `+39212345678` (note the missing 0 after the country code).

The Java version of the project does the following:

```java
    public String toString() {
      StringBuilder outputString = new StringBuilder();
      outputString.append("Country Code: ").append(countryCode_);
      outputString.append(" National Number: ").append(nationalNumber_);
      if (hasItalianLeadingZero() && isItalianLeadingZero()) {
        outputString.append(" Leading Zero(s): true");
      }
      if (hasNumberOfLeadingZeros()) {
        outputString.append(" Number of leading zeros: ").append(numberOfLeadingZeros_);
      }
      if (hasExtension()) {
        outputString.append(" Extension: ").append(extension_);
      }
      if (hasCountryCodeSource()) {
        outputString.append(" Country Code Source: ").append(countryCodeSource_);
      }
      if (hasPreferredDomesticCarrierCode()) {
        outputString.append(" Preferred Domestic Carrier Code: ").
            append(preferredDomesticCarrierCode_);
      }
      return outputString.toString();
    }
```

For the example Italian number, this causes the output to be: 
> Country Code: 39 National Number: 212345678 Leading Zero(s): true

My question to people who see this is: Should we change the string output to match what the Java version has. The issue has been present since 6fec96dcbea2607407a70d0baf2bbc34196dd625.

**Comment by Rvanlaak** [comment]
We used `__toString` to pass a phone number to our VoIP provider, which is broken now. This ofcourse is our own bad, we should have used the formatter. This initially wasn't clear to us, so maybe you can split the quite long readme into separate files under `/doc` and add a more explanative header on top of the formatting section? :+1:

**Comment by giggsey** [comment]
Apologies. This is what I had hoped to avoid.

I put it in the release notes when it went live, and the README states that
it doesn't follow exact semantic versioning.

Improving the documentation is needed, so I'll leave this issue open to do
that.

**Comment by Rvanlaak** [comment]
The `composer.json` of PhoneNumberBundle is pinned to `~5.7|~6.0|~7.0` so that also didn't catch that :+1: Where we usually check all upgrade notes, this one slipped through.
