### ISSUE TITLE
e-mail address converted to valid phone number

### ISSUE THREAD

**Issue by danielkesselberg** [giggsey/libphonenumber-for-php#76]
Hi Joshua, 

first of all: thanks for your great work!

I found a problem with libphonenumber-for-php. An e-mail address like Abc811@hotmail.com is converted to +498114686245266 which is a valid phone number for Germany.

https://libphonenumber.appspot.com/ reports an error for Abc811@hotmail.com.

best regards
Daniel

**Comment by giggsey** [comment]
Confirmed locally.

It'll be something to do with the translation of letters to numbers.

**Comment by giggsey** [comment]
Okay, Google's version gives you the same number if you don't have the '@' sign.

**Comment by giggsey** [comment]
Notes: The `getValidPhoneNumberPattern` is returning a regex, which is allowing the '@' through, whereas the Java version doesn't.

**Comment by giggsey** [comment]
This has now been fixed.

Unfortunately, I didn't look at this under after Google's latest release, so it won't be in a tagged release until they next do a release.

Such a small fix too... Thanks for reporting it :)

**Comment by danielkesselberg** [comment]
Thank you!
