### ISSUE TITLE
CamelCase namespace like LibPhoneNumber

### ISSUE THREAD

**Issue by rap2hpoutre** [giggsey/libphonenumber-for-php#77]
Namespace for this class is `libphonenumber`, it's a bit weird. Why not UpperCamelCase like `LibPhoneNumber`?

**Comment by giggsey** [comment]
It was just that way when I forked the project. I've also been reading a bit, and it seems Composer has some issues with namespaces in mixed case, so I'm a bit wary of changing it in case it broke BC.

Also, this project doesn't have a vendor name in the namespace, which itself is a bit odd.

Closing, as I don't feel it's worth the potential BC breakages.

**Comment by ruudk** [comment]
It would be really great if this could be considered for a next major release. Every time I see it I have the urge to fix it 🙈

**Comment by giggsey** [comment]
It might be a while before v9 comes along.

Either way, I don't think I'm going to change the namespace/package name.

Libraries are usually all lowercase. Google's README refers to it as libphonenumber.
