### ISSUE TITLE
PHP7 PCRE

### ISSUE THREAD

**Issue by jbboehr** [giggsey/libphonenumber-for-php#79]
In case you hadn't already tracked it down, the failing tests on PHP7 appear to be related to be a bug: https://bugs.php.net/bug.php?id=70110

**Comment by giggsey** [comment]
Thanks, HHVM has a similar issue.

**Comment by giggsey** [comment]
Local reproducible version: https://3v4l.org/pICqY

That PHP Bug mentions the stack limit, but the regex here is fairly small, so I'm not sure it's that.

It's failing on PHP7 + HHVM.

**Comment by giggsey** [comment]
Reported separately at https://bugs.php.net/bug.php?id=70304

**Comment by jbboehr** [comment]
Sorry, I should've mentioned that it was working with pcre.jit=0.

**Comment by giggsey** [comment]
Worked around by #89

**Comment by mfix** [comment]
Hi, I am having a problem with this again - "the bad regexp" was restored https://github.com/giggsey/libphonenumber-for-php/commit/9732331f19e638099e2342a2fbd1bf750dfcd6b2#diff-5577ba297642a6aebb3e35ea375e6870

Was it intended? How should I use it now to have a working regex (the separated one)? Thanks in advance!

**Comment by giggsey** [comment]
Strange how the unit test wasn't failing again.

Reopened for now, as the metadata is indeed incorrect.

**Comment by giggsey** [comment]
@mfix It's been resolved as of the latest commit. The line endings got messed up in my local copy, so it wasn't applying the patch.
