### ISSUE TITLE
New Phone numbers are not giving proper results

### ISSUE THREAD

**Issue by ishanrustagi** [giggsey/libphonenumber-for-php#80]
I am using this API and have downloaded the whole project through composer.
So whenever the any git file is updated would i'll be notified ?
If not, how would i'll updating my API with the new number series.

**Comment by giggsey** [comment]
There are websites that can monitor your Packagist dependencies, and let you know whether there have been any updates. One example is: https://www.versioneye.com/

I'm going to close this issue, as it's not actually an issue with the project.
