### ISSUE TITLE
Build failed: You must specify readable directory as repository.

### ISSUE THREAD

**Issue by schwich** [giggsey/libphonenumber-for-php#82]
vendor/giggsey/libphonenumber-for-php/build.xml:98:33: You must specify readable directory as repository.

vendor/giggsey/libphonenumber-for-php/vendor/phing/phing/classes/phing/tasks/ext/git/GitFetchTask.php(111): GitBaseTask->getGitClient(false, 'libphonenumber-...')

Happens when I try to run vendor/bin/phing compile.

**Comment by giggsey** [comment]
If you have `libphonenumber-for-php` installed as a dependency (which it appears to be given that it's in vendor/), you don't need to compile any data (it's already compiled)

**Comment by schwich** [comment]
Thanks for the quick response! When I try to get an instance of phoneUtil, it fails with "missing metadata". The libphonenumber-for-php/src/libphonenumber\data directory is empty

**Comment by giggsey** [comment]
Weird. How did you install it?

If you ran `phing compile`, it actually deletes all the data directory before compiling it again.

**Comment by schwich** [comment]
Thanks, phing compile definitely wiped out the directory. Reinstalled and it works. Well, it works after I moved the src/libphonenumber/data directory up one directory to src/data. It was throwing an exception because it was looking for the data directory in the wrong place.

**Comment by giggsey** [comment]
Weird about the src/libphonenumber/data issue. But I'm glad you got it working :)

**Comment by schwich** [comment]
Thanks for all your hard work and quick responses!
