### ISSUE TITLE
Online demo is not working

### ISSUE THREAD

**Issue by damnedest** [giggsey/libphonenumber-for-php#83]

**Comment by giggsey** [comment]
Thanks, will get that sorted asap.

**Comment by giggsey** [comment]
Right, there was an issue with the DNS server. The faulty record has been fixed (but it'll take a while to propagate).

I'll close this issue, as this should be resolved within a few hours.

In the mean time, you should be able to get to the demo via http://libphonenumber-for-php.giggsey.net/
