### ISSUE TITLE
Generate international number with country code, not name

### ISSUE THREAD

**Issue by opb** [giggsey/libphonenumber-for-php#84]
Hi there

I'm trying to work out how to get an international number using the country code instead of the country name - e.g. '44' instead of 'GB'. Obviously the simple format is `'+'.$countryCode+phoneNumber`, but seeing as only some countries drop the preceding zero, a simple rule like that wouldn't work (I don't think). 

```
$countryCode = '44';
$phone = '01234567899';
$internationalNumber = '+441234567899';
```

Is there a way to do this with this library? essentially I just want to send '44' to the `parse()` function instead of 'GB';

Thanks!

**Comment by giggsey** [comment]
There's a function called `getRegionCodeForCountryCode()`, which accepts a country calling code, and will return 'ZZ' (if it doesn't exist), or the first region code for that calling code (44 is actually GB, GG, IM and JE)

**Comment by opb** [comment]
Awesome, thanks!
