### ISSUE TITLE
Parse doesn't allow country code to be blank

### ISSUE THREAD

**Issue by colouredFunk** [giggsey/libphonenumber-for-php#85]
If supplying an international number to parse, the country code should be optional. 

$phoneUtil = \libphonenumber\PhoneNumberUtil::getInstance();
$number = $phoneUtil->parse($phone, "");

Example -  http://libphonenumber.appspot.com/, enter a international number, leave step 2 and 3, it parse the number correctly and returns country code etc.

**Comment by giggsey** [comment]
I just tried that, and it works fine

```php
require __DIR__ . '/vendor/autoload.php';

$phoneNumberUtil = \libphonenumber\PhoneNumberUtil::getInstance();

$phoneObj = $phoneNumberUtil->parse("+441174960000", '');

var_dump($phoneNumberUtil->isValidNumber($phoneObj));
var_dump($phoneNumberUtil->format($phoneObj, \libphonenumber\PhoneNumberFormat::E164));
```

Returns 

> bool(true)
> string(13) "+441174960000"

That matches the Java API. The parameter is required, but can be `null`, or an empty string.

The demo might not allow empty country names, but I could fix that if that's the issue you're having.

**Comment by giggsey** [comment]
No reply for 3 days, closing.

If you are still having an issue, please reopen this.

**Comment by samanala-athaudahetti** [comment]
I believe some piece of information is missing here.

If the number is WITH THE COUNTRY CODE, it does parse with a blank country code.

But if your number does not have the country code, we have to pass the country code as the second param.

In short, We need to have the country code.
