### ISSUE TITLE
getAsYouTypeFormatter missing

### ISSUE THREAD

**Issue by vladrusu** [giggsey/libphonenumber-for-php#87]
Hello !
I saw that the getAsYouTypeFormatter functionality is missing from your package. :(
It is present it the official Google library (v7.1.0).

Can you please implement it?

I am refering to this:
Formatting Phone Numbers 'as you type'

PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
AsYouTypeFormatter formatter = phoneUtil.getAsYouTypeFormatter("US");
System.out.println(formatter.inputDigit('6'));  // Outputs "6"
...  // Input more digits
System.out.println(formatter.inputDigit('3'));  // Now outputs "650 253"

**Comment by giggsey** [comment]
Hi,

What's the point of an As You Type Formatter for PHP?

If you are doing it via a web form, then you would need to send an AJAX
request for every character typed (in which case you might as well use the
JavaScript version).

**Comment by vladrusu** [comment]
Hi!
For a project I currently work on, I would like to parse/format a partial introduced number programatically (in server code, not AJAX).
For example:
Partial number: 1555245
Country Code: US
Expected result: 1 555-245

Using  $phoneUtil->format on "1555245" gives me these results:
E164 format	invalid
Original format	155-5245
National format	155-5245

Currently, I am unaware of a way to get "1 555-245" from "1555245". If you know one, please let me know.

**Comment by giggsey** [comment]
Sorry, but I still don't see the use case. I can't think of a reason you would need to format a partially input number, unless you are expecting further input.

**Comment by giggsey** [comment]
Closing issue.

I'll be happy to re-open it if you can convince me of a use case.

**Comment by alexmatveev** [comment]
@giggsey one case is for getting all possible prefixes for country code, I guess.

**Comment by giggsey** [comment]
The AsYouTypeFormatter wouldn't help there though, because it wouldn't format the number until you hit a valid number.

**Comment by alexmatveev** [comment]
What's the way to get this?

![dominican republic country code 1 809 country code do 2016-05-26 16-46-19](https://cloud.githubusercontent.com/assets/1456669/15576675/a396e942-2361-11e6-8c45-779c64a246b9.png)

**Comment by giggsey** [comment]
I don't think that's actually possible.

You can get the patterns for each number type, but you'll have to work out the prefix by yourself.

**Comment by giggsey** [comment]
Reopening, as I'm going to implement this.

**Comment by AlexanderMatveev** [comment]
@giggsey that's good :+1:
