### ISSUE TITLE
Invalid phone numer

### ISSUE THREAD

**Issue by Venzon** [giggsey/libphonenumber-for-php#90]
+46 44203686890x

Such phone number is not recognized as valid but it exists in GB
I replaced last digit with x
Any idea why its not valid?

Regards

**Comment by giggsey** [comment]
What's the values you are passing to the parse() function (number + region).

**Comment by Venzon** [comment]
default region is 'PL' for parse method

**Comment by Venzon** [comment]
we are unable to call this numer but we received call from such numer registered by our telephone exchange
maybe its some kind of voip numer
anyway seems that such numer does not exists for calling back
closing issue then

**Comment by giggsey** [comment]
Country code +46 isn't GB, which was my confusion.

**Comment by giggsey** [comment]
Okay, had a bit more time to look at this.

You are passing it a number starting 004644, which ends up looking for a Swedish number starting with 44.

The international dialling code for GB is 44, so if you have your number 0044203686890x, it'll return a valid number.
