### ISSUE TITLE
Sénégal numbers should also start with 78

### ISSUE THREAD

**Issue by temgo** [giggsey/libphonenumber-for-php#91]
Hello

In Sénégal (SN) it appears numbers starting with 78 are not accepted or even recognize as mobile phone numbers.

Can we double check that issue?

Thanks

**Comment by giggsey** [comment]
Hi,

Please see the section in the README about Invalid Numbers: https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers

If you know that the number should be valid, please [report it upstream to them](https://github.com/googlei18n/libphonenumber/issues).

There already seems to be an issue on Google's project for Sénégal mobile numbers at https://github.com/googlei18n/libphonenumber/issues/919
