### ISSUE TITLE
Djibouti Number showing as invalid when its valid

### ISSUE THREAD

**Issue by mcocaro** [giggsey/libphonenumber-for-php#92]
The number +253 77 080000 is a valid phone number from Evatis carrier in Djibouti and is showing up as invalid.

**Comment by giggsey** [comment]
Hi,

Please see the section in the README about Invalid Numbers: https://github.com/giggsey/libphonenumber-for-php#problems-with-invalid-numbers

The number you provided also returns invalid when using [Google's demo](https://libphonenumber.appspot.com). If you know that the number should be valid, please [report it upstream to them](https://github.com/googlei18n/libphonenumber/issues).
