### ISSUE TITLE
isValidNumber also accepts letters

### ISSUE THREAD

**Issue by mstoelzle** [giggsey/libphonenumber-for-php#95]
Hi,
I want to to validate swiss mobile phone numbers. Now if I enter letters in between the numbers or after a valid phone number it just "cuts them out" and $phoneUtil->isValidNumberForRegion($phoneNumber, $region) returns "true"; How can I prevent that? The parse function returns the following object:

```
libphonenumber\PhoneNumber::__set_state(array(
   'countryCode' => 41,
   'nationalNumber' => '799425028',
   'extension' => NULL,
   'italianLeadingZero' => NULL,
   'rawInput' => '+41799425s028',
   'countryCodeSource' => 0,
   'preferredDomesticCarrierCode' => '',
   'hasNumberOfLeadingZeros' => false,
   'numberOfLeadingZeros' => 1,
))
```

Your demo site works well concerning this problem. I didn't find yet the difference, what you're doing better ;)
Thanks for your help

**Comment by giggsey** [comment]
If I try the same input via Google's demo, it does the same thing [+41799425s028](https://libphonenumber.appspot.com/phonenumberparser?number=%2B41799425s028&country=CH).

So it is ignoring the 's'. From the PhoneNumber object it returned, you can see it's set nationalNumber to the number without the 's'.

There might be a way of forcing the letters to stay, and for validation to fail. I'll have a look through the methods tomorrow morning (GMT). I think it would be one of the parameters of `parse()` or `parseandKeepRawInput()`.

**Comment by giggsey** [comment]
Okay, I don't see a way of keeping the raw number.

The [`normalize()`](https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/PhoneNumberUtil.php#L1714-L1739) will convert letters into numbers, but **only** if there are 3 or more letters in the input. Otherwise, it just strips all the letters, leaving the digits.

What are you trying to achieve?

**Comment by mstoelzle** [comment]
Ok thank you for your answer and help. I just wanted to validate a mobile phone input with this script and didn't want to accept letters... I'm now validating for letters etc with a normal preg_match and regex, so that should work.

**Comment by andrew-lewell** [comment]
Hi, sorry to resurrect an old issue, but is there a reason that the validation accepts letters and just cuts them out? It seems to only be 1 or 2 letters/symbols
